cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED APP_BASE_ROOT)
    set(APP_BASE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()

file(REAL_PATH "${APP_BASE_ROOT}" app_base_root)
set(manifest "${app_base_root}/MANIFEST.sha256")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "missing app-base product manifest: ${manifest}")
endif()

file(STRINGS "${manifest}" lines)
set(paths)
set(revision FALSE)
foreach(line IN LISTS lines)
    if(line MATCHES "^# corpus-revision: .+$")
        set(revision TRUE)
    elseif(line MATCHES "^#" OR line STREQUAL "")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid app-base product manifest line: ${line}")
    else()
        set(expected_hash "${CMAKE_MATCH_1}")
        set(relative_path "${CMAKE_MATCH_2}")
        if(relative_path IN_LIST paths)
            message(FATAL_ERROR "duplicate app-base product manifest path: ${relative_path}")
        endif()
        set(path "${app_base_root}/${relative_path}")
        if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
            message(FATAL_ERROR "missing app-base product source: ${relative_path}")
        endif()
        file(READ "${path}" contents)
        string(FIND "${contents}" "\r" carriage_return)
        if(NOT carriage_return EQUAL -1)
            message(FATAL_ERROR "app-base product source must use LF: ${relative_path}")
        endif()
        file(SHA256 "${path}" actual_hash)
        string(TOUPPER "${actual_hash}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "app-base product manifest mismatch: ${relative_path}")
        endif()
        list(APPEND paths "${relative_path}")
    endif()
endforeach()
if(NOT revision)
    message(FATAL_ERROR "app-base product manifest has no corpus revision")
endif()

file(GLOB_RECURSE actual_paths RELATIVE "${app_base_root}" "${app_base_root}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${app_base_root}/${relative_path}" OR
       relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST paths)
        message(FATAL_ERROR "app-base product manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "app-base product manifest stale path: ${relative_path}")
    endif()
endforeach()

message(STATUS "app-base product manifest verified: ${app_base_root}")
