cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED IBMPC_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit ibmpc and probe roots required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/board-common" "${PROBE_ROOT}/board-at" "${PROBE_ROOT}/product" "${PROBE_ROOT}/machine")
function(reject owner source build expected)
    file(WRITE "${PROBE_ROOT}/${owner}/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DIBMPC_ROOT=${PROBE_ROOT}
        -P "${IBMPC_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(REMOVE "${PROBE_ROOT}/${owner}/probe.c")
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject(product "#include \"app-nxvm/product/config.h\"\n" "" "Noncanonical")
reject(product "#include \"app-nxvm/machine/machine_private.h\"\n" "" "Noncanonical")
reject(product "#include \"common/machine/input_queue.h\"\n" "" "Private dependency")
reject(board-common "#include \"app-nxvm/devices/machine_board_interface.h\"\n" "" "Noncanonical")
reject(board-common "#include \"x86/chips/video/video.h\"\n" "" "Private dependency")
reject(board-common "#include \"x86/chips/pit825x/pit.h\"\n" "" "Private dependency")
reject(board-common "#include \"x86/core/port.h\"\n" "" "Private dependency")
reject(board-common "" "target_link_libraries(ibmpc-board-common PRIVATE x86-core)\n" "Board adapter must not select Core")
reject(board-common "" "target_link_libraries(ibmpc-board-common PRIVATE x86-core-observable)\n" "Board adapter must not select Core")
reject(board-common "" "target_link_libraries(ibmpc-board-common PRIVATE common-machine)\n" "Forbidden ibmpc edge")
reject(board-at "#include \"ibmpc/board-common/machine_board_state.h\"\n" "" "Forbidden ibmpc edge")
reject(machine "#include \"ibmpc/board-common/machine_board_state.h\"\n" "" "Private dependency")
reject(product "#include <windows.h>\n" "" "Noncanonical")
reject(product "" "if(WIN32)\nendif()\n" "must not select platform")
file(REMOVE "${PROBE_ROOT}/CMakeLists.txt")
