if(NOT DEFINED LIBRARY_ROOT)
    set(LIBRARY_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
cmake_policy(SET CMP0057 NEW)
include("${CMAKE_CURRENT_LIST_DIR}/verify_component_dependencies.cmake")

file(GLOB_RECURSE types_files RELATIVE "${LIBRARY_ROOT}/types"
    "${LIBRARY_ROOT}/types/*")
foreach(path IN LISTS types_files)
    if(NOT path MATCHES "\\.h$" AND NOT path STREQUAL "README.md")
        message(FATAL_ERROR "types must contain declarations only: ${path}")
    endif()
    if(NOT path MATCHES "\\.h$")
        continue()
    endif()
    file(READ "${LIBRARY_ROOT}/types/${path}" source)
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" " " source "${source}")
    string(REGEX REPLACE "//[^\n]*" " " source "${source}")
    if(source MATCHES "#[ \t]*(if|ifdef|ifndef|elif)[^\n]*(^|[^A-Za-z0-9_])(_WIN32|WIN32|_WIN64|__linux__|__APPLE__)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "types must not select an operating system: ${path}")
    endif()
    if(NOT path MATCHES "/")
        if(source MATCHES "lib/types/(win32|linux)/")
            message(FATAL_ERROR "Common types header imports platform vocabulary: ${path}")
        endif()
        string(REGEX MATCHALL "#[ \t]*include[ \t]*<[^>]+>" includes "${source}")
        foreach(line IN LISTS includes)
            if(NOT line MATCHES "<(assert|complex|ctype|errno|fenv|float|inttypes|iso646|limits|locale|math|setjmp|signal|stdalign|stdarg|stdatomic|stdbool|stddef|stdint|stdio|stdlib|stdnoreturn|string|tgmath|threads|time|uchar|wchar|wctype)\\.h>" AND
               NOT (path STREQUAL "atomic.h" AND line MATCHES "<intrin\\.h>"))
                message(FATAL_ERROR "Non-C declaration in common types header: ${path}: ${line}")
            endif()
        endforeach()
        if(NOT path STREQUAL "atomic.h" AND source MATCHES "_MSC_VER")
            message(FATAL_ERROR "Only atomic compiler adaptation is admitted: ${path}")
        endif()
    elseif(NOT path MATCHES "^(win32|linux)/[^/]+\\.h$")
        message(FATAL_ERROR "Unexpected types platform layout: ${path}")
    elseif(source MATCHES "(^|[^A-Za-z0-9_])(if|for|while|switch)[ \t\r\n]*\\(")
        message(FATAL_ERROR "Component control flow belongs outside types: ${path}")
    endif()
endforeach()

set(external_tokens "malloc;calloc;free;memset;memcpy;memcmp;memchr;strlen;clock_gettime")
foreach(path IN LISTS types_files)
    if(NOT path MATCHES "\\.h$")
        continue()
    endif()
    file(READ "${LIBRARY_ROOT}/types/${path}" declarations)
    string(REGEX MATCHALL "#[ \t]*define[ \t]+(lib_|LIB_)[A-Za-z0-9_]+[ \t]+[A-Za-z_][A-Za-z0-9_]*" aliases "${declarations}")
    foreach(alias IN LISTS aliases)
        string(REGEX REPLACE ".*[ \t]([A-Za-z_][A-Za-z0-9_]*)$" "\\1" token "${alias}")
        if(NOT token MATCHES "^(lib_|LIB_)")
            list(APPEND external_tokens "${token}")
        endif()
    endforeach()
    string(REGEX MATCHALL "typedef[ \t]+(struct[ \t]+)?[A-Za-z_][A-Za-z0-9_]*[ \t]+lib_[A-Za-z0-9_]+" aliases "${declarations}")
    foreach(alias IN LISTS aliases)
        string(REGEX REPLACE "typedef[ \t]+(struct[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]+lib_.*" "\\2" token "${alias}")
        if(NOT token MATCHES "^(int|long|short|char|float|double|void|unsigned|signed|volatile|const|enum|struct)$")
            list(APPEND external_tokens "${token}")
        endif()
    endforeach()
endforeach()
list(REMOVE_DUPLICATES external_tokens)
list(JOIN external_tokens "|" external_pattern)

# Independent families: catch unwrapped vocabulary too. This is a finite
# source gate, not a C parser; new external families still require review.
set(external_families "u?int([0-9]+|_least[0-9]+|_fast[0-9]+|ptr|max)_t|(U?INT[A-Z0-9_]*|SIZE|PTRDIFF|WCHAR|WINT)_(MAX|MIN)|INT[0-9]+_C|UINT[0-9]+_C|pthread_[A-Za-z0-9_]+|PTHREAD_[A-Za-z0-9_]+|CLOCK_[A-Za-z0-9_]+|VK_[A-Za-z0-9_]+|WM_[A-Za-z0-9_]+|WAIT_[A-Za-z0-9_]+|ERROR_[A-Za-z0-9_]+|LP[A-Z][A-Z0-9_]*|H(WND|ANDLE|DC|ICON|CURSOR|BRUSH|FONT|INSTANCE)|DWORD|WORD|BOOL|UINT|LRESULT|WPARAM|LPARAM")
set(external_calls "realloc|memmove|strcpy|strncpy|strcmp|strncmp|strchr|strstr|strtok|printf|fprintf|snprintf|vsnprintf|fopen|fclose|fread|fwrite|fflush|fseek|ftell|ferror|feof|remove|rename|nanosleep|clock_gettime|open|close|read|write|lseek|fcntl|fsync|poll|select|Set[A-Z][A-Za-z0-9_]*|Get[A-Z][A-Za-z0-9_]*|Create[A-Z][A-Za-z0-9_]*|Destroy[A-Z][A-Za-z0-9_]*|WaitFor[A-Z][A-Za-z0-9_]*")

foreach(obsolete IN ITEMS win32.h posix.h clock.h input.h win32_runtime.h)
    if(EXISTS "${LIBRARY_ROOT}/types/${obsolete}")
        message(FATAL_ERROR "Obsolete types umbrella/dispatcher: ${obsolete}")
    endif()
endforeach()

file(GLOB_RECURSE library_sources RELATIVE "${LIBRARY_ROOT}"
    "${LIBRARY_ROOT}/*.c" "${LIBRARY_ROOT}/*.h")
foreach(path IN LISTS library_sources)
    if(NOT path MATCHES "^types/" AND path MATCHES "^[^/]+/(win32|linux)/.*_interface\\.h$")
        message(FATAL_ERROR "Platform implementation cannot declare a public interface: ${path}")
    endif()
    if(NOT path MATCHES "^types/")
        file(READ "${LIBRARY_ROOT}/${path}" body)
        string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" " " body "${body}")
        string(REGEX REPLACE "//[^\n]*" " " body "${body}")
        if(body MATCHES "ui_keyboard_submit_transition")
            message(FATAL_ERROR "Obsolete keyboard entry restored: ${path}")
        endif()
        string(REGEX REPLACE "\"([^\"\\\\]|\\\\.)*\"" " " body "${body}")
        if(path MATCHES "^ui-(window|console)/" AND
           body MATCHES "(^|[^A-Za-z0-9_])ui_keyboard_(submit_transition|submit_utf16|platform_[A-Za-z0-9_]+|note_recovered_key|release_recovered_key|consume_duplicate_character)[ \t\r\n]*\\(")
            message(FATAL_ERROR "UI leaf bypasses shared keyboard record entry: ${path}")
        endif()
        if(path MATCHES "^(host|ui-window)/win32/" AND
           body MATCHES "lib_win32_(read_console_input_a|write_console_output_a|register_class_a|create_window_ex_a|dispatch_message_a|peek_message_a)[ \t\r\n]*\\(")
            message(FATAL_ERROR "ANSI input bypasses Unicode record contract: ${path}")
        endif()
        if(body MATCHES "(^|[^A-Za-z0-9_])(${external_pattern}|UI_WIN32_KEY_[A-Za-z0-9_]+)([^A-Za-z0-9_]|$)")
            message(FATAL_ERROR "External vocabulary bypasses types in ${path}: ${CMAKE_MATCH_2}")
        endif()
        if(body MATCHES "(^|[^A-Za-z0-9_])(${external_families})([^A-Za-z0-9_]|$)" OR
           body MATCHES "(^|[^A-Za-z0-9_])(${external_calls})[ \t\r\n]*\\(")
            message(FATAL_ERROR "Unwrapped external vocabulary in ${path}: ${CMAKE_MATCH_2}")
        endif()
    endif()
    file(STRINGS "${LIBRARY_ROOT}/${path}" includes REGEX "^[ \t]*#[ \t]*include")
    foreach(line IN LISTS includes)
        if(NOT line MATCHES "#[ \t]*include[ \t]*[\"<]")
            message(FATAL_ERROR "Computed include bypasses ownership check: ${path}: ${line}")
        endif()
        if(line MATCHES "<lib/")
            message(FATAL_ERROR "Library includes require canonical quoted paths: ${path}: ${line}")
        endif()
        # Canonical paths make ownership checkable; relative traversal must not
        # bypass the same cross-component boundary enforced below.
        if(line MATCHES "\"([^\"]+)\"")
            set(include_path "${CMAKE_MATCH_1}")
            if(NOT include_path MATCHES "^lib/" OR include_path MATCHES "(^|/)\\.\\.?(/|$)")
                message(FATAL_ERROR "Library include must use a canonical component path: ${path}: ${line}")
            endif()
        endif()
        if(line MATCHES "\"lib/([^/]+)/([^\"]+)\"")
            set(dependency "${CMAKE_MATCH_1}")
            set(header "${CMAKE_MATCH_2}")
            string(REGEX REPLACE "/.*" "" owner "${path}")
            library_check_edge("${owner}" "${dependency}")
            if(NOT dependency STREQUAL owner AND NOT dependency STREQUAL "types" AND
               NOT header MATCHES "^[^/]+_interface\\.h$")
                message(FATAL_ERROR "Cross-component implementation include: ${path}: ${line}")
            endif()
            if(NOT dependency STREQUAL "types" AND header MATCHES "^(win32|linux)/")
                set(platform "${CMAKE_MATCH_1}")
                if(NOT dependency STREQUAL owner OR NOT path MATCHES "^[^/]+/${platform}/")
                    message(FATAL_ERROR "Platform implementation is component-local: ${path}: ${line}")
                endif()
            endif()
        endif()
        if(NOT path MATCHES "^types/" AND line MATCHES "#[ \t]*include[ \t]*<")
            message(FATAL_ERROR "External declarations bypass types: ${path}: ${line}")
        endif()
        if(line MATCHES "lib/types/(win32|linux)/")
            set(platform "${CMAKE_MATCH_1}")
            if(NOT path MATCHES "(^|/)${platform}/")
                message(FATAL_ERROR "Platform vocabulary crosses a neutral/other-platform boundary: ${path}")
            endif()
        endif()
        if(line MATCHES "lib/types/(win32|posix|clock|input|win32_runtime)\\.h")
            message(FATAL_ERROR "Obsolete types include: ${path}")
        endif()
    endforeach()
endforeach()
message(STATUS "types platform layout and declaration ownership verified")
