# One exact direct-edge map for source includes and build linkage.
foreach(retired IN ITEMS kvm-base/mailbox_wake_interface.h
        kvm-base/win32/mailbox.c kvm-base/linux/mailbox.c)
    if(EXISTS "${LIBRARY_ROOT}/${retired}")
        message(FATAL_ERROR "Default mailbox wake must reuse Base Event: ${retired}")
    endif()
endforeach()
set(library_components types base console console-broker storage kvm-base kvm-window kvm-console)
set(library_dependencies_types "")
set(library_dependencies_base types)
set(library_dependencies_console types base)
set(library_dependencies_console-broker types base console)
set(library_dependencies_storage types)
set(library_dependencies_kvm-base types base)
set(library_dependencies_kvm-window types kvm-base)
set(library_dependencies_kvm-console types base console kvm-base)

function(library_check_edge owner dependency)
    if(NOT owner IN_LIST library_components OR NOT dependency IN_LIST library_components)
        message(FATAL_ERROR "Unknown component edge: ${owner} -> ${dependency}")
    endif()
    if(NOT owner STREQUAL dependency AND
       NOT dependency IN_LIST library_dependencies_${owner})
        message(FATAL_ERROR "Forbidden component edge: ${owner} -> ${dependency}")
    endif()
endfunction()

file(GLOB_RECURSE library_component_sources LIST_DIRECTORIES FALSE
    "${LIBRARY_ROOT}/*.c" "${LIBRARY_ROOT}/*.h")
foreach(source IN LISTS library_component_sources)
    file(RELATIVE_PATH relative_source "${LIBRARY_ROOT}" "${source}")
    string(REPLACE "\\" "/" relative_source "${relative_source}")
    string(REGEX MATCH "^([^/]+)/" ignored "${relative_source}")
    set(owner "${CMAKE_MATCH_1}")
    file(READ "${source}" source_text)
    if(relative_source MATCHES "^host/" OR
       source_text MATCHES "host_console|HOST_CONSOLE|lib/host/")
        message(FATAL_ERROR "Retired Host naming; use console-broker: ${relative_source}")
    endif()
    if(NOT owner IN_LIST library_components)
        continue()
    endif()
    if(owner STREQUAL "kvm-base" AND
       source_text MATCHES "KVM_(COMPONENT_)?CONTROL_(SET_WINDOW|RELEASE_WINDOW)|KVM_WINDOW_CONTROL_|KVM_COMPONENT_WINDOW_TITLE_CAPACITY")
        message(FATAL_ERROR "Window controls belong to kvm-window, not kvm-base: ${relative_source}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*\"[^\"]+\""
        quoted_includes "${source_text}")
    foreach(quoted_include IN LISTS quoted_includes)
        string(REGEX REPLACE ".*\"([^\"]+)\"" "\\1"
            include_path "${quoted_include}")
        if(NOT include_path MATCHES "^lib/([^/]+)/")
            message(FATAL_ERROR "Library source include must use canonical lib/<component>/ path: ${relative_source}: ${include_path}")
        endif()
        string(REGEX REPLACE "^lib/([^/]+)/.*" "\\1"
            dependency "${include_path}")
        if(dependency IN_LIST library_components)
            library_check_edge("${owner}" "${dependency}")
        endif()
    endforeach()
endforeach()

if(EXISTS "${LIBRARY_ROOT}/kvm-window/win32/component.c")
    file(READ "${LIBRARY_ROOT}/kvm-window/win32/component.c" window_worker)
    if(window_worker MATCHES "base_sync_event_wait|kvm_mailbox_wake_wait|kvm_component_mailboxes_wake")
        message(FATAL_ERROR "Window must use its selected message notifier, not an Event bridge")
    endif()
    if(window_worker MATCHES "win32_window_cursor_blink_timeout")
        message(FATAL_ERROR "Cursor timing belongs only to the Window timer, not outer-loop waits")
    endif()
    string(REGEX MATCHALL "win32_window_advance_cursor_blink[ \t\r\n]*\\(" blink_entries "${window_worker}")
    list(LENGTH blink_entries blink_entry_count)
    if(NOT blink_entry_count EQUAL 2)
        message(FATAL_ERROR "Expected one blink definition and one timer dispatch call")
    endif()
endif()

if(EXISTS "${LIBRARY_ROOT}/CMakeLists.txt")
    file(READ "${LIBRARY_ROOT}/CMakeLists.txt" build_contract)
    string(REGEX REPLACE "#[^\n]*" "" build_contract "${build_contract}")
    string(TOLOWER "${build_contract}" build_contract)
    # Do not allow another spelling to bypass the direct-edge verifier.
    if(build_contract MATCHES "(^|[^A-Za-z_])link_libraries[ \t\r\n]*\\(" OR
       build_contract MATCHES "(interface_)?link_libraries[ \t\r\n]+")
        message(FATAL_ERROR "Use explicit target_link_libraries for component dependencies")
    endif()
    string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${build_contract}")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
        list(POP_FRONT args owner)
        foreach(dependency IN LISTS args)
            if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
                continue()
            endif()
            if(owner STREQUAL "lib-neutral-corpus" AND dependency IN_LIST library_components)
                continue()
            endif()
            if(dependency IN_LIST library_components)
                library_check_edge("${owner}" "${dependency}")
            elseif((dependency STREQUAL "user32" AND owner MATCHES "^(console-broker|kvm-base|kvm-window)$") OR
                   (dependency STREQUAL "gdi32" AND owner STREQUAL "kvm-window") OR
                   (dependency STREQUAL "threads::threads" AND owner STREQUAL "base"))
                continue()
            else()
                message(FATAL_ERROR "Unadmitted link: ${owner} -> ${dependency}")
            endif()
        endforeach()
    endforeach()
endif()
