# One exact direct-edge map for source includes and build linkage.
set(library_components types console host storage ui-base ui-window ui-console)
set(library_dependencies_types "")
set(library_dependencies_console types)
set(library_dependencies_host types console)
set(library_dependencies_storage types)
set(library_dependencies_ui-base types)
set(library_dependencies_ui-window types ui-base)
set(library_dependencies_ui-console types console ui-base)

function(library_check_edge owner dependency)
    if(NOT owner IN_LIST library_components OR NOT dependency IN_LIST library_components)
        message(FATAL_ERROR "Unknown component edge: ${owner} -> ${dependency}")
    endif()
    if(NOT owner STREQUAL dependency AND
       NOT dependency IN_LIST library_dependencies_${owner})
        message(FATAL_ERROR "Forbidden component edge: ${owner} -> ${dependency}")
    endif()
endfunction()

if(EXISTS "${LIBRARY_ROOT}/CMakeLists.txt")
    file(READ "${LIBRARY_ROOT}/CMakeLists.txt" build_contract)
    string(REGEX REPLACE "#[^\n]*" "" build_contract "${build_contract}")
    string(TOLOWER "${build_contract}" build_contract)
    # Do not allow another spelling to bypass the direct-edge verifier.
    if(build_contract MATCHES "(^|[^A-Za-z_])link_libraries[ \t\r\n]*\\(" OR
       build_contract MATCHES "(interface_)?link_libraries[ \t\r\n]+")
        message(FATAL_ERROR "Use explicit target_link_libraries for component dependencies")
    endif()
    string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${build_contract}")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
        list(POP_FRONT args owner)
        foreach(dependency IN LISTS args)
            if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
                continue()
            endif()
            if(owner STREQUAL "lib-neutral-corpus" AND dependency IN_LIST library_components)
                continue()
            endif()
            if(dependency IN_LIST library_components)
                library_check_edge("${owner}" "${dependency}")
            elseif((dependency STREQUAL "user32" AND owner MATCHES "^(host|ui-base|ui-window)$") OR
                   (dependency STREQUAL "gdi32" AND owner STREQUAL "ui-window") OR
                   (dependency STREQUAL "threads::threads" AND owner MATCHES "^(console|host|ui-base)$"))
                continue()
            else()
                message(FATAL_ERROR "Unadmitted link: ${owner} -> ${dependency}")
            endif()
        endforeach()
    endforeach()
endif()
