if(NOT DEFINED LIBRARY_ROOT)
    set(LIBRARY_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()

file(REAL_PATH "${LIBRARY_ROOT}" library_root)
set(library_manifest "${library_root}/MANIFEST.sha256")
if(NOT EXISTS "${library_manifest}")
    message(FATAL_ERROR "missing library manifest: ${library_manifest}")
endif()

file(STRINGS "${library_manifest}" manifest_lines)
set(manifest_paths)
set(manifest_revision FALSE)
foreach(line IN LISTS manifest_lines)
    if(line MATCHES "^# corpus-revision: .+$")
        set(manifest_revision TRUE)
    elseif(line MATCHES "^#" OR line STREQUAL "")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid library manifest line: ${line}")
    else()
        set(expected_hash "${CMAKE_MATCH_1}")
        set(relative_path "${CMAKE_MATCH_2}")
        string(LENGTH "${expected_hash}" hash_length)
        if(NOT hash_length EQUAL 64)
            message(FATAL_ERROR "invalid library manifest hash: ${relative_path}")
        endif()
        if(relative_path IN_LIST manifest_paths)
            message(FATAL_ERROR "duplicate library manifest path: ${relative_path}")
        endif()
        set(source_path "${library_root}/${relative_path}")
        if(NOT EXISTS "${source_path}" OR IS_DIRECTORY "${source_path}")
            message(FATAL_ERROR "missing library source: ${relative_path}")
        endif()
        file(READ "${source_path}" contents)
        string(FIND "${contents}" "\r" carriage_return)
        if(NOT carriage_return EQUAL -1)
            message(FATAL_ERROR "library source must use LF: ${relative_path}")
        endif()
        file(SHA256 "${source_path}" actual_hash)
        string(TOUPPER "${actual_hash}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "library manifest mismatch: ${relative_path}")
        endif()
        list(APPEND manifest_paths "${relative_path}")
    endif()
endforeach()
if(NOT manifest_revision)
    message(FATAL_ERROR "library manifest has no corpus revision")
endif()

file(GLOB_RECURSE actual_paths RELATIVE "${library_root}" "${library_root}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${library_root}/${relative_path}" OR
       relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST manifest_paths)
        message(FATAL_ERROR "library manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS manifest_paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "library manifest stale path: ${relative_path}")
    endif()
endforeach()

message(STATUS "library manifest verified: ${library_root}")
