include_guard(GLOBAL)

# Registration only: each corpus still selects its own tests and dependencies.
function(shared_register_test corpus source)
    get_filename_component(name "${source}" NAME)
    set(target "${corpus}-test-${name}")
    if(corpus STREQUAL "lib")
        set(label library)
    else()
        set(label "${corpus}")
    endif()
    add_executable(${target} ${source}_smoke.c)
    target_link_libraries(${target} PRIVATE ${ARGN})
    if(MSVC)
        target_compile_options(${target} PRIVATE /UNDEBUG)
    else()
        target_compile_options(${target} PRIVATE -UNDEBUG)
    endif()
    add_test(NAME ${label}.${name} COMMAND ${target})
    set_tests_properties(${label}.${name} PROPERTIES LABELS "unit;${corpus}"
        TIMEOUT 30 WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    string(TOUPPER "${corpus}" upper)
    set(list_name "SHARED_${upper}_TEST_TARGETS")
    list(APPEND ${list_name} ${target})
    set(${list_name} "${${list_name}}" PARENT_SCOPE)
endfunction()
