include_guard(GLOBAL)

# Registration only: each corpus still selects its own tests and dependencies.
function(shared_register_test corpus source)
    get_filename_component(name "${source}" NAME)
    set(target "${corpus}-test-${name}")
    set(label "${corpus}")
    add_executable(${target} ${source}_smoke.c)
    target_link_libraries(${target} PRIVATE ${ARGN})
    if(MSVC)
        target_compile_options(${target} PRIVATE /UNDEBUG)
    else()
        target_compile_options(${target} PRIVATE -UNDEBUG)
    endif()
    set(work_directory "${CMAKE_CURRENT_BINARY_DIR}/test/${target}")
    file(MAKE_DIRECTORY "${work_directory}")
    add_test(NAME ${label}.${source} COMMAND ${target})
    set_tests_properties(${label}.${source} PROPERTIES LABELS "unit;${corpus}"
        TIMEOUT 30 WORKING_DIRECTORY "${work_directory}")
    string(TOUPPER "${corpus}" upper)
    set(list_name "SHARED_${upper}_TEST_TARGETS")
    list(APPEND ${list_name} ${target})
    set(${list_name} "${${list_name}}" PARENT_SCOPE)
endfunction()

# Explicit script/verifier registrations share the same public contract as
# smoke registrations.  Check it during configure so a missing owner label
# cannot silently weaken selection in either standalone or embedded builds.
function(shared_verify_test_registration corpus)
    get_property(registered_tests DIRECTORY PROPERTY TESTS)
    foreach(test_name IN LISTS registered_tests)
        if(NOT test_name MATCHES "^${corpus}[.]")
            message(FATAL_ERROR "Shared ${corpus} test has foreign identity: ${test_name}")
        endif()
        get_test_property(${test_name} LABELS labels)
        list(FIND labels unit unit_index)
        list(FIND labels "${corpus}" owner_index)
        if(unit_index EQUAL -1 OR owner_index EQUAL -1)
            message(FATAL_ERROR "Shared ${corpus} test lacks unit/owner labels: ${test_name}")
        endif()
    endforeach()
endfunction()
