if(NOT DEFINED TEST_WORK_DIR)
    message(FATAL_ERROR "TEST_WORK_DIR required")
endif()
set(probe "${TEST_WORK_DIR}/test-boundary-probe")
file(MAKE_DIRECTORY "${probe}")
function(check layer source build expected)
    file(WRITE "${probe}/probe.c" "${source}\n")
    file(WRITE "${probe}/CMakeLists.txt" "${build}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_ROOT=${probe}"
        "-DTEST_LAYER=${layer}" -P "${CMAKE_CURRENT_LIST_DIR}/verify_test_boundaries.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Valid boundary rejected: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Missing boundary rejection ${expected}: ${output}${error}")
    endif()
endfunction()
check(lib "#include \"lib/types/test.h\"" "" "")
check(common "#include \"lib/base/sync_interface.h\"" "" "")
check(x86 "#include \"common/machine/machine_interface.h\"" "" "")
check(ibmpc "#include \"x86/core/machine_interface.h\"" "" "")
check(ibmpc "#include \"ibmpc/board-common/machine_board_interface.h\"" "" "")
check(ibmpc "#include \"app-my5170/profiles/profile_interface.h\"" "" "Outward")
check(ibmpc "#include \"../x86/core/fixture.h\"" "" "Foreign")
check(lib "#include \"common/machine/machine_interface.h\"" "" "Outward")
check(common "#include \"x86/debug/debug_interface.h\"" "" "Outward")
check(x86 "#include \"ibmpc/board.h\"" "" "Outward")
check(x86 "#include \"../common/machine_fixture.h\"" "" "Foreign")
check(x86 "" "target_sources(probe PRIVATE ../ibmpc/fixture.c)" "Foreign")
check(x86 "" "target_sources(probe PRIVATE ../common/machine_fixture.c)" "Foreign")
check(x86 "" "target_link_libraries(probe PRIVATE ibmpc-board-common)" "Outward")
check(common "" "target_link_libraries(probe PRIVATE x86-core)" "Outward")
check(lib "" "target_link_libraries(probe PRIVATE common-machine)" "Outward")
file(REMOVE "${probe}/probe.c" "${probe}/CMakeLists.txt")
message(STATUS "Test boundary negative probes verified")
