if(NOT DEFINED TEST_WORK_DIR)
    message(FATAL_ERROR "TEST_WORK_DIR required")
endif()
set(probe "${TEST_WORK_DIR}/test-boundary-probe")
file(MAKE_DIRECTORY "${probe}")
function(check layer source build expected)
    file(WRITE "${probe}/probe.c" "${source}\n")
    file(WRITE "${probe}/CMakeLists.txt" "${build}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_ROOT=${probe}"
        "-DTEST_LAYER=${layer}" -P "${CMAKE_CURRENT_LIST_DIR}/verify_test_boundaries.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Valid boundary rejected: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Missing boundary rejection ${expected}: ${output}${error}")
    endif()
endfunction()
check(lib "#include \"lib/types/test.h\"" "" "")
check(emulator "#include \"lib/base/sync_interface.h\"" "" "")
check(x86 "#include \"emulator/machine/machine_interface.h\"" "" "")
check(core "#include \"core/x86/machine_interface.h\"" "" "")
check(core "#include \"core/board-base/machine_board_interface.h\"" "" "")
check(ibmpc "#include \"app-my5170/profiles/profile_interface.h\"" "" "Outward")
check(ibmpc "#include \"../core/x86/fixture.h\"" "" "Foreign")
check(lib "#include \"emulator/machine/machine_interface.h\"" "" "Outward")
check(emulator "#include \"product/debug/debug_interface.h\"" "" "Outward")
check(x86 "#include \"ibmpc/board.h\"" "" "Outward")
check(x86 "#include \"../emulator/machine_fixture.h\"" "" "Foreign")
check(x86 "" "target_sources(probe PRIVATE ../ibmpc/fixture.c)" "Foreign")
check(x86 "" "target_sources(probe PRIVATE ../emulator/machine_fixture.c)" "Foreign")
check(x86 "" "target_link_libraries(probe PRIVATE core-board-base)" "Outward")
check(emulator "" "target_link_libraries(probe PRIVATE core-x86)" "Outward")
check(lib "" "target_link_libraries(probe PRIVATE emulator-machine)" "Outward")
file(REMOVE "${probe}/probe.c" "${probe}/CMakeLists.txt")
message(STATUS "Test boundary negative probes verified")
