cmake_minimum_required(VERSION 3.23)

if(NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "TEST_ROOT is required")
endif()
file(REAL_PATH "${TEST_ROOT}" TEST_ROOT)
set(manifest "${TEST_ROOT}/MANIFEST.sha256")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "missing test manifest: ${manifest}")
endif()

file(STRINGS "${manifest}" lines)
list(GET lines 0 header)
if(NOT header STREQUAL "# sha256-manifest-v1")
    message(FATAL_ERROR "invalid test manifest header: ${header}")
endif()

set(paths)
set(previous "")
foreach(line IN LISTS lines)
    if(line STREQUAL "# sha256-manifest-v1")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid test manifest line: ${line}")
    endif()
    set(expected_hash "${CMAKE_MATCH_1}")
    set(relative_path "${CMAKE_MATCH_2}")
    string(LENGTH "${expected_hash}" hash_length)
    if(NOT hash_length EQUAL 64)
        message(FATAL_ERROR "invalid test manifest hash: ${relative_path}")
    endif()
    if(relative_path IN_LIST paths)
        message(FATAL_ERROR "duplicate test manifest path: ${relative_path}")
    endif()
    if(NOT previous STREQUAL "" AND relative_path STRLESS previous)
        message(FATAL_ERROR "test manifest paths are not ordered: ${relative_path}")
    endif()
    set(file_path "${TEST_ROOT}/${relative_path}")
    if(NOT EXISTS "${file_path}" OR IS_DIRECTORY "${file_path}")
        message(FATAL_ERROR "missing test source: ${relative_path}")
    endif()
    file(READ "${file_path}" content)
    string(FIND "${content}" "\r" carriage_return)
    if(NOT carriage_return EQUAL -1)
        message(FATAL_ERROR "test source must use LF: ${relative_path}")
    endif()
    file(SHA256 "${file_path}" actual_hash)
    string(TOUPPER "${actual_hash}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "test manifest mismatch: ${relative_path}")
    endif()
    list(APPEND paths "${relative_path}")
    set(previous "${relative_path}")
endforeach()

file(GLOB_RECURSE actual_paths RELATIVE "${TEST_ROOT}" "${TEST_ROOT}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${TEST_ROOT}/${relative_path}" OR relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST paths)
        message(FATAL_ERROR "test manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "test manifest stale path: ${relative_path}")
    endif()
endforeach()

message(STATUS "test manifest verified: ${TEST_ROOT}")
