if(NOT DEFINED TEST_ROOT OR NOT DEFINED TEST_LAYER)
    message(FATAL_ERROR "TEST_ROOT and TEST_LAYER are required")
endif()
set(layers lib common x86 ibmpc)
list(FIND layers "${TEST_LAYER}" level)
if(level LESS 0)
    message(FATAL_ERROR "Unknown test layer: ${TEST_LAYER}")
endif()
file(REAL_PATH "${TEST_ROOT}" root)
file(GLOB_RECURSE files "${root}/*.c" "${root}/*.h")
foreach(path IN LISTS files)
    if(path MATCHES "/fixtures/")
        continue() # Deliberately invalid static-check inputs, not executables.
    endif()
    get_filename_component(directory "${path}" DIRECTORY)
    file(STRINGS "${path}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*\"")
    foreach(line IN LISTS includes)
        string(REGEX REPLACE "^.*include[ \t]*\"([^\"]+)\".*$" "\\1" header "${line}")
        if(header MATCHES "^(app[^/]*|core|vm|compat)/")
            message(FATAL_ERROR "Outward test include: ${path}: ${header}")
        elseif(header MATCHES "^(lib|common|x86|ibmpc)/")
            list(FIND layers "${CMAKE_MATCH_1}" dependency)
            if(dependency GREATER level)
                message(FATAL_ERROR "Outward test include: ${path}: ${header}")
            endif()
        else()
            get_filename_component(resolved "${directory}/${header}" ABSOLUTE)
            cmake_path(IS_PREFIX root "${resolved}" NORMALIZE local)
            if(NOT local)
                message(FATAL_ERROR "Foreign test fixture: ${path}: ${header}")
            endif()
        endif()
    endforeach()
endforeach()
file(READ "${root}/CMakeLists.txt" build)
if(TEST_LAYER STREQUAL "lib")
    set(outer "common-|x86-|ibmpc-")
elseif(TEST_LAYER STREQUAL "common")
    set(outer "x86-|ibmpc-")
elseif(TEST_LAYER STREQUAL "x86")
    set(outer "ibmpc-")
else()
    set(outer "app-|softpc-")
endif()
if(build MATCHES "target_link_libraries[ \t\n]*\\([^)]*[ \t\n](${outer})")
    message(FATAL_ERROR "Outward test link: ${root}")
endif()
# Source-root discovery uses ../../src; sibling suite paths never do.
if(build MATCHES "(CURRENT_LIST_DIR|CURRENT_SOURCE_DIR)}/[.][.]/(lib|common|x86|ibmpc)(/|\")" OR
   build MATCHES "[ \t\n\"]([.][.]/)+(lib|common|x86|ibmpc)/")
    message(FATAL_ERROR "Foreign test package in build: ${root}")
endif()
message(STATUS "${TEST_LAYER} test ownership and inward includes verified")
