if(NOT DEFINED LIBRARY_ROOT OR NOT DEFINED TEST_WORK_DIR)
    message(FATAL_ERROR "LIBRARY_ROOT and TEST_WORK_DIR required")
endif()
cmake_policy(SET CMP0057 NEW)
set(fixture "${TEST_WORK_DIR}/types-layout-fixture")
file(MAKE_DIRECTORY "${fixture}")
file(REMOVE "${fixture}/CMakeLists.txt")
foreach(component types console host storage kvm-base kvm-window kvm-console)
    file(REMOVE "${fixture}/${component}/edge.h")
endforeach()
file(COPY "${LIBRARY_ROOT}/types" DESTINATION "${fixture}")
# A failed/aborted negative probe must not poison the next positive control.
# These are the only scratch files owned by this self-test.
file(REMOVE "${fixture}/consumer.c" "${fixture}/types/probe.h"
    "${fixture}/types/win32/probe.h" "${fixture}/kvm-base/probe_interface.h"
    "${fixture}/kvm-window/win32/probe.c"
    "${fixture}/kvm-base/win32/probe_interface.h"
    "${fixture}/host/win32/encoding_probe.c"
    "${fixture}/kvm-window/win32/encoding_probe.c"
    "${fixture}/kvm-window/input_probe.c"
    "${fixture}/kvm-console/input_probe.c")
set(probe "${fixture}/types/probe.h")
function(check_layout expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DLIBRARY_ROOT=${fixture}"
        -P "${LIBRARY_ROOT}/verify_types_layout.cmake"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "pass" AND NOT status EQUAL 0)
        message(FATAL_ERROR "Valid layout rejected: ${output}${error}")
    elseif(expected STREQUAL "fail" AND status EQUAL 0)
        message(FATAL_ERROR "Invalid layout accepted")
    endif()
endfunction()
file(WRITE "${probe}" "#include <stdint.h>\n")
check_layout(pass)

# Exact component DAG: exhaust all 49 possible direct edges, not only a few
# forbidden filename patterns. Each fixture is removed before the next check.
set(components types console host storage kvm-base kvm-window kvm-console)
set(allowed_types "")
set(allowed_console types)
set(allowed_host types console)
set(allowed_storage types)
set(allowed_kvm-base types)
set(allowed_kvm-window types kvm-base)
set(allowed_kvm-console types console kvm-base)
foreach(owner IN LISTS components)
    file(MAKE_DIRECTORY "${fixture}/${owner}")
    foreach(dependency IN LISTS components)
        set(expected fail)
        if(owner STREQUAL dependency OR dependency IN_LIST allowed_${owner})
            set(expected pass)
        endif()
        file(WRITE "${fixture}/${owner}/edge.h"
            "#include \"lib/${dependency}/probe_interface.h\"\n")
        check_layout(${expected})
        file(REMOVE "${fixture}/${owner}/edge.h")
        file(WRITE "${fixture}/CMakeLists.txt"
            "target_link_libraries(${owner} INTERFACE ${dependency})\n")
        check_layout(${expected})
        file(REMOVE "${fixture}/CMakeLists.txt")
    endforeach()
endforeach()
file(WRITE "${fixture}/CMakeLists.txt"
    "TARGET_LINK_LIBRARIES(host PRIVATE kvm-window)\n")
check_layout(fail)
file(REMOVE "${fixture}/CMakeLists.txt")
file(WRITE "${probe}" "#ifdef _WIN32\n#endif\n")
check_layout(fail)
file(WRITE "${probe}" "#if defined(__linux__)\n#endif\n")
check_layout(fail)
file(WRITE "${probe}" "#include <windows.h>\n")
check_layout(fail)
file(WRITE "${probe}" "#include \"lib/types/win32/file.h\"\n")
check_layout(fail)
file(WRITE "${probe}" "#include <stdint.h>\n")
file(WRITE "${fixture}/types/win32/probe.h" "static inline int f(int x) { if (x) return 1; return 0; }\n")
check_layout(fail)
file(REMOVE "${fixture}/types/win32/probe.h")
file(WRITE "${fixture}/consumer.c" "#include \"lib/types/linux/file.h\"\n")
check_layout(fail)
file(WRITE "${fixture}/consumer.c" "#include <stdio.h>\n")
check_layout(fail)
foreach(token IN ITEMS HANDLE CreateEventA FILE fread pthread_mutex_t pthread_create VK_CONTROL KVM_WIN32_KEY_CONTROL UINT64_MAX UINT_FAST16_MAX int_fast16_t pthread_condattr_t VK_UNKNOWN_UNWRAPPED)
    file(WRITE "${fixture}/consumer.c" "void probe(void) { ${token}; }\n")
    check_layout(fail)
endforeach()
foreach(call IN ITEMS realloc memmove GetUnwrappedOperation pthread_cond_timedwait)
    file(WRITE "${fixture}/consumer.c" "void probe(void) { ${call}(0); }\n")
    check_layout(fail)
endforeach()
file(WRITE "${fixture}/consumer.c" "#include \"lib/console/console.h\"\n")
check_layout(fail)
file(WRITE "${fixture}/consumer.c" "void probe(void) { lib_win32_handle h; }\n")
check_layout(pass)
file(REMOVE "${fixture}/consumer.c" "${probe}")
check_layout(pass)

# Root support contracts are public to allowed leaves. A public-looking suffix
# cannot make another component's platform implementation accessible.
set(platform_probe "${fixture}/kvm-window/win32/probe.c")
file(MAKE_DIRECTORY "${fixture}/kvm-window/win32" "${fixture}/kvm-base")
foreach(header IN ITEMS kvm-base/input_interface.h kvm-window/win32/mouse.h types/win32/input.h)
    file(WRITE "${platform_probe}" "#include \"lib/${header}\"\n")
    check_layout(pass)
endforeach()
foreach(header IN ITEMS kvm-base/win32/input_interface.h kvm-base/linux/input.h kvm-window/linux/input.h types/linux/sync.h kvm-base/../kvm-base/win32/input.h)
    file(WRITE "${platform_probe}" "#include \"lib/${header}\"\n")
    check_layout(fail)
endforeach()
file(REMOVE "${platform_probe}")
# A root forwarding header must not smuggle the private platform header out.
file(WRITE "${fixture}/kvm-base/probe_interface.h"
    "#include \"lib/kvm-base/win32/input.h\"\n")
check_layout(fail)
file(REMOVE "${fixture}/kvm-base/probe_interface.h")
file(MAKE_DIRECTORY "${fixture}/kvm-base/win32")
file(WRITE "${fixture}/kvm-base/win32/probe_interface.h" "/* forbidden public location */\n")
check_layout(fail)
file(REMOVE "${fixture}/kvm-base/win32/probe_interface.h")
file(WRITE "${platform_probe}" "#include \"../../kvm-base/win32/input.h\"\n")
check_layout(fail)
file(REMOVE "${platform_probe}")
check_layout(pass)
file(WRITE "${fixture}/types/win32/probe.h" "#include <lib/host/console_interface.h>\n")
check_layout(fail)
file(WRITE "${fixture}/types/win32/probe.h" "#include SELECTED_HEADER\n")
check_layout(fail)
file(REMOVE "${fixture}/types/win32/probe.h")
check_layout(pass)

# Native character producers must not silently narrow Unicode records.
foreach(component IN ITEMS host kvm-window)
    set(encoding_probe "${fixture}/${component}/win32/encoding_probe.c")
    file(MAKE_DIRECTORY "${fixture}/${component}/win32")
    foreach(call IN ITEMS read_console_input_a register_class_a create_window_ex_a dispatch_message_a peek_message_a)
        file(WRITE "${encoding_probe}" "void probe(void) { lib_win32_${call}\n\t(0); }\n")
        check_layout(fail)
    endforeach()
    file(WRITE "${encoding_probe}" "void probe(void) { lib_win32_read_console_input_w(0); }\n")
    check_layout(pass)
    file(REMOVE "${encoding_probe}")
endforeach()

# Both leaves must use the same record-level decision, not a low-level bypass.
file(WRITE "${fixture}/kvm-base/probe_interface.h" "int kvm_keyboard_submit_utf16(void);\n")
check_layout(fail)
file(REMOVE "${fixture}/kvm-base/probe_interface.h")
check_layout(pass)
foreach(leaf IN ITEMS kvm-window kvm-console)
    set(input_probe "${fixture}/${leaf}/input_probe.c")
    foreach(call IN ITEMS kvm_keyboard_submit_transition kvm_keyboard_submit_utf16
            kvm_keyboard_platform_transition kvm_keyboard_note_recovered_key)
        file(WRITE "${input_probe}" "void probe(void) { ${call}(0); }\n")
        check_layout(fail)
        file(WRITE "${input_probe}" "void probe(void) { ${call}\n\t(0); }\n")
        check_layout(fail)
    endforeach()
    file(WRITE "${input_probe}" "void probe(void) { kvm_keyboard_submit_record(0); }\n")
    check_layout(pass)
    file(REMOVE "${input_probe}")
endforeach()
