cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED CORE_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit Core and probe roots required")
endif()
file(REMOVE_RECURSE "${PROBE_ROOT}")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/pit825x" "${PROBE_ROOT}/product")
function(reject owner source expected)
    file(WRITE "${PROBE_ROOT}/${owner}/probe.c" "${source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DCORE_ROOT=${PROBE_ROOT}
        -P "${CORE_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(REMOVE "${PROBE_ROOT}/${owner}/probe.c")
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject(chips/pit825x "#include \"core/machine/machine_interface.h\"\n" "Lower Core component")
reject(x86 "#include \"outer/product/main.c\"\n" "Core may not depend")
file(REMOVE_RECURSE "${PROBE_ROOT}")
