if(NOT DEFINED TEST_DIRECTORY OR NOT EXISTS "${TEST_DIRECTORY}")
    message(FATAL_ERROR "CTest directory is required.")
endif()

set_property(GLOBAL PROPERTY test_route_ctest_files "")

function(test_route_collect_ctest_file ctest_file)
    if(NOT EXISTS "${ctest_file}")
        return()
    endif()

    get_property(ctest_files GLOBAL PROPERTY test_route_ctest_files)
    list(FIND ctest_files "${ctest_file}" known_index)
    if(NOT known_index EQUAL -1)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY test_route_ctest_files "${ctest_file}")

    get_filename_component(ctest_directory "${ctest_file}" DIRECTORY)
    file(STRINGS "${ctest_file}" ctest_lines)
    foreach(line IN LISTS ctest_lines)
        if(NOT line MATCHES "^subdirs\\((.*)\\)$")
            continue()
        endif()
        string(REGEX MATCHALL "\"[^\"]+\"" subdirectory_tokens "${CMAKE_MATCH_1}")
        foreach(token IN LISTS subdirectory_tokens)
            string(REGEX REPLACE "^\"(.*)\"$" "\\1" subdirectory "${token}")
            test_route_collect_ctest_file(
                "${ctest_directory}/${subdirectory}/CTestTestfile.cmake")
        endforeach()
    endforeach()
endfunction()

test_route_collect_ctest_file("${TEST_DIRECTORY}/CTestTestfile.cmake")
get_property(ctest_files GLOBAL PROPERTY test_route_ctest_files)
set(declared_tests)
set(test_properties)
foreach(ctest_file IN LISTS ctest_files)
    if(NOT EXISTS "${ctest_file}")
        continue()
    endif()
    file(STRINGS "${ctest_file}" ctest_lines)
    foreach(line IN LISTS ctest_lines)
        if(line MATCHES "^add_test\\(\\[=\\[([^]]+)\\]=\\]")
            list(APPEND declared_tests "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^set_tests_properties\\(\\[=\\[([^]]+)\\]=\\] PROPERTIES.* LABELS \"([^\"]*)\"")
            string(REPLACE ";" "|" property_labels "${CMAKE_MATCH_2}")
            list(APPEND test_properties "${CMAKE_MATCH_1}@@${property_labels}")
        endif()
    endforeach()
endforeach()

set(checked 0)
set(route_names unit integration diagnostic)
set(owner_names lib emulator product core x86)
foreach(test_name IN LISTS declared_tests)
    if(NOT test_name MATCHES "^(lib|library|emulator|product|core|x86\\.)")
        continue()
    endif()
    set(route_count 0)
    set(owner_count 0)
    set(property_found FALSE)
    foreach(test_property IN LISTS test_properties)
        string(REPLACE "@@" ";" property_parts "${test_property}")
        list(GET property_parts 0 property_test_name)
        if(NOT property_test_name STREQUAL test_name)
            continue()
        endif()
        set(property_found TRUE)
        list(GET property_parts 1 property_labels)
        string(REPLACE "|" ";" labels "${property_labels}")
        foreach(label IN LISTS labels)
            if(label IN_LIST route_names)
                math(EXPR route_count "${route_count} + 1")
            endif()
            if(label IN_LIST owner_names)
                math(EXPR owner_count "${owner_count} + 1")
            endif()
        endforeach()
    endforeach()
    if(NOT property_found OR NOT route_count EQUAL 1 OR NOT owner_count EQUAL 1)
        message(FATAL_ERROR
            "CTest ${test_name} must have one route and one owner label; routes=${route_count}; owners=${owner_count}")
    endif()
    math(EXPR checked "${checked} + 1")
endforeach()

if(checked EQUAL 0)
    message(FATAL_ERROR "No Shared/Core CTest registrations were found.")
endif()
message(STATUS "TEST-ROUTE-PARTITION:OK:count=${checked}")
