cmake_minimum_required(VERSION 3.23)
file(STRINGS "${X86_ROOT}/chips/cpu/cpu_instructions.c" cpu_lines)
set(owner "")
set(enter_stack_switches 0)
foreach(line IN LISTS cpu_lines)
    if(line MATCHES "^static [a-zA-Z0-9_]+ ([a-zA-Z0-9_]+)\\(")
        set(owner "${CMAKE_MATCH_1}")
    endif()
    if(line MATCHES "_e_pop\\(")
        message(FATAL_ERROR "Stack boundary: retired pop forwarding owner")
    endif()
    if(owner STREQUAL "_s_test_ss_frame" AND
       (line MATCHES "_m_test_access|_kma_test_access" OR
        line MATCHES "cpu_state\\.data\\.[a-zA-Z0-9_.]+[ \t]*[-+]?=[^=]"))
        message(FATAL_ERROR "Stack boundary: ordinary admission translates or publishes")
    endif()
    if(owner MATCHES "^(PUSHA|POPA|ENTER)$")
        if(line MATCHES "_s_test_ss_frame\\(")
            set(admitted_${owner} TRUE)
        elseif(line MATCHES "(_e_push|_kec_pop)\\(" AND NOT admitted_${owner})
            message(FATAL_ERROR "Stack boundary: ${owner} transfer before frame admission")
        endif()
    endif()
    if(owner STREQUAL "ENTER" AND line MATCHES "switch \\(_GetStackSize\\)")
        math(EXPR enter_stack_switches "${enter_stack_switches} + 1")
    endif()
endforeach()
foreach(handler IN ITEMS PUSHA POPA ENTER)
    if(NOT admitted_${handler})
        message(FATAL_ERROR "Stack boundary: missing ${handler} admission")
    endif()
endforeach()
if(NOT enter_stack_switches EQUAL 1)
    message(FATAL_ERROR "Stack boundary: ENTER chain uses stack width")
endif()
message(STATUS "CPU stack frame owner boundary: OK")
