#ifndef NXVM_TEST_SELECTION_H
#define NXVM_TEST_SELECTION_H

typedef enum vm_machine_profile_kind {
    VM_MACHINE_PROFILE_DEFAULT_PC_AT,
    VM_MACHINE_PROFILE_IBM_5170_MODEL_339,
    VM_MACHINE_PROFILE_IBM_5160_MODEL_268,
    VM_MACHINE_PROFILE_COMPAQ_DESKPRO_386_MODEL_40
} vm_machine_profile_kind;
#endif
