#ifndef KVM_LINKVM_INPUT_H
#define KVM_LINKVM_INPUT_H

#include "lib/kvm-base/event_interface.h"

typedef enum kvm_linkvm_key {
    KVM_LINKVM_KEY_ENTER,
    KVM_LINKVM_KEY_BACKSPACE,
    KVM_LINKVM_KEY_F1,
    KVM_LINKVM_KEY_F2,
    KVM_LINKVM_KEY_F3,
    KVM_LINKVM_KEY_F4,
    KVM_LINKVM_KEY_F5,
    KVM_LINKVM_KEY_F6,
    KVM_LINKVM_KEY_F7,
    KVM_LINKVM_KEY_F8,
    KVM_LINKVM_KEY_F9,
    KVM_LINKVM_KEY_F10,
    KVM_LINKVM_KEY_F11,
    KVM_LINKVM_KEY_F12,
    KVM_LINKVM_KEY_UP,
    KVM_LINKVM_KEY_DOWN,
    KVM_LINKVM_KEY_LEFT,
    KVM_LINKVM_KEY_RIGHT,
    KVM_LINKVM_KEY_HOME,
    KVM_LINKVM_KEY_END,
    KVM_LINKVM_KEY_PAGE_UP,
    KVM_LINKVM_KEY_PAGE_DOWN,
    KVM_LINKVM_KEY_INSERT,
    KVM_LINKVM_KEY_DELETE
} kvm_linkvm_key;


#endif
