if(NOT DEFINED UX_LIBRARY_ROOT)
    message(FATAL_ERROR "UX_LIBRARY_ROOT is required")
endif()

file(STRINGS "${UX_LIBRARY_ROOT}/MANIFEST.sha256" ux_manifest)
foreach(ux_manifest_line IN LISTS ux_manifest)
    if(ux_manifest_line MATCHES "^#" OR ux_manifest_line STREQUAL "")
        continue()
    endif()
    if(NOT ux_manifest_line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid UX manifest line: ${ux_manifest_line}")
    endif()
    set(ux_expected "${CMAKE_MATCH_1}")
    set(ux_relative_path "${CMAKE_MATCH_2}")
    string(LENGTH "${ux_expected}" ux_expected_length)
    if(NOT ux_expected_length EQUAL 64)
        message(FATAL_ERROR "invalid UX hash length: ${ux_relative_path}")
    endif()
    set(ux_source "${UX_LIBRARY_ROOT}/${ux_relative_path}")
    if(NOT EXISTS "${ux_source}")
        message(FATAL_ERROR "missing UX source: ${ux_relative_path}")
    endif()
    file(READ "${ux_source}" ux_contents)
    string(REPLACE "\r\n" "\n" ux_contents "${ux_contents}")
    string(SHA256 ux_actual "${ux_contents}")
    string(TOUPPER "${ux_actual}" ux_actual)
    if(NOT ux_actual STREQUAL ux_expected)
        message(FATAL_ERROR "UX manifest mismatch: ${ux_relative_path}")
    endif()
endforeach()
