cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT)
    set(X86_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components debug xasm32 product)
set(edges_debug emulator/machine x86/xasm32 lib/storage lib/types)
set(edges_xasm32 lib/types)
set(edges_product emulator/machine emulator/session emulator/ui emulator/product x86/debug lib/kvm-base lib/types)

function(check_edge owner dependency)
    if(NOT dependency STREQUAL "x86/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden x86 edge: ${owner} -> ${dependency}")
    endif()
endfunction()

function(component_for_target target out_component)
    if(target STREQUAL "types" OR target STREQUAL "base" OR target STREQUAL "console" OR
       target STREQUAL "console-broker" OR target STREQUAL "storage" OR
       target STREQUAL "kvm-base" OR target STREQUAL "kvm-window" OR target STREQUAL "kvm-console")
        set(${out_component} "lib/${target}" PARENT_SCOPE)
    elseif(target MATCHES "^emulator-(machine|session|ui|product)$")
        string(REGEX REPLACE "^emulator-" "emulator/" component "${target}")
        set(${out_component} "${component}" PARENT_SCOPE)
    elseif(target STREQUAL "x86-xasm32")
        set(${out_component} "x86/xasm32" PARENT_SCOPE)
    elseif(target STREQUAL "x86-debug")
        set(${out_component} "x86/debug" PARENT_SCOPE)
    elseif(target MATCHES "^x86-product(-.*)?$")
        set(${out_component} "x86/product" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unknown x86 link target: ${target}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${X86_ROOT}" "${X86_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "x86 must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "^(debug|xasm32|product)/[^/]+\\.[ch]$")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    file(READ "${X86_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in x86; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(U?INT[A-Z0-9_]*|SIZE|PTRDIFF|WCHAR|WINT)_(MAX|MIN)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw integer limit in x86; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|WaitForSingleObject|CreateEvent[A-W]?|pthread_")
        message(FATAL_ERROR "Platform implementation in x86: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(x86|emulator|lib)/[^/]+/[^/]+\\.h$")
            message(FATAL_ERROR "Noncanonical x86 include: ${header}")
        endif()
        string(REGEX MATCH "^([^/]+)/([^/]+)/([^/]+\\.h)$" _ "${header}")
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_3}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "x86/${owner}")
            if(NOT EXISTS "${X86_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local x86 header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in x86: ${header}")
        endif()
    endforeach()
endforeach()

file(READ "${X86_ROOT}/CMakeLists.txt" build_source)
string(REGEX REPLACE "#[^\n]*" "" build_source "${build_source}")
string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${build_source}")
foreach(link IN LISTS links)
    string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
    string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
    list(POP_FRONT args target)
    component_for_target("${target}" owner_component)
    string(REGEX REPLACE "^x86/" "" owner "${owner_component}")
    foreach(dependency_target IN LISTS args)
        if(dependency_target MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$" OR dependency_target STREQUAL "")
            continue()
        endif()
        component_for_target("${dependency_target}" dependency)
        check_edge("${owner}" "${dependency}")
    endforeach()
endforeach()
message(STATUS "x86 platform and component boundaries verified")
