cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT)
    set(X86_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components debug xasm32)
set(edges_debug common/machine x86/xasm32 lib/storage lib/types)
set(edges_xasm32 lib/types)

function(check_edge owner dependency)
    if(NOT dependency STREQUAL "x86/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden x86 edge: ${owner} -> ${dependency}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${X86_ROOT}" "${X86_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "x86 must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "^([^/]+)/.*\\.[ch]$")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    if(NOT owner IN_LIST components)
        message(FATAL_ERROR "Unknown x86 component: ${path}")
    endif()
    file(READ "${X86_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in x86; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|Interlocked[A-Za-z]+|WaitForSingleObject|CreateEvent[A-W]?|SetEvent|ResetEvent|CloseHandle|pthread_" OR
       tokens MATCHES "(^|[^A-Za-z0-9_])(HANDLE|DWORD|LONG|HWND)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Platform implementation in x86: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(x86|common|lib)/([^/]+)/([A-Za-z0-9_-]+\\.h)$")
            message(FATAL_ERROR "Noncanonical x86 include: ${header}")
        endif()
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_3}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "x86/${owner}")
            if(NOT EXISTS "${X86_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local x86 header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in x86: ${header}")
        endif()
    endforeach()
endforeach()

file(GLOB_RECURSE builds "${X86_ROOT}/CMakeLists.txt")
foreach(build IN LISTS builds)
    file(READ "${build}" source)
    string(REGEX REPLACE "#[^\n]*" "" source "${source}")
    if(source MATCHES "(WIN32|LINUX|UNIX|APPLE|CMAKE_SYSTEM_NAME)")
        message(FATAL_ERROR "x86 build must not select platform implementations")
    endif()
    string(TOLOWER "${source}" source)
    if(source MATCHES "(^|[^_A-Za-z])link_libraries[ \t\r\n]*\\(" OR
       source MATCHES "(interface_)?link_libraries[ \t]")
        message(FATAL_ERROR "Use explicit x86 target_link_libraries")
    endif()
    string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${source}")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
        list(POP_FRONT args target)
        string(REGEX REPLACE "^x86-" "" owner "${target}")
        if(NOT owner IN_LIST components)
            message(FATAL_ERROR "Unknown x86 link owner: ${target}")
        endif()
        foreach(dependency IN LISTS args)
            if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
                continue()
            endif()
            if(dependency MATCHES "^(common|x86)-(.+)$")
                set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
            else()
                set(dependency "lib/${dependency}")
            endif()
            check_edge("${owner}" "${dependency}")
        endforeach()
    endforeach()
endforeach()
message(STATUS "x86 platform and component boundaries verified")
