cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT)
    set(X86_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components core debug xasm32 chips/cpu chips/pit825x chips/rtc146818 chips/pic8259 chips/dma8237 chips/fdc8272 chips/hdc chips/video chips/fpu chips/ps2mouse chips/keyboard chips/kbc8042 chips/ppi8255 chips/xtkeyboard)
list(APPEND components ibmpc-common)
list(APPEND components ibmpc-at)
list(APPEND components ibmpc-xt)
list(APPEND components product)
set(edges_product lib/types lib/storage lib/base common/session common/ui common/machine lib/kvm-base x86/debug x86/product-config)
set(edges_ibmpc-xt lib/types x86/core x86/chips/ppi8255)
set(edges_ibmpc-at lib/types x86/core x86/chips/kbc8042 x86/chips/keyboard x86/chips/ps2mouse x86/chips/pit825x)
set(edges_ibmpc-common lib/types x86/chips/video x86/core x86/chips/pit825x x86/chips/pic8259 x86/chips/dma8237 x86/chips/fdc8272 x86/chips/hdc x86/chips/rtc146818 x86/chips/xtkeyboard x86/ibmpc-at x86/ibmpc-xt)
set(edges_core lib/types x86/chips/cpu x86/chips/fpu)
set(edges_debug common/machine x86/xasm32 lib/storage lib/types)
set(edges_xasm32 lib/types)
set(edges_chips/cpu lib/types x86/chips/fpu)
set(edges_chips/pit825x lib/types)
set(edges_chips/rtc146818 lib/types)
set(edges_chips/pic8259 lib/types)
set(edges_chips/dma8237 lib/types)
set(edges_chips/fdc8272 lib/types)
set(edges_chips/hdc lib/types)
set(edges_chips/video lib/types)
set(edges_chips/fpu lib/types)
set(edges_chips/ps2mouse lib/types)
set(edges_chips/keyboard lib/types)
set(edges_chips/kbc8042 lib/types x86/chips/keyboard)
set(edges_chips/ppi8255 lib/types)
set(edges_chips/xtkeyboard lib/types)

function(check_edge owner dependency)
    if(NOT dependency STREQUAL "x86/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden x86 edge: ${owner} -> ${dependency}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${X86_ROOT}" "${X86_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "x86 must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "\\.[ch]$")
        continue()
    endif()
    if(NOT path MATCHES "^((chips/[^/]+)|[^/]+)/[^/]+\\.[ch]$")
        message(FATAL_ERROR "Noncanonical x86 source path: ${path}")
    endif()
    set(owner "${CMAKE_MATCH_1}")
    if(NOT owner IN_LIST components)
        message(FATAL_ERROR "Unknown x86 component: ${path}")
    endif()
    file(READ "${X86_ROOT}/${path}" source)
    if(owner STREQUAL "chips/kbc8042")
        string(REGEX MATCHALL "x86_keyboard_[A-Za-z0-9_]+" keyboard_symbols "${source}")
        foreach(symbol IN LISTS keyboard_symbols)
            if(NOT symbol STREQUAL "x86_keyboard_set2_to_set1")
                message(FATAL_ERROR "Controller may use only the stateless scan codec: ${symbol}")
            endif()
        endforeach()
    endif()
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in x86; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|Interlocked[A-Za-z]+|WaitForSingleObject|CreateEvent[A-W]?|SetEvent|ResetEvent|CloseHandle|pthread_" OR
       tokens MATCHES "(^|[^A-Za-z0-9_])(HANDLE|DWORD|LONG|HWND)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Platform implementation in x86: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(x86|common|lib)/((chips/[^/]+)|[^/]+)/([A-Za-z0-9_-]+\\.h)$")
            message(FATAL_ERROR "Noncanonical x86 include: ${header}")
        endif()
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_4}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "x86/${owner}")
            if(NOT EXISTS "${X86_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local x86 header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in x86: ${header}")
        endif()
    endforeach()
endforeach()

file(GLOB_RECURSE builds "${X86_ROOT}/CMakeLists.txt")
foreach(build IN LISTS builds)
    file(READ "${build}" source)
    string(REGEX REPLACE "#[^\n]*" "" source "${source}")
    if(source MATCHES "(WIN32|LINUX|UNIX|APPLE|CMAKE_SYSTEM_NAME)")
        message(FATAL_ERROR "x86 build must not select platform implementations")
    endif()
    string(TOLOWER "${source}" source)
    if(source MATCHES "(^|[^_A-Za-z])link_libraries[ \t\r\n]*\\(" OR
       source MATCHES "(interface_)?link_libraries[ \t]")
        message(FATAL_ERROR "Use explicit x86 target_link_libraries")
    endif()
    string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${source}")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
        list(POP_FRONT args target)
        string(REGEX REPLACE "^x86-" "" owner "${target}")
        if(owner STREQUAL "core-observable")
            set(owner "core")
        endif()
        if(owner STREQUAL "product-config")
            set(owner "product")
        endif()
        if(owner STREQUAL "ibmpc-common-observable")
            set(owner "ibmpc-common")
        endif()
        if(owner STREQUAL "cpu-shared")
            set(owner "chips/cpu")
        endif()
        if(owner STREQUAL "pit825x" OR owner STREQUAL "rtc146818" OR owner STREQUAL "pic8259" OR owner STREQUAL "dma8237" OR owner STREQUAL "fdc8272" OR owner STREQUAL "hdc" OR owner STREQUAL "video" OR owner STREQUAL "fpu" OR owner STREQUAL "ps2mouse" OR owner STREQUAL "keyboard" OR owner STREQUAL "kbc8042" OR owner STREQUAL "ppi8255" OR owner STREQUAL "xtkeyboard")
            set(owner "chips/${owner}")
        endif()
        if(NOT owner IN_LIST components)
            message(FATAL_ERROR "Unknown x86 link owner: ${target}")
        endif()
        foreach(dependency IN LISTS args)
            if(owner STREQUAL "ibmpc-common" AND dependency MATCHES "^x86-core(-observable)?$")
                message(FATAL_ERROR "Board adapter must not select Core implementation: ${dependency}")
            endif()
            if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
                continue()
            endif()
            if(dependency MATCHES "^(common|x86)-(.+)$")
                set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
                if(dependency STREQUAL "x86/cpu-shared")
                    set(dependency "x86/chips/cpu")
                elseif(dependency STREQUAL "x86/keyboard")
                    set(dependency "x86/chips/keyboard")
                elseif(dependency STREQUAL "x86/fpu")
                    set(dependency "x86/chips/fpu")
                elseif(dependency STREQUAL "x86/pit825x")
                    set(dependency "x86/chips/pit825x")
                elseif(dependency STREQUAL "x86/pic8259")
                    set(dependency "x86/chips/pic8259")
                elseif(dependency STREQUAL "x86/dma8237")
                    set(dependency "x86/chips/dma8237")
                elseif(dependency STREQUAL "x86/fdc8272")
                    set(dependency "x86/chips/fdc8272")
                elseif(dependency STREQUAL "x86/hdc")
                    set(dependency "x86/chips/hdc")
                elseif(dependency STREQUAL "x86/kbc8042")
                    set(dependency "x86/chips/kbc8042")
                elseif(dependency STREQUAL "x86/ps2mouse")
                    set(dependency "x86/chips/ps2mouse")
                elseif(dependency STREQUAL "x86/ppi8255")
                    set(dependency "x86/chips/ppi8255")
                elseif(dependency STREQUAL "x86/video")
                    set(dependency "x86/chips/video")
                elseif(dependency STREQUAL "x86/rtc146818")
                    set(dependency "x86/chips/rtc146818")
                elseif(dependency STREQUAL "x86/xtkeyboard")
                    set(dependency "x86/chips/xtkeyboard")
                endif()
            else()
                set(dependency "lib/${dependency}")
            endif()
            check_edge("${owner}" "${dependency}")
        endforeach()
    endforeach()
endforeach()
message(STATUS "x86 platform and component boundaries verified")
