cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT)
    set(X86_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
file(REAL_PATH "${X86_ROOT}" X86_ROOT)
set(x86_manifest "${X86_ROOT}/MANIFEST.sha256")
if(NOT EXISTS "${x86_manifest}")
    message(FATAL_ERROR "missing x86 manifest: ${x86_manifest}")
endif()
file(STRINGS "${x86_manifest}" manifest_lines)
list(GET manifest_lines 0 manifest_header)
if(NOT manifest_header STREQUAL "# sha256-manifest-v1")
    message(FATAL_ERROR "invalid x86 manifest header: ${manifest_header}")
endif()
set(manifest_paths)
set(previous_path "")
foreach(line IN LISTS manifest_lines)
    if(line STREQUAL "# sha256-manifest-v1")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid x86 manifest line: ${line}")
    else()
        set(expected_hash "${CMAKE_MATCH_1}")
        set(relative_path "${CMAKE_MATCH_2}")
        string(LENGTH "${expected_hash}" hash_length)
        if(NOT hash_length EQUAL 64)
            message(FATAL_ERROR "invalid x86 manifest hash: ${relative_path}")
        endif()
        if(relative_path IN_LIST manifest_paths)
            message(FATAL_ERROR "duplicate x86 manifest path: ${relative_path}")
        endif()
        if(NOT previous_path STREQUAL "" AND relative_path STRLESS previous_path)
            message(FATAL_ERROR "x86 manifest paths are not ordered: ${relative_path}")
        endif()
        set(source_path "${X86_ROOT}/${relative_path}")
        if(NOT EXISTS "${source_path}" OR IS_DIRECTORY "${source_path}")
            message(FATAL_ERROR "missing x86 source: ${relative_path}")
        endif()
        file(READ "${source_path}" contents)
        string(FIND "${contents}" "\r" carriage_return)
        if(NOT carriage_return EQUAL -1)
            message(FATAL_ERROR "x86 source must use LF: ${relative_path}")
        endif()
        file(SHA256 "${source_path}" actual_hash)
        string(TOUPPER "${actual_hash}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "x86 manifest mismatch: ${relative_path}")
        endif()
        list(APPEND manifest_paths "${relative_path}")
        set(previous_path "${relative_path}")
    endif()
endforeach()
file(GLOB_RECURSE actual_paths RELATIVE "${X86_ROOT}" "${X86_ROOT}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${X86_ROOT}/${relative_path}" OR relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST manifest_paths)
        message(FATAL_ERROR "x86 manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS manifest_paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "x86 manifest stale path: ${relative_path}")
    endif()
endforeach()
message(STATUS "x86 manifest verified: ${X86_ROOT}")
