cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED IBMPC_ROOT)
    set(IBMPC_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components board-common board-at board-xt machine product)
set(edges_board-common lib/types x86/core x86/chips/video x86/chips/pit825x x86/chips/pic8259 x86/chips/dma8237 x86/chips/fdc8272 x86/chips/hdc x86/chips/rtc146818 x86/chips/xtkeyboard ibmpc/board-at ibmpc/board-xt)
set(edges_board-at lib/types x86/core x86/chips/kbc8042 x86/chips/keyboard x86/chips/ps2mouse x86/chips/pit825x)
set(edges_board-xt lib/types x86/core x86/chips/ppi8255)
set(edges_machine lib/types lib/base lib/storage common/machine ibmpc/board-common x86/core x86/debug x86/chips/video)
set(edges_product lib/types lib/base lib/storage lib/kvm-base common/session common/ui common/machine ibmpc/machine x86/debug)
function(check_edge owner dependency)
    if(NOT dependency STREQUAL "ibmpc/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden ibmpc edge: ${owner} -> ${dependency}")
    endif()
endfunction()
file(GLOB_RECURSE paths RELATIVE "${IBMPC_ROOT}" "${IBMPC_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "ibmpc must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "\\.[ch]$")
        continue()
    endif()
    if(NOT path MATCHES "^([^/]+)/((media/)?[A-Za-z0-9_-]+\\.[ch])$")
        message(FATAL_ERROR "Noncanonical ibmpc source path: ${path}")
    endif()
    set(owner "${CMAKE_MATCH_1}")
    if(NOT owner IN_LIST components)
        message(FATAL_ERROR "Unknown ibmpc component: ${path}")
    endif()
    file(READ "${IBMPC_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in ibmpc; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|Interlocked[A-Za-z]+|WaitForSingleObject|CreateEvent[A-W]?|SetEvent|ResetEvent|CloseHandle|pthread_" OR
       tokens MATCHES "(^|[^A-Za-z0-9_])(HANDLE|DWORD|LONG|HWND)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Platform implementation in ibmpc: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(ibmpc|x86|common|lib)/((chips/[^/]+)|[^/]+)/((media/)?[A-Za-z0-9_-]+\\.h)$")
            message(FATAL_ERROR "Noncanonical ibmpc include: ${header}")
        endif()
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_4}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "ibmpc/${owner}")
            if(NOT EXISTS "${IBMPC_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local ibmpc header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in ibmpc: ${header}")
        endif()
    endforeach()
endforeach()
file(READ "${IBMPC_ROOT}/CMakeLists.txt" build)
string(REGEX REPLACE "#[^\n]*" "" build "${build}")
if(build MATCHES "(WIN32|LINUX|UNIX|APPLE|CMAKE_SYSTEM_NAME)")
    message(FATAL_ERROR "ibmpc build must not select platform implementations")
endif()
string(TOLOWER "${build}" build)
string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${build}")
foreach(link IN LISTS links)
    string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
    string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
    list(POP_FRONT args target)
    string(REGEX REPLACE "^ibmpc-" "" owner "${target}")
    string(REGEX REPLACE "^board-common-observable$" "board-common" owner "${owner}")
    string(REGEX REPLACE "^machine-(media|conversion)$" "machine" owner "${owner}")
    string(REGEX REPLACE "^product-config$" "product" owner "${owner}")
    if(NOT owner IN_LIST components)
        message(FATAL_ERROR "Unknown ibmpc link owner: ${target}")
    endif()
    foreach(dependency IN LISTS args)
        if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
            continue()
        endif()
        if(owner STREQUAL "board-common" AND dependency MATCHES "^x86-core(-observable)?$")
            message(FATAL_ERROR "Board adapter must not select Core implementation: ${dependency}")
        endif()
        if(dependency MATCHES "^x86-(.+)$")
            set(chip "${CMAKE_MATCH_1}")
            if(chip STREQUAL "core" OR chip STREQUAL "core-observable")
                set(dependency x86/core)
            elseif(chip STREQUAL "debug")
                set(dependency x86/debug)
            else()
                set(dependency "x86/chips/${chip}")
            endif()
        elseif(dependency MATCHES "^common-(.+)$")
            set(dependency "common/${CMAKE_MATCH_1}")
        elseif(dependency MATCHES "^ibmpc-(.+)$")
            set(dependency "${CMAKE_MATCH_1}")
            string(REGEX REPLACE "^machine-(media|conversion)$" "machine" dependency "${dependency}")
            string(REGEX REPLACE "^product-config$" "product" dependency "${dependency}")
            set(dependency "ibmpc/${dependency}")
        else()
            set(dependency "lib/${dependency}")
        endif()
        check_edge("${owner}" "${dependency}")
    endforeach()
endforeach()
message(STATUS "ibmpc platform and component boundaries verified")
