#ifndef VM_MACHINE_MEDIA_H
#define VM_MACHINE_MEDIA_H


#define VM_MACHINE_MEDIA_FDD_ID 1u
#define VM_MACHINE_MEDIA_HDD_ID 2u
#define VM_MACHINE_MEDIA_FDD_SECONDARY_ID 3u
#define VM_MACHINE_MEDIA_HDD_SECONDARY_ID 4u

#endif
