cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit stack-frame probe root required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/cpu")
set(valid "static void _s_test_ss_frame(void)\n{\n_m_test_logical();\n}\nstatic void PUSHA(void)\n{\n_s_test_ss_frame();\n_e_push();\n}\nstatic void POPA(void)\n{\n_s_test_ss_frame();\n_kec_pop();\n}\nstatic void ENTER(void)\n{\n_s_test_ss_frame();\n_e_push();\nswitch (_GetStackSize)\n}\n")
function(check source accepted)
    file(WRITE "${PROBE_ROOT}/chips/cpu/cpu_instructions.c" "${source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DX86_ROOT=${PROBE_ROOT}"
        -P "${CMAKE_CURRENT_LIST_DIR}/verify_stack_frame.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(accepted)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Rejected valid stack owner: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}${error}" MATCHES "Stack boundary:")
        message(FATAL_ERROR "Stack violation not rejected: ${output}${error}")
    endif()
endfunction()
check("${valid}" TRUE)
string(REPLACE "_m_test_logical()" "_m_test_access()" invalid "${valid}")
check("${invalid}" FALSE)
string(REPLACE "_m_test_logical()" "cpu_state.data.sp = 1" invalid "${valid}")
check("${invalid}" FALSE)
string(REPLACE "_kec_pop()" "_e_pop()" invalid "${valid}")
check("${invalid}" FALSE)
string(REPLACE "_s_test_ss_frame();\n_e_push()" "_e_push();\n_s_test_ss_frame()" invalid "${valid}")
check("${invalid}" FALSE)
string(REPLACE "switch (_GetStackSize)" "switch (_GetStackSize)\nswitch (_GetStackSize)" invalid "${valid}")
check("${invalid}" FALSE)
file(REMOVE "${PROBE_ROOT}/chips/cpu/cpu_instructions.c")
message(STATUS "CPU stack frame verifier selftest: OK")
