cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit x86 and probe roots required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/debug" "${PROBE_ROOT}/xasm32")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/pit825x")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/rtc146818")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/pic8259")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/dma8237")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/ps2mouse")
file(MAKE_DIRECTORY "${PROBE_ROOT}/devices/keyboard" "${PROBE_ROOT}/devices/kbc8042")
function(reject owner source build expected)
    file(WRITE "${PROBE_ROOT}/${owner}/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DX86_ROOT=${PROBE_ROOT}
        -P "${X86_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(REMOVE "${PROBE_ROOT}/${owner}/probe.c")
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject(debug "#include <windows.h>\n" "" "Noncanonical")
reject(debug "struct hidden { HANDLE handle; };\n" "" "Platform implementation")
reject(debug "void f(void) { memcpy(0,0,0); }\n" "" "Raw CRT")
reject(debug "#include \"common/session/session_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "#include \"common/machine/input_queue.h\"\n" "" "Private dependency")
reject(debug "#include \"x86/xasm32/aasm32.h\"\n" "" "Private dependency")
reject(debug "#include \"../xasm32/aasm32.h\"\n" "" "Noncanonical")
reject(debug "#include \"lib/types/win32/window.h\"\n" "" "Noncanonical")
reject(debug "#include \"vm/vm_interface.h\"\n" "" "Noncanonical")
reject(xasm32 "#include \"x86/debug/protocol_interface.h\"\n" "" "Forbidden x86 edge")
reject(xasm32 "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "" "target_link_libraries(x86-debug PRIVATE common-session)\n" "Forbidden x86 edge")
reject(xasm32 "" "TARGET_LINK_LIBRARIES(x86-xasm32 PRIVATE x86-debug)\n" "Forbidden x86 edge")
reject(debug "" "if(WIN32)\nendif()\n" "must not select platform")
reject(devices/pit825x "#include \"app-nxvm/devices/port.h\"\n" "" "Noncanonical")
reject(devices/pit825x "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(devices/pit825x "#include \"x86/devices/dma8237/dma.h\"\n" "" "Forbidden x86 edge")
reject(debug "#include \"x86/devices/pit825x/pit.h\"\n" "" "Forbidden x86 edge")
reject(devices/pit825x "" "target_link_libraries(x86-pit825x PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/rtc146818 "#include \"app-nxvm/devices/pic.h\"\n" "" "Noncanonical")
reject(devices/rtc146818 "#include \"x86/devices/pit825x/pit.h\"\n" "" "Forbidden x86 edge")
reject(devices/rtc146818 "" "target_link_libraries(x86-rtc146818 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/pic8259 "#include \"app-nxvm/devices/pic_bus.h\"\n" "" "Noncanonical")
reject(devices/pic8259 "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(devices/pic8259 "#include \"x86/devices/rtc146818/rtc.h\"\n" "" "Forbidden x86 edge")
reject(devices/pic8259 "" "target_link_libraries(x86-pic8259 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/dma8237 "#include \"app-nxvm/devices/dma_bus.h\"\n" "" "Noncanonical")
reject(devices/dma8237 "#include \"x86/devices/pic8259/pic.h\"\n" "" "Forbidden x86 edge")
reject(devices/dma8237 "" "target_link_libraries(x86-dma8237 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/ps2mouse "#include \"app-nxvm/devices/kbc.h\"\n" "" "Noncanonical")
reject(devices/ps2mouse "#include \"x86/devices/pic8259/pic.h\"\n" "" "Forbidden x86 edge")
reject(devices/ps2mouse "" "target_link_libraries(x86-ps2mouse PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/keyboard "#include \"app-nxvm/devices/kbc.h\"\n" "" "Noncanonical")
reject(devices/keyboard "" "target_link_libraries(x86-keyboard PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(devices/kbc8042 "void f(void) { x86_keyboard_reset(0); }\n" "" "only the stateless scan codec")
reject(devices/kbc8042 "#include \"app-nxvm/devices/pic_bus.h\"\n" "" "Noncanonical")
reject(devices/kbc8042 "#include \"x86/devices/keyboard/keyboard.h\"\n" "" "Private dependency")
reject(devices/kbc8042 "" "target_link_libraries(x86-kbc8042 PRIVATE common-machine)\n" "Forbidden x86 edge")
file(REMOVE "${PROBE_ROOT}/CMakeLists.txt")
