cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit x86 and probe roots required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/debug" "${PROBE_ROOT}/xasm32")
function(reject owner source build expected)
    file(WRITE "${PROBE_ROOT}/${owner}/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DX86_ROOT=${PROBE_ROOT}
        -P "${X86_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(REMOVE "${PROBE_ROOT}/${owner}/probe.c")
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject(debug "#include <windows.h>\n" "" "Noncanonical")
reject(debug "struct hidden { HANDLE handle; };\n" "" "Platform implementation")
reject(debug "void f(void) { memcpy(0,0,0); }\n" "" "Raw CRT")
reject(debug "#include \"common/session/session_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "#include \"common/machine/input_queue.h\"\n" "" "Private dependency")
reject(debug "#include \"x86/xasm32/aasm32.h\"\n" "" "Private dependency")
reject(debug "#include \"../xasm32/aasm32.h\"\n" "" "Noncanonical")
reject(debug "#include \"lib/types/win32/window.h\"\n" "" "Noncanonical")
reject(debug "#include \"vm/vm_interface.h\"\n" "" "Noncanonical")
reject(xasm32 "#include \"x86/debug/protocol_interface.h\"\n" "" "Forbidden x86 edge")
reject(xasm32 "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "" "target_link_libraries(x86-debug PRIVATE common-session)\n" "Forbidden x86 edge")
reject(xasm32 "" "TARGET_LINK_LIBRARIES(x86-xasm32 PRIVATE x86-debug)\n" "Forbidden x86 edge")
reject(debug "" "if(WIN32)\nendif()\n" "must not select platform")
file(REMOVE "${PROBE_ROOT}/CMakeLists.txt")
