cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit host-arithmetic probe root required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/cpu")
function(check source accepted)
    file(WRITE "${PROBE_ROOT}/chips/cpu/cpu_instructions.c" "${source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DX86_ROOT=${PROBE_ROOT}"
        -P "${CMAKE_CURRENT_LIST_DIR}/verify_host_arithmetic.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(accepted)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Rejected safe expression: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}${error}" MATCHES "CPU pre-widening")
        message(FATAL_ERROR "Forbidden host arithmetic not rejected: ${output}${error}")
    endif()
endfunction()
check("result = (cpu_state.data.dx << 16) | cpu_state.data.ax;" FALSE)
check("result = MASK_U64(1 << temp);" FALSE)
check("result = MASK_U64((lib_i32)opr1 * (lib_i8)opr2);" FALSE)
check("_m_read_ref(context, ref, data, 4);" FALSE)
check("result = MASK_U16((lib_i16)result >> 1);" FALSE)
check("result = ((lib_u32)cpu_state.data.dx << 16) | cpu_state.data.ax;" TRUE)
check("result = MASK_U64((lib_i64)(lib_i32)opr1 * (lib_i64)(lib_i8)opr2);" TRUE)
check("result = MASK_U64(UINT64_C(1) << temp);" TRUE)
file(REMOVE "${PROBE_ROOT}/chips/cpu/cpu_instructions.c")
message(STATUS "CPU host arithmetic verifier selftest: OK")
