cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED X86_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit x86 and probe roots required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/debug" "${PROBE_ROOT}/xasm32")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/pit825x")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/rtc146818")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/pic8259")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/dma8237")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/ps2mouse")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/keyboard" "${PROBE_ROOT}/chips/kbc8042")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/ppi8255" "${PROBE_ROOT}/chips/xtkeyboard")
file(MAKE_DIRECTORY "${PROBE_ROOT}/chips/fpu")
file(MAKE_DIRECTORY "${PROBE_ROOT}/core")
file(MAKE_DIRECTORY "${PROBE_ROOT}/ibmpc-common")
file(MAKE_DIRECTORY "${PROBE_ROOT}/product")
function(reject owner source build expected)
    file(WRITE "${PROBE_ROOT}/${owner}/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DX86_ROOT=${PROBE_ROOT}
        -P "${X86_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(REMOVE "${PROBE_ROOT}/${owner}/probe.c")
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject(debug "#include <windows.h>\n" "" "Noncanonical")
reject(product "#include \"app-nxvm/product/config.h\"\n" "" "Noncanonical")
reject(product "#include \"common/machine/input_queue.h\"\n" "" "Forbidden x86 edge")
reject(debug "struct hidden { HANDLE handle; };\n" "" "Platform implementation")
reject(debug "void f(void) { memcpy(0,0,0); }\n" "" "Raw CRT")
reject(debug "#include \"common/session/session_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "#include \"common/machine/input_queue.h\"\n" "" "Private dependency")
reject(debug "#include \"x86/xasm32/aasm32.h\"\n" "" "Private dependency")
reject(debug "#include \"../xasm32/aasm32.h\"\n" "" "Noncanonical")
reject(debug "#include \"lib/types/win32/window.h\"\n" "" "Noncanonical")
reject(debug "#include \"vm/vm_interface.h\"\n" "" "Noncanonical")
reject(xasm32 "#include \"x86/debug/protocol_interface.h\"\n" "" "Forbidden x86 edge")
reject(xasm32 "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(debug "" "target_link_libraries(x86-debug PRIVATE common-session)\n" "Forbidden x86 edge")
reject(xasm32 "" "TARGET_LINK_LIBRARIES(x86-xasm32 PRIVATE x86-debug)\n" "Forbidden x86 edge")
reject(debug "" "if(WIN32)\nendif()\n" "must not select platform")
reject(chips/pit825x "#include \"x86/core/port.h\"\n" "" "Forbidden x86 edge")
reject(chips/pit825x "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(chips/pit825x "#include \"x86/chips/dma8237/dma.h\"\n" "" "Forbidden x86 edge")
reject(debug "#include \"x86/chips/pit825x/pit.h\"\n" "" "Forbidden x86 edge")
reject(chips/pit825x "" "target_link_libraries(x86-pit825x PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/rtc146818 "#include \"app-nxvm/devices/pic.h\"\n" "" "Noncanonical")
reject(chips/rtc146818 "#include \"x86/chips/pit825x/pit.h\"\n" "" "Forbidden x86 edge")
reject(chips/rtc146818 "" "target_link_libraries(x86-rtc146818 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/pic8259 "#include \"app-nxvm/devices/pic_bus.h\"\n" "" "Noncanonical")
reject(chips/pic8259 "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(chips/pic8259 "#include \"x86/chips/rtc146818/rtc.h\"\n" "" "Forbidden x86 edge")
reject(chips/pic8259 "" "target_link_libraries(x86-pic8259 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/dma8237 "#include \"app-nxvm/devices/dma_bus.h\"\n" "" "Noncanonical")
reject(chips/dma8237 "#include \"x86/chips/pic8259/pic.h\"\n" "" "Forbidden x86 edge")
reject(chips/dma8237 "" "target_link_libraries(x86-dma8237 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/ps2mouse "#include \"x86/ibmpc-at/kbc.h\"\n" "" "Forbidden x86 edge")
reject(chips/ps2mouse "#include \"x86/chips/pic8259/pic.h\"\n" "" "Forbidden x86 edge")
reject(chips/ps2mouse "" "target_link_libraries(x86-ps2mouse PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/keyboard "#include \"x86/ibmpc-at/kbc.h\"\n" "" "Forbidden x86 edge")
reject(chips/keyboard "" "target_link_libraries(x86-keyboard PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/kbc8042 "void f(void) { x86_keyboard_reset(0); }\n" "" "only the stateless scan codec")
reject(chips/kbc8042 "#include \"app-nxvm/devices/pic_bus.h\"\n" "" "Noncanonical")
reject(chips/kbc8042 "#include \"x86/chips/keyboard/keyboard.h\"\n" "" "Private dependency")
reject(chips/kbc8042 "" "target_link_libraries(x86-kbc8042 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/ppi8255 "#include \"x86/core/port.h\"\n" "" "Forbidden x86 edge")
reject(chips/ppi8255 "" "target_link_libraries(x86-ppi8255 PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/xtkeyboard "#include \"x86/chips/ppi8255/ppi8255_interface.h\"\n" "" "Forbidden x86 edge")
reject(chips/xtkeyboard "" "target_link_libraries(x86-xtkeyboard PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(chips/fpu "#include \"app-nxvm/devices/cpu_interface.h\"\n" "" "Noncanonical")
reject(chips/fpu "#include \"x86/chips/pic8259/pic.h\"\n" "" "Forbidden x86 edge")
reject(chips/fpu "" "target_link_libraries(x86-fpu PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(core "#include \"app-nxvm/devices/machine_board_interface.h\"\n" "" "Noncanonical")
reject(core "#include \"common/machine/machine_interface.h\"\n" "" "Forbidden x86 edge")
reject(core "#include \"x86/chips/pit825x/pit825x_interface.h\"\n" "" "Forbidden x86 edge")
reject(core "#include \"x86/chips/cpu/cpu.h\"\n" "" "Private dependency")
reject(core "" "target_link_libraries(x86-core PRIVATE common-machine)\n" "Forbidden x86 edge")
reject(ibmpc-common "#include \"app-nxvm/devices/machine_board_interface.h\"\n" "" "Noncanonical")
reject(ibmpc-common "#include \"x86/chips/video/video.h\"\n" "" "Private dependency")
reject(ibmpc-common "#include \"x86/chips/pit825x/pit.h\"\n" "" "Private dependency")
reject(ibmpc-common "#include \"x86/core/port.h\"\n" "" "Private dependency")
reject(ibmpc-common "" "target_link_libraries(x86-ibmpc-common PRIVATE x86-core)\n" "Board adapter must not select Core")
reject(ibmpc-common "" "target_link_libraries(x86-ibmpc-common PRIVATE x86-core-observable)\n" "Board adapter must not select Core")
reject(ibmpc-common "" "target_link_libraries(x86-ibmpc-common PRIVATE common-machine)\n" "Forbidden x86 edge")
file(REMOVE "${PROBE_ROOT}/CMakeLists.txt")
