cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED EMULATOR_ROOT)
    set(EMULATOR_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()

file(REAL_PATH "${EMULATOR_ROOT}" emulator_root)
set(emulator_manifest "${emulator_root}/MANIFEST.sha256")
if(NOT EXISTS "${emulator_manifest}")
    message(FATAL_ERROR "missing emulator manifest: ${emulator_manifest}")
endif()

file(STRINGS "${emulator_manifest}" manifest_lines)
list(GET manifest_lines 0 manifest_header)
if(NOT manifest_header STREQUAL "# sha256-manifest-v1")
    message(FATAL_ERROR "invalid emulator manifest header: ${manifest_header}")
endif()
set(manifest_paths)
set(previous_path "")
foreach(line IN LISTS manifest_lines)
    if(line STREQUAL "# sha256-manifest-v1")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid emulator manifest line: ${line}")
    else()
        set(expected_hash "${CMAKE_MATCH_1}")
        set(relative_path "${CMAKE_MATCH_2}")
        string(LENGTH "${expected_hash}" hash_length)
        if(NOT hash_length EQUAL 64)
            message(FATAL_ERROR "invalid emulator manifest hash: ${relative_path}")
        endif()
        if(relative_path IN_LIST manifest_paths)
            message(FATAL_ERROR "duplicate emulator manifest path: ${relative_path}")
        endif()
        if(NOT previous_path STREQUAL "" AND relative_path STRLESS previous_path)
            message(FATAL_ERROR "emulator manifest paths are not ordered: ${relative_path}")
        endif()
        set(source_path "${emulator_root}/${relative_path}")
        if(NOT EXISTS "${source_path}" OR IS_DIRECTORY "${source_path}")
            message(FATAL_ERROR "missing emulator source: ${relative_path}")
        endif()
        file(READ "${source_path}" contents)
        string(FIND "${contents}" "\r" carriage_return)
        if(NOT carriage_return EQUAL -1)
            message(FATAL_ERROR "emulator source must use LF: ${relative_path}")
        endif()
        file(SHA256 "${source_path}" actual_hash)
        string(TOUPPER "${actual_hash}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "emulator manifest mismatch: ${relative_path}")
        endif()
        list(APPEND manifest_paths "${relative_path}")
        set(previous_path "${relative_path}")
    endif()
endforeach()

file(GLOB_RECURSE actual_paths RELATIVE "${emulator_root}" "${emulator_root}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${emulator_root}/${relative_path}" OR
       relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST manifest_paths)
        message(FATAL_ERROR "emulator manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS manifest_paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "emulator manifest stale path: ${relative_path}")
    endif()
endforeach()

message(STATUS "emulator manifest verified: ${emulator_root}")
