cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED EMULATOR_ROOT)
    set(EMULATOR_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components machine session ui)
set(edges_machine base kvm-base kvm-window kvm-console storage types)
set(edges_session machine ui base console kvm-base types)
set(edges_ui console console-broker kvm-base kvm-window kvm-console types)
set(lib_components types base console-broker storage console kvm-base kvm-window kvm-console)

function(check_edge owner dependency)
    if(NOT dependency STREQUAL owner AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden Emulator edge: ${owner} -> ${dependency}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${EMULATOR_ROOT}" "${EMULATOR_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "Emulator must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "^([^/]+)/.*\\.[ch]$")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    if(NOT owner IN_LIST components)
        message(FATAL_ERROR "Unknown Emulator component: ${path}")
    endif()
    file(READ "${EMULATOR_ROOT}/${path}" source)
    # Assembly text legitimately contains DWORD; inspect tokens, not literals.
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in Emulator; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(U?INT[A-Z0-9_]*|SIZE|PTRDIFF|WCHAR|WINT)_(MAX|MIN)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw integer limit in Emulator; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|Interlocked[A-Za-z]+|WaitForSingleObject|CreateEvent[A-W]?|SetEvent|ResetEvent|CloseHandle|pthread_" OR
       tokens MATCHES "(^|[^A-Za-z0-9_])(HANDLE|DWORD|LONG|HWND)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Platform implementation in Emulator: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(header MATCHES "^(emulator|lib)/([^/]+)/(.+)$")
            set(corpus "${CMAKE_MATCH_1}")
            set(dependency "${CMAKE_MATCH_2}")
            set(file "${CMAKE_MATCH_3}")
            if(NOT file MATCHES "^[A-Za-z0-9_-]+\\.h$")
                message(FATAL_ERROR "Noncanonical Emulator header path: ${header}")
            endif()
            if(corpus STREQUAL "emulator" AND NOT dependency IN_LIST components)
                message(FATAL_ERROR "Unknown Emulator dependency: ${header}")
            elseif(corpus STREQUAL "lib" AND NOT dependency IN_LIST lib_components)
                message(FATAL_ERROR "Unknown Lib dependency: ${header}")
            endif()
            check_edge("${owner}" "${dependency}")
            if(owner STREQUAL "machine" AND dependency MATCHES "^kvm-(window|console)$"
                    AND NOT file STREQUAL "frame_interface.h")
                message(FATAL_ERROR "Machine may consume only KVM frame values: ${header}")
            endif()
            if(corpus STREQUAL "emulator" AND dependency STREQUAL owner)
                if(NOT EXISTS "${EMULATOR_ROOT}/${dependency}/${file}")
                    message(FATAL_ERROR "Missing local header: ${header}")
                endif()
            elseif(NOT dependency STREQUAL "types" AND
                   NOT file MATCHES "^[^/]+_interface\\.h$")
                message(FATAL_ERROR "Private dependency in Emulator: ${header}")
            endif()
            if(dependency STREQUAL "kvm-base" AND NOT file MATCHES "^(event|frame|hotkey)_interface\\.h$")
                message(FATAL_ERROR "Private KVM support in Emulator: ${header}")
            endif()
        else()
            message(FATAL_ERROR "Noncanonical Emulator include: ${header}")
        endif()
    endforeach()
endforeach()

file(GLOB_RECURSE builds "${EMULATOR_ROOT}/CMakeLists.txt")
foreach(build IN LISTS builds)
    file(READ "${build}" source)
    string(REGEX REPLACE "#[^\n]*" "" source "${source}")
    if(source MATCHES "(WIN32|LINUX|UNIX|APPLE|CMAKE_SYSTEM_NAME)")
        message(FATAL_ERROR "Emulator build must not select platform implementations")
    endif()
    string(TOLOWER "${source}" source)
    if(source MATCHES "(^|[^_A-Za-z])link_libraries[ \t\r\n]*\\(" OR
       source MATCHES "(interface_)?link_libraries[ \t]")
        message(FATAL_ERROR "Use explicit Emulator target_link_libraries")
    endif()
    string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${source}")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
        string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
        list(POP_FRONT args target)
        string(REGEX REPLACE "^emulator-" "" owner "${target}")
        if(NOT owner IN_LIST components)
            message(FATAL_ERROR "Unknown Emulator link owner: ${target}")
        endif()
        foreach(dependency IN LISTS args)
            if(dependency MATCHES "^(public|private|interface)$" OR dependency STREQUAL "")
                continue()
            endif()
            string(REGEX REPLACE "^emulator-" "" dependency "${dependency}")
            check_edge("${owner}" "${dependency}")
        endforeach()
    endforeach()
endforeach()
message(STATUS "Emulator platform and component boundaries verified")
