# Synthetic bytes only: this unit never opens a BYOB archive.
file(MAKE_DIRECTORY "${WORK}")
string(ASCII 1 127 255 sample)
file(WRITE "${WORK}/sample.rom" "${sample}")
file(WRITE "${WORK}/empty.rom" "")
foreach(case IN ITEMS present absent empty missing)
    set(input "${WORK}/sample.rom")
    if(case STREQUAL "absent")
        set(input LIB_NULL)
    elseif(case STREQUAL "empty")
        set(input "${WORK}/empty.rom")
    elseif(case STREQUAL "missing")
        set(input "${WORK}/does-not-exist.rom")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DINPUT_BIOS_0=${input}" -DINPUT_BIOS_1=LIB_NULL
        -DINPUT_VIDEO=LIB_NULL -DINPUT_CMOS=LIB_NULL -DINPUT_FONT=LIB_NULL
        "-DOUTPUT=${WORK}/${case}.c" -P "${EMBED_SCRIPT}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(case STREQUAL "empty" OR case STREQUAL "missing")
        if(status EQUAL 0)
            message(FATAL_ERROR "Embedding accepted ${case} input")
        endif()
        continue()
    endif()
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Embedding rejected ${case}: ${error}")
    endif()
    file(READ "${WORK}/${case}.c" generated)
    string(FIND "${generated}" "${WORK}" path_index)
    if(NOT path_index EQUAL -1)
        message(FATAL_ERROR "Generated firmware leaks a build-input path")
    endif()
    if(case STREQUAL "present")
        string(FIND "${generated}" "0x01,0x7f,0xff," bytes_index)
        string(FIND "${generated}" "{firmware_BIOS_0, sizeof(firmware_BIOS_0)}" view_index)
        if(bytes_index EQUAL -1 OR view_index EQUAL -1)
            message(FATAL_ERROR "Embedding changed bytes or extent")
        endif()
    else()
        string(FIND "${generated}" ".bios = {{LIB_NULL, 0u}, {LIB_NULL, 0u}}" view_index)
        if(view_index EQUAL -1)
            message(FATAL_ERROR "Absent firmware has a nonempty view")
        endif()
    endif()
endforeach()
message(STATUS "Firmware embedding synthetic inputs: OK")
