# Repository-owned guest source only; no external firmware/media is opened.
file(MAKE_DIRECTORY "${WORK}")
foreach(pass IN ITEMS first second)
    execute_process(COMMAND "${BUILDER}" "${SOURCE}" "${WORK}/${pass}.rom"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Firmware construction failed: ${output}${error}")
    endif()
    file(SIZE "${WORK}/${pass}.rom" bytes)
    if(NOT bytes EQUAL 65536)
        message(FATAL_ERROR "Firmware extent is not 64 KiB")
    endif()
endforeach()
file(SHA256 "${WORK}/first.rom" first_hash)
file(SHA256 "${WORK}/second.rom" second_hash)
if(NOT first_hash STREQUAL second_hash)
    message(FATAL_ERROR "Firmware construction is nondeterministic")
endif()
file(READ "${WORK}/first.rom" reset OFFSET 65520 LIMIT 5 HEX)
if(NOT reset MATCHES "^ea[0-9a-f][0-9a-f][0-9a-f][0-9a-f]00f0$")
    message(FATAL_ERROR "Reset does not far-jump into the F000 guest ROM")
endif()
file(READ "${WORK}/first.rom" fallback OFFSET 0 LIMIT 1 HEX)
if(NOT fallback STREQUAL "cf")
    message(FATAL_ERROR "Unassigned vectors no longer point to IRET")
endif()
foreach(vector IN ITEMS 8 9 14 16 17 18 19 21 22 26 64 118)
    math(EXPR offset "0xf800 + ${vector} * 4")
    file(READ "${WORK}/first.rom" entry OFFSET ${offset} LIMIT 4 HEX)
    if(NOT entry MATCHES "^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]00f0$" OR
        entry STREQUAL "000000f0")
        message(FATAL_ERROR "Missing guest interrupt vector ${vector}")
    endif()
endforeach()

# Assembly failures must not publish a truncated or partial ROM over old output.
file(MAKE_DIRECTORY "${WORK}/invalid")
foreach(case IN ITEMS missing invalid empty oversized)
    file(COPY "${SOURCE}/" DESTINATION "${WORK}/invalid" FILES_MATCHING PATTERN "*.asm")
    if(case STREQUAL "missing")
        file(REMOVE "${WORK}/invalid/floppy.asm")
    elseif(case STREQUAL "invalid")
        file(WRITE "${WORK}/invalid/floppy.asm" "invalid_instruction\n")
    elseif(case STREQUAL "empty")
        file(WRITE "${WORK}/invalid/floppy.asm" "")
    else()
        string(REPEAT "nop\n" 20000 excessive_code)
        file(WRITE "${WORK}/invalid/floppy.asm" "${excessive_code}")
    endif()
    execute_process(COMMAND "${BUILDER}" "${WORK}/invalid" "${WORK}/second.rom"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(status EQUAL 0)
        message(FATAL_ERROR "Firmware construction accepted ${case} source")
    endif()
    file(SHA256 "${WORK}/second.rom" preserved_hash)
    if(NOT preserved_hash STREQUAL second_hash)
        message(FATAL_ERROR "Failed ${case} assembly replaced the previous output")
    endif()
endforeach()
message(STATUS "Firmware deterministic build, layout and failed-assembly publication: OK")
