#ifndef LIB_TYPES_WIN32_CONSOLE_H
#define LIB_TYPES_WIN32_CONSOLE_H

/* Win32 Console records, handles and I/O declarations. */
#include <windows.h>

typedef CHAR_INFO lib_win32_char_info;
typedef CONSOLE_CURSOR_INFO lib_win32_console_cursor_info;
typedef CONSOLE_SCREEN_BUFFER_INFO lib_win32_console_screen_buffer_info;
typedef CONSOLE_SCREEN_BUFFER_INFOEX lib_win32_console_screen_buffer_infoex;
typedef COORD lib_win32_coord;
typedef INPUT_RECORD lib_win32_input_record;
typedef KEY_EVENT_RECORD lib_win32_key_event_record;
typedef MOUSE_EVENT_RECORD lib_win32_mouse_event_record;
typedef SMALL_RECT lib_win32_small_rect;
#define lib_win32_cancel_io_ex CancelIoEx
#define lib_win32_cancel_synchronous_io CancelSynchronousIo
#define lib_win32_flush_console_input_buffer FlushConsoleInputBuffer
#define lib_win32_get_console_mode GetConsoleMode
#define lib_win32_get_console_screen_buffer_info GetConsoleScreenBufferInfo
#define lib_win32_get_console_screen_buffer_info_ex GetConsoleScreenBufferInfoEx
#define lib_win32_get_console_window GetConsoleWindow
#define lib_win32_read_console_a ReadConsoleA
#define lib_win32_read_console_input_w ReadConsoleInputW
#define lib_win32_set_console_cursor_info SetConsoleCursorInfo
#define lib_win32_set_console_cursor_position SetConsoleCursorPosition
#define lib_win32_set_console_mode SetConsoleMode
#define lib_win32_set_console_screen_buffer_info_ex SetConsoleScreenBufferInfoEx
#define lib_win32_set_console_screen_buffer_size SetConsoleScreenBufferSize
#define lib_win32_set_console_window_info SetConsoleWindowInfo
#define lib_win32_write_console_a WriteConsoleA
#define lib_win32_write_console_input_a WriteConsoleInputA
#define lib_win32_write_console_output_w WriteConsoleOutputW
#define LIB_WIN32_ENABLE_ECHO_INPUT ENABLE_ECHO_INPUT
#define LIB_WIN32_ENABLE_EXTENDED_FLAGS ENABLE_EXTENDED_FLAGS
#define LIB_WIN32_ENABLE_LINE_INPUT ENABLE_LINE_INPUT
#define LIB_WIN32_ENABLE_MOUSE_INPUT ENABLE_MOUSE_INPUT
#define LIB_WIN32_ENABLE_PROCESSED_INPUT ENABLE_PROCESSED_INPUT
#define LIB_WIN32_ENABLE_QUICK_EDIT_MODE ENABLE_QUICK_EDIT_MODE
#define LIB_WIN32_ENABLE_VIRTUAL_TERMINAL_INPUT ENABLE_VIRTUAL_TERMINAL_INPUT
#define LIB_WIN32_ENHANCED_KEY ENHANCED_KEY
#define LIB_WIN32_FROM_LEFT_1ST_BUTTON_PRESSED FROM_LEFT_1ST_BUTTON_PRESSED
#define LIB_WIN32_RIGHTMOST_BUTTON_PRESSED RIGHTMOST_BUTTON_PRESSED
#define LIB_WIN32_LEFT_ALT_PRESSED LEFT_ALT_PRESSED
#define LIB_WIN32_LEFT_CTRL_PRESSED LEFT_CTRL_PRESSED
#define LIB_WIN32_RIGHT_ALT_PRESSED RIGHT_ALT_PRESSED
#define LIB_WIN32_RIGHT_CTRL_PRESSED RIGHT_CTRL_PRESSED
#define LIB_WIN32_SHIFT_PRESSED SHIFT_PRESSED
#define LIB_WIN32_KEY_EVENT KEY_EVENT
#define LIB_WIN32_MOUSE_EVENT MOUSE_EVENT

#endif
