#ifndef LIB_TYPES_WIN32_INPUT_H
#define LIB_TYPES_WIN32_INPUT_H

#include <windows.h>

/* Exact SDK queries. Key/modifier interpretation belongs to ui-base. */
typedef SHORT lib_win32_key_state;
#define lib_win32_get_key_state GetKeyState
#define lib_win32_map_virtual_key MapVirtualKeyA
#define lib_win32_key_scan VkKeyScanW

/* VkKeyScan high-byte flags, as specified by the Win32 API. */
#define LIB_WIN32_KEY_SCAN_SHIFT 1u
#define LIB_WIN32_KEY_SCAN_CONTROL 2u
#define LIB_WIN32_KEY_SCAN_ALT 4u

#define LIB_WIN32_MAPVK_VK_TO_VSC MAPVK_VK_TO_VSC
#define LIB_WIN32_KEY_BACK VK_BACK
#define LIB_WIN32_KEY_TAB VK_TAB
#define LIB_WIN32_KEY_RETURN VK_RETURN
#define LIB_WIN32_KEY_SHIFT VK_SHIFT
#define LIB_WIN32_KEY_CONTROL VK_CONTROL
#define LIB_WIN32_KEY_ALT VK_MENU
#define LIB_WIN32_KEY_PAUSE VK_PAUSE
#define LIB_WIN32_KEY_CAPS_LOCK VK_CAPITAL
#define LIB_WIN32_KEY_ESCAPE VK_ESCAPE
#define LIB_WIN32_KEY_SPACE VK_SPACE
#define LIB_WIN32_KEY_PAGE_UP VK_PRIOR
#define LIB_WIN32_KEY_PAGE_DOWN VK_NEXT
#define LIB_WIN32_KEY_END VK_END
#define LIB_WIN32_KEY_HOME VK_HOME
#define LIB_WIN32_KEY_LEFT VK_LEFT
#define LIB_WIN32_KEY_UP VK_UP
#define LIB_WIN32_KEY_RIGHT VK_RIGHT
#define LIB_WIN32_KEY_DOWN VK_DOWN
#define LIB_WIN32_KEY_SNAPSHOT VK_SNAPSHOT
#define LIB_WIN32_KEY_INSERT VK_INSERT
#define LIB_WIN32_KEY_DELETE VK_DELETE
#define LIB_WIN32_KEY_0 '0'
#define LIB_WIN32_KEY_9 '9'
#define LIB_WIN32_KEY_A 'A'
#define LIB_WIN32_KEY_Z 'Z'
#define LIB_WIN32_KEY_LEFT_WINDOWS VK_LWIN
#define LIB_WIN32_KEY_RIGHT_WINDOWS VK_RWIN
#define LIB_WIN32_KEY_APPS VK_APPS
#define LIB_WIN32_KEY_NUMPAD_0 VK_NUMPAD0
#define LIB_WIN32_KEY_NUMPAD_9 VK_NUMPAD9
#define LIB_WIN32_KEY_MULTIPLY VK_MULTIPLY
#define LIB_WIN32_KEY_ADD VK_ADD
#define LIB_WIN32_KEY_SUBTRACT VK_SUBTRACT
#define LIB_WIN32_KEY_DECIMAL VK_DECIMAL
#define LIB_WIN32_KEY_DIVIDE VK_DIVIDE
#define LIB_WIN32_KEY_F1 VK_F1
#define LIB_WIN32_KEY_F12 VK_F12
#define LIB_WIN32_KEY_F13 VK_F13
#define LIB_WIN32_KEY_F24 VK_F24
#define LIB_WIN32_KEY_NUM_LOCK VK_NUMLOCK
#define LIB_WIN32_KEY_SCROLL_LOCK VK_SCROLL
#define LIB_WIN32_KEY_LEFT_SHIFT VK_LSHIFT
#define LIB_WIN32_KEY_RIGHT_SHIFT VK_RSHIFT
#define LIB_WIN32_KEY_LEFT_CONTROL VK_LCONTROL
#define LIB_WIN32_KEY_RIGHT_CONTROL VK_RCONTROL
#define LIB_WIN32_KEY_LEFT_ALT VK_LMENU
#define LIB_WIN32_KEY_RIGHT_ALT VK_RMENU
#define LIB_WIN32_KEY_OEM_1 VK_OEM_1
#define LIB_WIN32_KEY_OEM_PLUS VK_OEM_PLUS
#define LIB_WIN32_KEY_OEM_COMMA VK_OEM_COMMA
#define LIB_WIN32_KEY_OEM_MINUS VK_OEM_MINUS
#define LIB_WIN32_KEY_OEM_PERIOD VK_OEM_PERIOD
#define LIB_WIN32_KEY_OEM_2 VK_OEM_2
#define LIB_WIN32_KEY_OEM_3 VK_OEM_3
#define LIB_WIN32_KEY_OEM_4 VK_OEM_4
#define LIB_WIN32_KEY_OEM_5 VK_OEM_5
#define LIB_WIN32_KEY_OEM_6 VK_OEM_6
#define LIB_WIN32_KEY_OEM_7 VK_OEM_7

#endif
