cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED COMMON_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit Common and probe roots required")
endif()
file(MAKE_DIRECTORY "${PROBE_ROOT}/machine")
function(reject source build expected)
    file(WRITE "${PROBE_ROOT}/machine/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DCOMMON_ROOT=${PROBE_ROOT}
        -P "${COMMON_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject("#include <windows.h>\n" "" "Noncanonical")
reject("#ifdef _WIN32\n#endif\n" "" "Platform implementation")
reject("struct hidden { HANDLE event; };\n" "" "Platform implementation")
reject("pthread_mutex_t gate;\n" "" "Platform implementation")
foreach(symbol IN ITEMS memset memcpy memmove memcmp memchr strlen strcmp
        strchr strtok calloc malloc realloc free snprintf)
    reject("void probe(void) { ${symbol}(0); }\n" "" "Raw CRT vocabulary")
    reject("#define LEGACY_${symbol} ${symbol}\n" "" "Raw CRT vocabulary")
endforeach()
reject("#include \"lib/types/win32/sync.h\"\n" "" "Noncanonical Common header path")
reject("#include \"common/session/session_interface.h\"\n" "" "Forbidden Common edge")
reject("#include \"lib/base/sync.h\"\n" "" "Private dependency")
reject("#include \"lib/kvm-base/component_interface.h\"\n" "" "Private KVM support")
reject("#include \"../session/control.h\"\n" "" "Noncanonical")
reject("#include \"common/machine/../../host/machine.h\"\n" "" "Noncanonical")
reject("" "target_link_libraries(common-machine PRIVATE user32)\n" "Forbidden Common edge")
reject("" "target_link_libraries(common-machine PRIVATE common-ui)\n" "Forbidden Common edge")
reject("" "TARGET_LINK_LIBRARIES(common-machine PRIVATE common-ui)\n" "Forbidden Common edge")
reject("" "if(WIN32)\nendif()\n" "must not select platform")
file(WRITE "${PROBE_ROOT}/machine/probe.c" "")
file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "")
file(WRITE "${PROBE_ROOT}/MANIFEST.sha256" "# corpus-revision: probe\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DCOMMON_ROOT=${PROBE_ROOT}
    -P "${COMMON_ROOT}/verify_manifest.cmake" RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "manifest missing path")
    message(FATAL_ERROR "Manifest failed to reject unlisted corpus content")
endif()
# Remove only files created by this test, never an arbitrary caller directory.
file(REMOVE "${PROBE_ROOT}/machine/probe.c" "${PROBE_ROOT}/CMakeLists.txt"
    "${PROBE_ROOT}/MANIFEST.sha256")
