cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED EMULATOR_ROOT OR NOT DEFINED PROBE_ROOT)
    message(FATAL_ERROR "Explicit Emulator and probe roots required")
endif()
file(REMOVE_RECURSE "${PROBE_ROOT}")
file(MAKE_DIRECTORY "${PROBE_ROOT}/machine")
function(reject source build expected)
    file(WRITE "${PROBE_ROOT}/machine/probe.c" "${source}")
    file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "${build}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DEMULATOR_ROOT=${PROBE_ROOT}
        -P "${EMULATOR_ROOT}/verify_corpus.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${expected}, got ${result}: ${output}${error}")
    endif()
endfunction()
reject("#include <windows.h>\n" "" "Noncanonical")
foreach(header IN ITEMS assert limits stddef stdint stdio stdlib string stdarg
        ctype math stdbool float)
    reject("#include <${header}.h>\n" "" "Noncanonical Emulator include")
    reject("#include \"${header}.h\"\n" "" "Noncanonical Emulator include")
endforeach()
foreach(symbol IN ITEMS UINT_MAX INT32_MAX INT32_MIN UINT32_MAX UINT64_MAX
        SIZE_MAX UINT_FAST16_MAX PTRDIFF_MAX)
    reject("unsigned value = ${symbol};\n" "" "Raw integer limit")
    reject("#define LEGACY_LIMIT ${symbol}\n" "" "Raw integer limit")
endforeach()
file(WRITE "${PROBE_ROOT}/machine/probe_interface.h" "#include <stdint.h>\n")
reject("" "" "Noncanonical Emulator include")
file(REMOVE "${PROBE_ROOT}/machine/probe_interface.h")
reject("#ifdef _WIN32\n#endif\n" "" "Platform implementation")
reject("struct hidden { HANDLE event; };\n" "" "Platform implementation")
reject("pthread_mutex_t gate;\n" "" "Platform implementation")
foreach(symbol IN ITEMS memset memcpy memmove memcmp memchr strlen strcmp
        strchr strtok calloc malloc realloc free snprintf)
    reject("void probe(void) { ${symbol}(0); }\n" "" "Raw CRT vocabulary")
    reject("#define LEGACY_${symbol} ${symbol}\n" "" "Raw CRT vocabulary")
endforeach()
reject("#include \"lib/types/win32/sync.h\"\n" "" "Noncanonical Emulator header path")
reject("#include \"emulator/session/session_interface.h\"\n" "" "Forbidden Emulator edge")
reject("#include \"foreign/debug/protocol_interface.h\"\n" "" "Noncanonical Emulator include")
reject("#include \"emulator/debug/debug_interface.h\"\n" "" "Unknown Emulator dependency")
reject("#include \"emulator/xasm32/xasm32_interface.h\"\n" "" "Unknown Emulator dependency")
reject("#include \"lib/base/sync.h\"\n" "" "Private dependency")
reject("#include \"lib/kvm-base/component_interface.h\"\n" "" "Private KVM support")
reject("#include \"lib/kvm-window/window_interface.h\"\n" "" "only KVM frame values")
reject("#include \"lib/kvm-console/console_interface.h\"\n" "" "only KVM frame values")
reject("#include \"../session/control.h\"\n" "" "Noncanonical")
reject("#include \"emulator/machine/../../host/machine.h\"\n" "" "Noncanonical")
reject("" "target_link_libraries(emulator-machine PRIVATE user32)\n" "Forbidden Emulator edge")
reject("" "target_link_libraries(emulator-machine PRIVATE emulator-ui)\n" "Forbidden Emulator edge")
reject("" "TARGET_LINK_LIBRARIES(emulator-machine PRIVATE emulator-ui)\n" "Forbidden Emulator edge")
reject("" "if(WIN32)\nendif()\n" "must not select platform")
file(WRITE "${PROBE_ROOT}/machine/probe.c"
    "#include \"lib/types/types_interface.h\"\nlib_u32 limit = LIB_UINT32_MAX;\n"
    "lib_size size = LIB_SIZE_MAX;\n/* UINT_MAX */\nconst char *name = \"UINT32_MAX\";\n")
file(WRITE "${PROBE_ROOT}/CMakeLists.txt"
    "target_link_libraries(emulator-machine PRIVATE types)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DEMULATOR_ROOT=${PROBE_ROOT}
    -P "${EMULATOR_ROOT}/verify_corpus.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Legal Types vocabulary rejected: ${output}${error}")
endif()
file(WRITE "${PROBE_ROOT}/machine/probe.c" "")
file(WRITE "${PROBE_ROOT}/CMakeLists.txt" "")
file(WRITE "${PROBE_ROOT}/MANIFEST.sha256" "# sha256-manifest-v1\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DEMULATOR_ROOT=${PROBE_ROOT}
    -P "${EMULATOR_ROOT}/verify_manifest.cmake" RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "manifest missing path")
    message(FATAL_ERROR "Manifest failed to reject unlisted corpus content")
endif()
# Remove only files created by this test, never an arbitrary caller directory.
file(REMOVE "${PROBE_ROOT}/machine/probe.c" "${PROBE_ROOT}/CMakeLists.txt"
    "${PROBE_ROOT}/MANIFEST.sha256")

# Emulator fixtures may inspect their own owner, not include Lib implementation.
function(private_lib_include source output)
    set(found "")
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[\"<]lib/[^\">]+[\">]" includes "${source}")
    foreach(include IN LISTS includes)
        if(NOT include MATCHES "[\"<]lib/types/[A-Za-z0-9_/]+\\.h[\">]$" AND
           NOT include MATCHES "[\"<]lib/[a-z0-9-]+/[a-z0-9_]+_interface\\.h[\">]$")
            set(found "${include}")
            break()
        endif()
    endforeach()
    set(${output} "${found}" PARENT_SCOPE)
endfunction()
foreach(header IN ITEMS lib/kvm-window/window.h lib/kvm-window/win32/component.c)
    private_lib_include("#include \"${header}\"" invalid)
    if(NOT invalid)
        message(FATAL_ERROR "Private Lib test include was accepted: ${header}")
    endif()
endforeach()
file(GLOB_RECURSE fixtures "${CMAKE_CURRENT_LIST_DIR}/*.c" "${CMAKE_CURRENT_LIST_DIR}/*.h")
foreach(fixture IN LISTS fixtures)
    file(READ "${fixture}" source)
    private_lib_include("${source}" invalid)
    if(invalid)
        message(FATAL_ERROR "Private Lib dependency in Emulator test ${fixture}: ${invalid}")
    endif()
endforeach()
