#ifndef NXVM_CORE_MACHINE_KEYBOARD_STATE_H
#define NXVM_CORE_MACHINE_KEYBOARD_STATE_H

#include <stdint.h>

#define NXVM_KEYBOARD_ASYNC_RIGHT_SHIFT (UINT32_C(1) << 0)
#define NXVM_KEYBOARD_ASYNC_LEFT_SHIFT  (UINT32_C(1) << 1)
#define NXVM_KEYBOARD_ASYNC_CONTROL     (UINT32_C(1) << 2)
#define NXVM_KEYBOARD_ASYNC_ALT         (UINT32_C(1) << 3)
#define NXVM_KEYBOARD_ASYNC_SCROLL_LOCK (UINT32_C(1) << 4)
#define NXVM_KEYBOARD_ASYNC_NUM_LOCK    (UINT32_C(1) << 5)
#define NXVM_KEYBOARD_ASYNC_CAPS_LOCK   (UINT32_C(1) << 6)
#define NXVM_KEYBOARD_ASYNC_INSERT      (UINT32_C(1) << 7)

#define NXVM_KEYBOARD_TOGGLE_SCROLL_LOCK (UINT32_C(1) << 0)
#define NXVM_KEYBOARD_TOGGLE_NUM_LOCK    (UINT32_C(1) << 1)
#define NXVM_KEYBOARD_TOGGLE_CAPS_LOCK   (UINT32_C(1) << 2)
#define NXVM_KEYBOARD_TOGGLE_INSERT      (UINT32_C(1) << 3)
#define NXVM_KEYBOARD_TOGGLE_PAUSE       (UINT32_C(1) << 4)

#endif
