cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED CORE_ROOT)
    set(CORE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()

# Core owns the NXVM-only machine stack.  Validate source includes rather
# than target names, so the boundary remains visible to standalone consumers.
file(GLOB_RECURSE core_sources RELATIVE "${CORE_ROOT}" "${CORE_ROOT}/*.[ch]")
foreach(path IN LISTS core_sources)
    if(NOT path MATCHES "^(chips/[^/]+|x86|board-base|board-at|board-xt|machine|product)/[^/]+\\.[ch]$" AND
       NOT path MATCHES "^machine/media/[^/]+\\.[ch]$")
        message(FATAL_ERROR "Noncanonical Core source path: ${path}")
    endif()
    file(READ "${CORE_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in Core: ${path}")
    endif()
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(HANDLE|DWORD|LONG|HWND)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Platform type in Core: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(header MATCHES "^(app-|vm/)")
            message(FATAL_ERROR "Core may not depend on an App: ${path} -> ${header}")
        endif()
        if(header MATCHES "^product/surface/" AND NOT path MATCHES "^product/")
            message(FATAL_ERROR "Only core/product may consume portable Product: ${path} -> ${header}")
        endif()
        if(header MATCHES "^core/product/" AND NOT path MATCHES "^product/")
            message(FATAL_ERROR "Inner Core component depends on core/product: ${path} -> ${header}")
        endif()
        if(header MATCHES "^core/machine/" AND path MATCHES "^(chips|x86|board-base|board-at|board-xt)/")
            message(FATAL_ERROR "Lower Core component depends on machine adapter: ${path} -> ${header}")
        endif()
    endforeach()
endforeach()
message(STATUS "Core component boundaries verified")
