if(NOT DEFINED PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE OR
        "${PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE}" STREQUAL "")
    message(FATAL_ERROR
        "M5:T355:S2:WINDOWS31-HDD-CHECKPOINT requires PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE")
endif()

if(NOT EXISTS "${PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE}")
    message(FATAL_ERROR
        "M5:T355:S2:WINDOWS31-HDD-CHECKPOINT input does not exist: ${PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE}")
endif()

if(NOT DEFINED PROJECT_T355_CHECKPOINT_EXECUTABLE OR
        NOT EXISTS "${PROJECT_T355_CHECKPOINT_EXECUTABLE}")
    message(FATAL_ERROR
        "M5:T355:S2:WINDOWS31-HDD-CHECKPOINT probe executable is unavailable")
endif()

execute_process(
    COMMAND "${PROJECT_T355_CHECKPOINT_EXECUTABLE}"
        "${PROJECT_WINDOWS31_CHECKPOINT_HDD_IMAGE}"
    RESULT_VARIABLE project_t355_checkpoint_result)
if(NOT project_t355_checkpoint_result EQUAL 0)
    message(FATAL_ERROR
        "M5:T355:S2:WINDOWS31-HDD-CHECKPOINT probe failed: ${project_t355_checkpoint_result}")
endif()

message("M5:T355:S2:WINDOWS31-HDD-CHECKPOINT:OK")
