if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/cpu_bus.c" core)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/board_advance.c" board)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine_board.c" wiring)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine.c" creation)
foreach(forbidden "machine->shared_pic_master" "machine->shared_pic_slave"
    "core_machine_pic_scan_interrupt(" "core_machine_pic_get_interrupt(")
    string(FIND "${core}" "${forbidden}" position)
    if(NOT position LESS 0)
        message(FATAL_ERROR "CPU bus directly owns board PIC: ${forbidden}")
    endif()
endforeach()
foreach(required "board_pic_pending_provider(machine->board_owner)"
    "board_pic_acknowledge_provider(machine->board_owner)"
    "CORE_MACHINE_TRANSACTION_CPU_INTERRUPT_ACKNOWLEDGE"
    "core_machine_transaction_commit(" "core_machine_external_cycle_invalidate(machine)")
    string(FIND "${core}" "${required}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Core PIC/CPU locality lacks ${required}")
    endif()
endforeach()
foreach(required "core_machine_board_pic_pending(" "core_machine_board_pic_acknowledge("
    "core_machine_pic_scan_interrupt(" "core_machine_pic_get_interrupt(")
    string(FIND "${board}" "${required}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Board PIC signal lacks ${required}")
    endif()
endforeach()
string(FIND "${wiring}" "core_machine_external_cycle_invalidate(machine)" position)
if(NOT position LESS 0)
    message(FATAL_ERROR "Board refresh output mutates CPU locality directly")
endif()
string(FIND "${wiring}" "core_machine_cpu_bus_refresh_pulse(machine)" position)
if(position LESS 0)
    message(FATAL_ERROR "Board refresh pulse does not notify Core")
endif()
foreach(required "board_pic_pending_provider = core_machine_board_pic_pending"
    "board_pic_acknowledge_provider = core_machine_board_pic_acknowledge")
    string(FIND "${creation}" "${required}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Board PIC provider not bound: ${required}")
    endif()
endforeach()
message("M5:T540:S29:BOARD-PIC-CPU-LOCALITY:OK")
