if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine_scheduler.c" core)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/board_advance.c" board)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine_board.c" creation)
foreach(effect "core_machine_fdc_advance_at(" "core_machine_hdc_advance_at("
    "x86_rtc_advance(")
    string(FIND "${core}" "${effect}" core_position)
    string(FIND "${board}" "${effect}" board_position)
    if(NOT core_position LESS 0 OR board_position LESS 0)
        message(FATAL_ERROR "Readiness effect has wrong owner: ${effect}")
    endif()
endforeach()
string(FIND "${board}" "x86_fpu_advance(" board_fpu)
if(NOT board_fpu LESS 0)
    message(FATAL_ERROR "Board owns Core FPU advancement")
endif()
string(FIND "${core}" "machine->attachment.media(machine->attachment.context, source_ticks, due_tick);" media)
string(FIND "${core}" "x86_fpu_advance(machine->fpu, source_ticks);" fpu)
string(FIND "${core}" "machine->attachment.rtc(machine->attachment.context, source_ticks);" rtc)
if(media LESS 0 OR fpu LESS media OR rtc LESS fpu)
    message(FATAL_ERROR "Core lost media-FPU-RTC readiness order")
endif()
foreach(binding "core_machine_board_media_advance" "core_machine_board_rtc_advance")
    string(FIND "${creation}" "${binding}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Readiness provider is not bound: ${binding}")
    endif()
endforeach()
message("M5:T540:S24:BOARD-READINESS:OK")
