if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine_board.c" board_source)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/memory.c" memory_source)
foreach(personality IN ITEMS planar_parity d4_platform)
    string(FIND "${board_source}"
        "lib_status core_machine_configure_${personality}(" first)
    if(personality STREQUAL "planar_parity")
        string(FIND "${board_source}"
            "lib_status core_machine_configure_d4_platform(" last)
    else()
        string(FIND "${board_source}"
            "lib_status core_machine_report_planar_parity_fault(" last)
    endif()
    if(first LESS 0 OR last LESS first)
        message(FATAL_ERROR "Port-B ${personality} construction range is missing")
    endif()
    math(EXPR length "${last} - ${first}")
    string(SUBSTRING "${board_source}" ${first} ${length} construction)
    string(FIND "${construction}" "core_machine_install_port_routes" position)
    if(position LESS 0)
        message(FATAL_ERROR "Port-B ${personality} must publish one Core route")
    endif()
    foreach(forbidden IN ITEMS "executor_port" "checkpoint"
        "core_machine_install_port_provider" "core_machine_port_rollback_registration")
        string(FIND "${construction}" "${forbidden}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "Port-B ${personality} retains raw registration: ${forbidden}")
        endif()
    endforeach()
    if(personality STREQUAL "planar_parity")
        string(FIND "${construction}" "core_machine_memory_enable_parity(" prepare_position)
        string(FIND "${construction}" "core_machine_memory_release_parity(" rollback_position)
        string(FIND "${construction}" "core_machine_install_port_routes(" publish_position)
        if(prepare_position LESS 0 OR publish_position LESS prepare_position OR
            rollback_position LESS publish_position)
            message(FATAL_ERROR "Port-B parity preparation/rollback order is incomplete")
        endif()
    endif()
endforeach()
string(FIND "${memory_source}" "core_machine_memory_release_parity(ram);" finalize_position)
if(finalize_position LESS 0)
    message(FATAL_ERROR "Port-B parity rollback and finalization must share one release")
endif()

message("M5:T540:S13:BOARD-PORT-B-BOUNDARY:OK")
