if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/x86/product/machine/lifecycle.c" lifecycle)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/profiles/machine_plan.c" plan)
file(READ "${PROJECT_SOURCE_DIR}/src/app-nxvm/profiles/default_profile/external_pc_at_rom.c" provider)
file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" cmake_source)

string(FIND "${plan}" "vm_profile_external_pc_at_rom_provider" position)
if(position EQUAL -1)
    message(FATAL_ERROR "External-ROM plan boundary missing its provider")
endif()
string(FIND "${lifecycle}" "core_machine_bind_firmware_provider" position)
if(position EQUAL -1)
    message(FATAL_ERROR "External-ROM lifecycle boundary missing provider binding")
endif()
string(FIND "${provider}" "core_machine_firmware_register_immutable_rom" position)
if(position EQUAL -1)
    message(FATAL_ERROR "External-ROM provider does not map immutable firmware")
endif()
foreach(forbidden "default_pc_at.c" "rom/bios.c" "rom/qdcga.c")
    string(FIND "${cmake_source}" "${forbidden}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "Generated product firmware remains in CMake: ${forbidden}")
    endif()
endforeach()

# Profiles map supplied immutable bytes; only the build may open ROM files.
file(GLOB_RECURSE profile_sources
    "${PROJECT_SOURCE_DIR}/src/app-nxvm/profiles/*.c"
    "${PROJECT_SOURCE_DIR}/src/app-nxvm/profiles/*.h")
foreach(path IN LISTS profile_sources)
    file(READ "${path}" text)
    if(text MATCHES "lib_storage_file_|lib_storage_medium_open|fopen[ \t]*\\(|CreateFile|ReadFile|bios_path|video_path|font_path|create_file_backed|byob_manifest_load")
        message(FATAL_ERROR "Runtime firmware file route in profile: ${path}")
    endif()
endforeach()

message(STATUS "M5:T539:S12:IMMUTABLE-ROM-CLOSURE:OK")
