if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/machine.c")
set(machine_model "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/cpu_timing_model.c")
set(preview "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/cpu_instructions.c")
set(bus "${PROJECT_SOURCE_DIR}/src/app-nxvm/devices/cpu_bus.c")
set(preview_smoke "${PROJECT_SOURCE_DIR}/test/app-nxvm/unit/core/devices/core_machine_cpu_timing_preview_smoke.c")
set(timing_smoke "${PROJECT_SOURCE_DIR}/test/app-nxvm/unit/core/devices/core_machine_instruction_timing_smoke.c")
set(evidence "${PROJECT_SOURCE_DIR}/docs/nxvm/etc/evidence/t388-s5-jcc-target-lexeme.md")
foreach(path IN ITEMS "${machine}" "${machine_model}" "${preview}" "${bus}" "${preview_smoke}" "${timing_smoke}" "${evidence}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "T388 Jcc target-lexeme input is missing: ${path}")
    endif()
endforeach()
foreach(item IN ITEMS machine preview bus preview_smoke timing_smoke evidence)
    file(READ "${${item}}" ${item}_text)
endforeach()
file(READ "${machine_model}" machine_model_text)
set(machine_text "${machine_text}${machine_model_text}")
function(t388_require text token)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 Jcc target-lexeme drift: ${token}")
    endif()
endfunction()
foreach(token IN ITEMS "core_machine_cpu_execution_preview_lexeme" "CORE_MACHINE_80386_JCC_TAKEN_TICKS" "core_machine_source_timing_mark_unallocated")
    t388_require("${machine_text}" "${token}")
    t388_require("${evidence_text}" "${token}")
endforeach()
t388_require("${preview_text}" "preview_mode = LIB_TRUE")
t388_require("${preview_text}" "memory_status = context->bus->read_memory(context->bus_context, physical,")
t388_require("${preview_text}" "(void *)rdata, byte, provenance, context->preview_mode,")
t388_require("${bus_text}" "if (observe_only) {
        return core_machine_memory_inspect_physical(&machine->executor_memory,
            address, (lib_uptr)destination, bytes, reset_fetch);
    }
    status = core_machine_transaction_begin")
if(preview_text MATCHES "core_machine_memory_(inspect|read)_.*physical\\(")
    message(FATAL_ERROR "CPU preview must use the bus observation contract, not board memory")
endif()
if(machine_model_text MATCHES "core_machine_memory_read_(physical|reset_physical)\\(")
    message(FATAL_ERROR "CPU timing must inspect memory, not issue device reads")
endif()
t388_require("${preview_smoke_text}" "preview_test_taken_near_jcc_target")
t388_require("${preview_smoke_text}" "0x66u, 0x0fu, 0x84u")
t388_require("${timing_smoke_text}" "static const lib_u8 jcc[]")
t388_require("${timing_smoke_text}" "result.ticks != 9u")
t388_require("${evidence_text}" "M5:T388:S5:JCC-TARGET-LEXEME:OK")
message(STATUS "T388 Jcc target-lexeme boundary passed.")
