if(NOT DEFINED PROJECT_DEFERRED_DIRECT_OWNERSHIP_VERIFIER OR NOT EXISTS "${PROJECT_DEFERRED_DIRECT_OWNERSHIP_VERIFIER}" OR
        NOT DEFINED PROJECT_DIRECT_COMPILATION_MATRIX_FILE OR NOT EXISTS "${PROJECT_DIRECT_COMPILATION_MATRIX_FILE}" OR
        NOT DEFINED PROJECT_OWNER_TEST_STRICT_TARGETS_FILE OR NOT EXISTS "${PROJECT_OWNER_TEST_STRICT_TARGETS_FILE}" OR
        NOT DEFINED PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE OR NOT EXISTS "${PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE}" OR
        NOT DEFINED PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE OR NOT EXISTS "${PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE}" OR
        NOT DEFINED PROJECT_INVALID_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE OR NOT EXISTS "${PROJECT_INVALID_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE}")
    message(FATAL_ERROR "Deferred-ownership verifier self-test inputs are required.")
endif()
execute_process(
    COMMAND "${CMAKE_COMMAND}"
        -DPROJECT_DIRECT_COMPILATION_MATRIX_FILE:FILEPATH=${PROJECT_DIRECT_COMPILATION_MATRIX_FILE}
        -DPROJECT_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE:FILEPATH=${PROJECT_INVALID_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE}
        -DPROJECT_OWNER_TEST_STRICT_TARGETS_FILE:FILEPATH=${PROJECT_OWNER_TEST_STRICT_TARGETS_FILE}
        -DPROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE:FILEPATH=${PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE}
        -DPROJECT_RESIDUAL_DIRECT_ENTRIES_FILE:FILEPATH=${PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE}
        -P "${PROJECT_DEFERRED_DIRECT_OWNERSHIP_VERIFIER}"
    RESULT_VARIABLE project_deferred_direct_selftest_result)
if(project_deferred_direct_selftest_result EQUAL 0)
    message(FATAL_ERROR "Deferred-ownership verifier accepted its invalid duplicate fixture.")
endif()
message(STATUS "Deferred ownership verifier self-test passed.")
