if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/core/x86/machine.c")
set(machine_model "${PROJECT_SOURCE_DIR}/src/core/chips/cpu/cpu_timing_model.c")
set(s2 "${PROJECT_SOURCE_DIR}/docs/nxvm/etc/evidence/t388-s2-successful-sentinel-matrix.md")
set(s4 "${PROJECT_SOURCE_DIR}/docs/nxvm/etc/evidence/t388-s4-residual-form-context-ledger.md")
set(authority "${PROJECT_SOURCE_DIR}/docs/nxvm/etc/evidence/t360-s1-four-profile-source-authority-consumer-inventory.md")
foreach(path IN ITEMS "${machine}" "${s2}" "${s4}" "${authority}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Residual ledger input is missing: ${path}")
    endif()
endforeach()
file(READ "${machine}" machine_text)
file(READ "${machine_model}" machine_model_text)
set(machine_text "${machine_text}${machine_model_text}")
file(READ "${s2}" s2_text)
file(READ "${s4}" s4_text)
file(READ "${authority}" authority_text)
function(physical_timing_require text token)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Residual ledger drift: ${token}")
    endif()
endfunction()
foreach(token IN ITEMS
    "core_machine_source_timing_lookup"
    "core_machine_legacy_source_instruction_cost"
    "core_machine_string_io_source_instruction_cost"
    "core_machine_80286_source_instruction_cost"
    "core_machine_80386_source_instruction_cost"
    "core_machine_cpu_execution_preview_lexeme"
    "CORE_MACHINE_SOURCE_UNALLOCATED_TICKS")
    physical_timing_require("${machine_text}" "${token}")
    physical_timing_require("${s2_text}" "${token}")
    physical_timing_require("${s4_text}" "${token}")
endforeach()
foreach(token IN ITEMS "Tables 2-20/2-21" "Table 1-16" "Appendix B" "section 17.2.2.3")
    physical_timing_require("${authority_text}" "${token}")
    physical_timing_require("${s4_text}" "${token}")
endforeach()
physical_timing_require("${s4_text}" "M5:T388:S4:RESIDUAL-FORM-CONTEXT-LEDGER:OK")
message(STATUS "Residual form/context ledger passed.")
