foreach(required IN ITEMS PROJECT_T344_CURRENT_TARGETS_FILE
        PROJECT_T344_CURRENT_AUXILIARY_TESTS_FILE PROJECT_T344_CTEST_TEST_FILE)
    if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
        message(FATAL_ERROR "T344 registration input is required: ${required}")
    endif()
endforeach()

file(STRINGS "${PROJECT_T344_CURRENT_TARGETS_FILE}" targets)
file(STRINGS "${PROJECT_T344_CURRENT_AUXILIARY_TESTS_FILE}" auxiliary)
file(STRINGS "${PROJECT_T344_CTEST_TEST_FILE}" ctest_lines)
get_filename_component(test_build_root "${PROJECT_T344_CTEST_TEST_FILE}" DIRECTORY)
file(STRINGS "${test_build_root}/test/core/CTestTestfile.cmake" core_ctest_lines)
list(APPEND ctest_lines ${core_ctest_lines})
file(STRINGS "${test_build_root}/test/core/CTestTestfile.cmake" ibmpc_ctest_lines)
list(APPEND ctest_lines ${ibmpc_ctest_lines})
set(registered)
foreach(line IN LISTS ctest_lines)
    if(line MATCHES "^add_test\\(\\[=\\[(unit|integration)\\.([^]]+)\\]=\\]")
        list(APPEND registered "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^add_test\\(\\\"(unit|integration)\\.([^\\\"]+)\\\"")
        list(APPEND registered "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^add_test\\(\\[=\\[x86\\.[^]]+\\]=\\] \"([^\"]+)\"")
        # Shared registration names belong to x86, not a product unit alias.
        # Match the real executable target rather than inventing a second name.
        get_filename_component(shared_target "${CMAKE_MATCH_1}" NAME_WE)
        if(shared_target IN_LIST targets)
            list(APPEND registered "${shared_target}")
        endif()
    endif()
endforeach()
foreach(target IN LISTS targets auxiliary)
    list(FIND registered "${target}" registered_index)
    if(registered_index EQUAL -1)
        message(FATAL_ERROR "T344 target lacks a CTest route: ${target}")
    endif()
endforeach()
if(DEFINED PROJECT_T515_INI_BOOT_CASES_FILE)
    if(NOT EXISTS "${PROJECT_T515_INI_BOOT_CASES_FILE}")
        message(FATAL_ERROR "T515 INI boot registration input is missing.")
    endif()
    file(STRINGS "${PROJECT_T515_INI_BOOT_CASES_FILE}" matrix_cases)
    list(LENGTH matrix_cases matrix_case_count)
    if(NOT matrix_case_count EQUAL 1)
        message(FATAL_ERROR "Fixed product build must register exactly one INI boot row.")
    endif()
    foreach(matrix_case IN LISTS matrix_cases)
        list(FIND registered "${matrix_case}" matrix_case_index)
        if(matrix_case_index EQUAL -1)
            message(FATAL_ERROR "T515 INI boot case lacks a CTest route: ${matrix_case}")
        endif()
        list(REMOVE_ITEM registered "${matrix_case}")
    endforeach()
endif()
list(SORT registered)
list(LENGTH registered route_count)
list(REMOVE_DUPLICATES registered)
list(LENGTH registered unique_route_count)
if(NOT route_count EQUAL unique_route_count)
    message(FATAL_ERROR "T344 test has more than one CTest route.")
endif()
list(LENGTH targets target_count)
list(LENGTH auxiliary auxiliary_count)
math(EXPR expected_count "${target_count} + ${auxiliary_count}")
list(LENGTH registered registered_count)
if(NOT registered_count EQUAL expected_count)
    message(FATAL_ERROR "T344 registration has an unexpected test count.")
endif()
message(STATUS "M5:T500:S4:TEST-NO-DUAL-REGISTRATION:OK:${registered_count}")
