if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/core/board-base/machine_board.c" board_source)
file(READ "${PROJECT_SOURCE_DIR}/src/core/x86/memory.c" memory_source)
file(READ "${PROJECT_SOURCE_DIR}/src/core/x86/memory_interface.c" memory_boundary)
file(READ "${PROJECT_SOURCE_DIR}/src/core/board-at/parity.c" parity_source)
file(READ "${PROJECT_SOURCE_DIR}/src/app-mydeskpro386/profiles/d4_platform.c" d4_source)
foreach(personality IN ITEMS planar_parity d4_platform)
    if(personality STREQUAL "planar_parity")
        set(owner_source "${parity_source}")
        string(FIND "${owner_source}" "lib_status core_machine_at_parity_create(" first)
        string(FIND "${owner_source}" "void core_machine_at_parity_observe(" last)
    else()
        set(owner_source "${d4_source}")
        string(FIND "${owner_source}" "lib_status core_machine_d4_platform_create(" first)
        string(FIND "${owner_source}" "void core_machine_d4_platform_destroy(" last)
    endif()
    if(first LESS 0 OR last LESS first)
        message(FATAL_ERROR "Port-B ${personality} construction range is missing")
    endif()
    math(EXPR length "${last} - ${first}")
    string(SUBSTRING "${owner_source}" ${first} ${length} construction)
    string(FIND "${construction}" "core_machine_install_port_routes" position)
    if(position LESS 0)
        message(FATAL_ERROR "Port-B ${personality} must publish one Core route")
    endif()
    foreach(forbidden IN ITEMS "executor_port" "checkpoint"
        "core_machine_install_port_provider" "core_machine_port_rollback_registration")
        string(FIND "${construction}" "${forbidden}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "Port-B ${personality} retains raw registration: ${forbidden}")
        endif()
    endforeach()
    if(personality STREQUAL "planar_parity")
        string(FIND "${construction}" "core_machine_install_memory_device_routes(" prepare_position)
        string(FIND "${construction}" "core_machine_remove_memory_device_routes(" rollback_position)
        string(FIND "${construction}" "core_machine_install_port_routes(" publish_position)
        string(FIND "${construction}" "*out_parity = parity;" commit_position)
        if(prepare_position LESS 0 OR publish_position LESS prepare_position OR
            rollback_position LESS publish_position OR commit_position LESS rollback_position)
            message(FATAL_ERROR "Port-B parity preparation/rollback order is incomplete")
        endif()
        foreach(forbidden IN ITEMS "executor_memory" "core_machine_memory_enable_parity("
            "core_machine_memory_release_parity(")
            string(FIND "${construction}" "${forbidden}" position)
            if(NOT position EQUAL -1)
                message(FATAL_ERROR "Port-B parity retains raw memory construction: ${forbidden}")
            endif()
        endforeach()
    endif()
endforeach()
if(NOT board_source MATCHES "core_machine_at_parity_create\\(board->core," OR
    board_source MATCHES "core_machine_configure_d4_platform|d4_platform_port_b")
    message(FATAL_ERROR "Common Board must compose AT parity without owning Model40 Port-B state")
endif()
foreach(required IN ITEMS "core_machine_memory_enable_parity(memory, parity->bytes,"
    "machine->executor_memory.connect.parity_owner == owner"
    "core_machine_memory_release_parity(&machine->executor_memory);")
    string(FIND "${memory_boundary}" "${required}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Core parity preparation/owner cleanup is missing: ${required}")
    endif()
endforeach()
string(FIND "${memory_source}" "core_machine_memory_release_parity(ram);" finalize_position)
if(finalize_position LESS 0)
    message(FATAL_ERROR "Port-B parity rollback and finalization must share one release")
endif()

message("M5:T540:S13:BOARD-PORT-B-BOUNDARY:OK")
