if(NOT DEFINED PROJECT_ARTIFACT_PATH OR
   NOT DEFINED PROJECT_ARTIFACT_ARCHITECTURE)
    message(FATAL_ERROR "Artifact path and architecture are required.")
endif()
if(NOT PROJECT_ARTIFACT_ARCHITECTURE MATCHES "^(x64|x86)$")
    message(FATAL_ERROR "Artifact architecture must be x64 or x86.")
endif()

file(READ "${PROJECT_ARTIFACT_PATH}" dos_header HEX LIMIT 64)
string(SUBSTRING "${dos_header}" 120 2 offset0)
string(SUBSTRING "${dos_header}" 122 2 offset1)
string(SUBSTRING "${dos_header}" 124 2 offset2)
string(SUBSTRING "${dos_header}" 126 2 offset3)
math(EXPR pe_offset "0x${offset3}${offset2}${offset1}${offset0}")
file(READ "${PROJECT_ARTIFACT_PATH}" pe_header HEX OFFSET ${pe_offset} LIMIT 26)
string(SUBSTRING "${pe_header}" 0 8 signature)
string(SUBSTRING "${pe_header}" 8 4 machine)
string(SUBSTRING "${pe_header}" 48 4 optional_magic)
if(NOT signature STREQUAL "50450000")
    message(FATAL_ERROR "Artifact is not a PE executable: ${PROJECT_ARTIFACT_PATH}")
endif()
if(PROJECT_ARTIFACT_ARCHITECTURE STREQUAL "x64")
    set(expected_machine "6486")
    set(expected_optional_magic "0b02")
else()
    set(expected_machine "4c01")
    set(expected_optional_magic "0b01")
endif()
if(NOT machine STREQUAL expected_machine OR
   NOT optional_magic STREQUAL expected_optional_magic)
    message(FATAL_ERROR
        "Artifact PE architecture does not match ${PROJECT_ARTIFACT_ARCHITECTURE}: ${PROJECT_ARTIFACT_PATH}")
endif()
message("NXVM artifact architecture: ${PROJECT_ARTIFACT_ARCHITECTURE}: OK")
