if(NOT DEFINED PROJECT_DIRECT_COMPILATION_MATRIX_FILE OR
        NOT EXISTS "${PROJECT_DIRECT_COMPILATION_MATRIX_FILE}")
    message(FATAL_ERROR "Deferred direct ownership requires the Direct-compilation matrix.")
endif()
if(NOT DEFINED PROJECT_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE OR
        NOT EXISTS "${PROJECT_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE}")
    message(FATAL_ERROR "Deferred ownership matrix is required.")
endif()
if(NOT DEFINED PROJECT_OWNER_TEST_STRICT_TARGETS_FILE OR
        NOT EXISTS "${PROJECT_OWNER_TEST_STRICT_TARGETS_FILE}")
    message(FATAL_ERROR "owner-test strict classification target inventory is required.")
endif()
if(NOT DEFINED PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE OR
        NOT EXISTS "${PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE}")
    message(FATAL_ERROR "safe-production strict classification production inventory is required.")
endif()
if(NOT DEFINED PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE OR
        NOT EXISTS "${PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE}")
    message(FATAL_ERROR "residual direct classification residual inventory is required.")
endif()

file(STRINGS "${PROJECT_DIRECT_COMPILATION_MATRIX_FILE}" project_direct_compilation_rows)
file(STRINGS "${PROJECT_DEFERRED_DIRECT_OWNERSHIP_MATRIX_FILE}" project_deferred_direct_ownership_rows)
file(STRINGS "${PROJECT_OWNER_TEST_STRICT_TARGETS_FILE}" project_owner_test_targets)
file(STRINGS "${PROJECT_SAFE_PRODUCTION_STRICT_ENTRIES_FILE}" project_safe_production_entries)
file(STRINGS "${PROJECT_RESIDUAL_DIRECT_ENTRIES_FILE}" project_residual_direct_residual_entries)
set(project_safe_production_targets)
foreach(project_safe_production_entry IN LISTS project_safe_production_entries)
    string(REPLACE "|" ";" project_safe_production_fields "${project_safe_production_entry}")
    list(LENGTH project_safe_production_fields project_safe_production_field_count)
    if(NOT project_safe_production_field_count EQUAL 2)
        message(FATAL_ERROR "Malformed safe-production strict classification entry: ${project_safe_production_entry}")
    endif()
    list(GET project_safe_production_fields 0 project_safe_production_target)
    list(APPEND project_safe_production_targets "${project_safe_production_target}")
endforeach()
set(project_residual_direct_residual_keys)
foreach(project_residual_direct_entry IN LISTS project_residual_direct_residual_entries)
    string(REPLACE "|" ";" project_residual_direct_fields "${project_residual_direct_entry}")
    list(LENGTH project_residual_direct_fields project_residual_direct_field_count)
    if(NOT project_residual_direct_field_count EQUAL 3)
        message(FATAL_ERROR "Malformed residual direct classification residual entry: ${project_residual_direct_entry}")
    endif()
    list(GET project_residual_direct_fields 0 project_residual_direct_target)
    list(GET project_residual_direct_fields 1 project_residual_direct_source)
    list(GET project_residual_direct_fields 2 project_residual_direct_domain)
    if(project_residual_direct_domain STREQUAL "")
        message(FATAL_ERROR "residual direct classification residual entry has no domain: ${project_residual_direct_entry}")
    endif()
    set(project_residual_direct_key "${project_residual_direct_target}|${project_residual_direct_source}")
    list(FIND project_residual_direct_residual_keys "${project_residual_direct_key}"
        project_residual_direct_duplicate_index)
    if(NOT project_residual_direct_duplicate_index EQUAL -1)
        message(FATAL_ERROR "Duplicate residual direct classification residual entry: ${project_residual_direct_key}")
    endif()
    list(APPEND project_residual_direct_residual_keys "${project_residual_direct_key}")
endforeach()
set(project_deferred_direct_expected_keys)
foreach(project_deferred_direct_row IN LISTS project_direct_compilation_rows)
    string(REPLACE "|" ";" project_deferred_direct_fields "${project_deferred_direct_row}")
    list(LENGTH project_deferred_direct_fields project_deferred_direct_count)
    if(NOT project_deferred_direct_count EQUAL 4)
        message(FATAL_ERROR "Malformed Direct compilation row in Deferred direct ownership verifier: ${project_deferred_direct_row}")
    endif()
    list(GET project_deferred_direct_fields 0 project_deferred_direct_target)
    list(GET project_deferred_direct_fields 1 project_deferred_direct_source)
    list(GET project_deferred_direct_fields 2 project_deferred_direct_status)
    list(FIND project_owner_test_targets "${project_deferred_direct_target}" project_owner_test_target_index)
    list(FIND project_safe_production_targets "${project_deferred_direct_target}" project_safe_production_target_index)
    if(project_deferred_direct_status STREQUAL "deferred" OR
            (project_deferred_direct_status STREQUAL "retained-strict" AND
            NOT project_owner_test_target_index EQUAL -1 AND
            project_deferred_direct_source MATCHES "^test/") OR
            (project_deferred_direct_status STREQUAL "retained-strict" AND
            NOT project_safe_production_target_index EQUAL -1))
        list(APPEND project_deferred_direct_expected_keys "${project_deferred_direct_target}|${project_deferred_direct_source}")
    endif()
endforeach()

set(project_deferred_direct_seen_keys)
set(project_deferred_direct_owner_test_count 0)
set(project_deferred_direct_embedded_count 0)
set(project_deferred_direct_type_count 0)
set(project_deferred_direct_safe_production_count 0)
set(project_deferred_direct_mixed_count 0)
set(project_deferred_direct_expected_residual_keys)
set(project_deferred_direct_expected_strict_keys)
foreach(project_deferred_direct_row IN LISTS project_deferred_direct_ownership_rows)
    string(REPLACE "|" ";" project_deferred_direct_fields "${project_deferred_direct_row}")
    list(LENGTH project_deferred_direct_fields project_deferred_direct_count)
    if(NOT project_deferred_direct_count EQUAL 4)
        message(FATAL_ERROR "Malformed deferred-ownership row: ${project_deferred_direct_row}")
    endif()
    list(GET project_deferred_direct_fields 0 project_deferred_direct_target)
    list(GET project_deferred_direct_fields 1 project_deferred_direct_source)
    list(GET project_deferred_direct_fields 2 project_deferred_direct_class)
    list(GET project_deferred_direct_fields 3 project_deferred_direct_mechanism)
    set(project_deferred_direct_key "${project_deferred_direct_target}|${project_deferred_direct_source}")
    list(FIND project_deferred_direct_expected_keys "${project_deferred_direct_key}" project_deferred_direct_expected_index)
    if(project_deferred_direct_expected_index EQUAL -1)
        message(FATAL_ERROR "Deferred-ownership row is not a deferred direct-compilation row: ${project_deferred_direct_key}")
    endif()
    list(FIND project_deferred_direct_seen_keys "${project_deferred_direct_key}" project_deferred_direct_seen_index)
    if(NOT project_deferred_direct_seen_index EQUAL -1)
        message(FATAL_ERROR "Duplicate deferred-ownership row: ${project_deferred_direct_key}")
    endif()
    list(APPEND project_deferred_direct_seen_keys "${project_deferred_direct_key}")
    if(project_deferred_direct_class STREQUAL "project-owned-owner-test" AND
            project_deferred_direct_mechanism STREQUAL "owner-test-strict-cohort")
        math(EXPR project_deferred_direct_owner_test_count "${project_deferred_direct_owner_test_count} + 1")
    elseif(project_deferred_direct_class STREQUAL "embedded-production-test" AND
            project_deferred_direct_mechanism STREQUAL "production-owner-warning-remediation")
        math(EXPR project_deferred_direct_embedded_count "${project_deferred_direct_embedded_count} + 1")
        list(APPEND project_deferred_direct_expected_residual_keys "${project_deferred_direct_key}")
    elseif(project_deferred_direct_class STREQUAL "type-foundation-production" AND
            project_deferred_direct_mechanism STREQUAL "safe-production-strict-cohort")
        math(EXPR project_deferred_direct_type_count "${project_deferred_direct_type_count} + 1")
        list(APPEND project_deferred_direct_expected_strict_keys "${project_deferred_direct_key}")
    elseif(project_deferred_direct_class STREQUAL "safely-separable-production" AND
            project_deferred_direct_mechanism STREQUAL "safe-production-strict-cohort")
        math(EXPR project_deferred_direct_safe_production_count "${project_deferred_direct_safe_production_count} + 1")
        list(APPEND project_deferred_direct_expected_strict_keys "${project_deferred_direct_key}")
    elseif(project_deferred_direct_class STREQUAL "mixed-or-inherited-production" AND
            project_deferred_direct_mechanism STREQUAL "ownership-separation-and-warning-remediation")
        math(EXPR project_deferred_direct_mixed_count "${project_deferred_direct_mixed_count} + 1")
        list(APPEND project_deferred_direct_expected_residual_keys "${project_deferred_direct_key}")
    else()
        message(FATAL_ERROR "Unknown deferred-ownership class or mechanism: ${project_deferred_direct_row}")
    endif()
endforeach()

list(LENGTH project_deferred_direct_expected_keys project_deferred_direct_expected_count)
list(LENGTH project_deferred_direct_seen_keys project_deferred_direct_seen_count)
list(LENGTH project_owner_test_targets project_owner_test_target_count)
if(NOT project_deferred_direct_seen_count EQUAL project_deferred_direct_expected_count)
    message(FATAL_ERROR "Deferred-ownership matrix has ${project_deferred_direct_seen_count} rows; expected ${project_deferred_direct_expected_count}.")
endif()
list(LENGTH project_safe_production_entries project_safe_production_entry_count)
foreach(project_deferred_direct_expected_strict_key IN LISTS project_deferred_direct_expected_strict_keys)
    list(FIND project_safe_production_entries "${project_deferred_direct_expected_strict_key}"
        project_safe_production_index)
    if(project_safe_production_index EQUAL -1)
        message(FATAL_ERROR "Missing safe-production strict entry: ${project_deferred_direct_expected_strict_key}")
    endif()
endforeach()
foreach(project_safe_production_entry IN LISTS project_safe_production_entries)
    list(FIND project_deferred_direct_expected_strict_keys "${project_safe_production_entry}"
        project_safe_production_index)
    if(project_safe_production_index EQUAL -1)
        message(FATAL_ERROR "Unexpected safe-production strict entry: ${project_safe_production_entry}")
    endif()
endforeach()
list(LENGTH project_deferred_direct_expected_residual_keys project_deferred_direct_expected_residual_count)
list(LENGTH project_residual_direct_residual_keys project_residual_direct_residual_count)
foreach(project_deferred_direct_expected_residual_key IN LISTS project_deferred_direct_expected_residual_keys)
    list(FIND project_residual_direct_residual_keys "${project_deferred_direct_expected_residual_key}"
        project_residual_direct_residual_index)
    if(project_residual_direct_residual_index EQUAL -1)
        message(FATAL_ERROR "Missing residual direct classification residual entry: ${project_deferred_direct_expected_residual_key}")
    endif()
endforeach()
foreach(project_residual_direct_residual_key IN LISTS project_residual_direct_residual_keys)
    list(FIND project_deferred_direct_expected_residual_keys "${project_residual_direct_residual_key}"
        project_deferred_direct_expected_residual_index)
    if(project_deferred_direct_expected_residual_index EQUAL -1)
        message(FATAL_ERROR "Unexpected residual direct classification residual entry: ${project_residual_direct_residual_key}")
    endif()
endforeach()
message(STATUS "Deferred ownership passed: ${project_deferred_direct_seen_count} rows (${project_deferred_direct_owner_test_count} owner tests, ${project_deferred_direct_embedded_count} embedded production tests, ${project_deferred_direct_type_count} type foundation, ${project_deferred_direct_safe_production_count} safely separable production, ${project_deferred_direct_mixed_count} mixed/inherited production, ${project_deferred_direct_expected_residual_count} exact residual production entries).")
