if(NOT DEFINED PROJECT_STRICT_DECLARATION_MATRIX OR
    NOT EXISTS "${PROJECT_STRICT_DECLARATION_MATRIX}")
    message(FATAL_ERROR "Strict-declaration verifier needs its generated matrix.")
endif()

file(STRINGS "${PROJECT_STRICT_DECLARATION_MATRIX}" project_strict_declaration_records)
function(project_strict_declaration_has_duplicate records out_duplicate)
    set(project_strict_declaration_seen_records)
    foreach(project_strict_declaration_record IN LISTS records)
        list(FIND project_strict_declaration_seen_records "${project_strict_declaration_record}"
            project_strict_declaration_duplicate_index)
        if(NOT project_strict_declaration_duplicate_index EQUAL -1)
            set(${out_duplicate} TRUE PARENT_SCOPE)
            return()
        endif()
        list(APPEND project_strict_declaration_seen_records "${project_strict_declaration_record}")
    endforeach()
    set(${out_duplicate} FALSE PARENT_SCOPE)
endfunction()

foreach(project_strict_declaration_record IN LISTS project_strict_declaration_records)
    if(NOT project_strict_declaration_record MATCHES "^[^|]+[|]-(Wall|Wextra|Wpedantic|Werror)$")
        message(FATAL_ERROR "Strict-declaration matrix has an invalid record: ${project_strict_declaration_record}")
    endif()
endforeach()
project_strict_declaration_has_duplicate("${project_strict_declaration_records}" project_strict_declaration_duplicate)
if(project_strict_declaration_duplicate)
    message(FATAL_ERROR "Duplicate target-local strict declaration.")
endif()
set(project_strict_declaration_negative_records "negative|-Wall" "negative|-Wall")
project_strict_declaration_has_duplicate("${project_strict_declaration_negative_records}"
    project_strict_declaration_negative_duplicate)
if(NOT project_strict_declaration_negative_duplicate)
    message(FATAL_ERROR "Strict-declaration duplicate self-check failed.")
endif()
list(LENGTH project_strict_declaration_records project_strict_declaration_count)
if(project_strict_declaration_count EQUAL 0)
    message(FATAL_ERROR "Strict-declaration matrix is empty.")
endif()
message(STATUS "Strict-declaration uniqueness passed: ${project_strict_declaration_count} target-option declarations.")
