# Inspect the real transitive graph, not archive dead stripping.
set(pending ${PROJECT_CURRENT_VM_ARTIFACT_TARGET})
set(visited)
while(pending)
    list(POP_FRONT pending target)
    if(NOT TARGET ${target} OR target IN_LIST visited)
        continue()
    endif()
    list(APPEND visited ${target})
    if(target STREQUAL "vm-profile-tests" OR
            (target MATCHES "^core-machine(-observable|-runtime)?$" AND
             NOT NXVM_PRODUCT_MACHINE_KEY STREQUAL "model40"))
        message(FATAL_ERROR "Selected product links an unselected composition: ${target}")
    endif()
    get_target_property(sources ${target} SOURCES)
    foreach(source IN LISTS sources)
        if(source MATCHES "app-my5160/" AND NOT NXVM_PRODUCT_MACHINE_KEY STREQUAL "xt")
            message(FATAL_ERROR "Selected product links the My5160 App: ${source}")
        endif()
        if(source MATCHES "app-my5170/" AND NOT NXVM_PRODUCT_MACHINE_KEY STREQUAL "at")
            message(FATAL_ERROR "Selected product links the My5170 App: ${source}")
        endif()
        if(source MATCHES "app-mydeskpro386/" AND NOT NXVM_PRODUCT_MACHINE_KEY STREQUAL "model40")
            message(FATAL_ERROR "Selected product links the MyDeskPro386 App: ${source}")
        endif()
        if(NXVM_PRODUCT_MACHINE_KEY MATCHES "^(xt|at|model40)$" AND source MATCHES "app-nxvm/")
            message(FATAL_ERROR "Extracted App production graph depends on peer App: ${source}")
        endif()
        if(source MATCHES "app-nxvm/profiles/([^/]+)/")
            set(family "${CMAKE_MATCH_1}")
            if((NXVM_PRODUCT_MACHINE_KEY STREQUAL "xt" AND NOT family STREQUAL "xt") OR
               (NXVM_PRODUCT_MACHINE_KEY STREQUAL "model40" AND NOT family STREQUAL "model40") OR
               (NXVM_PRODUCT_MACHINE_KEY MATCHES "^(default|at)$" AND NOT family STREQUAL "default_profile"))
                message(FATAL_ERROR "Selected product has a sibling composition source: ${source}")
            endif()
        endif()
    endforeach()
    get_target_property(links ${target} LINK_LIBRARIES)
    get_target_property(interface_links ${target} INTERFACE_LINK_LIBRARIES)
    foreach(link IN LISTS links interface_links)
        string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" link "${link}")
        if(TARGET ${link})
            list(APPEND pending ${link})
        endif()
    endforeach()
endwhile()
if(NOT "vm-profile-selected" IN_LIST visited)
    message(FATAL_ERROR "Product lacks the selected composition")
endif()
get_target_property(definitions vm-profile-selected COMPILE_DEFINITIONS)
if("VM_PROFILE_BUILD_DEFAULT=1" IN_LIST definitions OR "VM_PROFILE_BUILD_5170=1" IN_LIST definitions)
    message(FATAL_ERROR "Fixed App source must not restore mixed AT constructor guards")
endif()
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/selected-composition-targets.txt" CONTENT "${visited}\n")
message(STATUS "Selected ${NXVM_PRODUCT_MACHINE_KEY} composition graph: OK")
