#ifndef IBMPC_NXVM_VERSION_INTERFACE_H
#define IBMPC_NXVM_VERSION_INTERFACE_H

#define NXVM_PRODUCT_NAME "Neko's x86 Virtual Machine"
#ifndef PRODUCT_BUILD_VERSION
#define PRODUCT_BUILD_VERSION "0.5.0000"
#endif
#define NXVM_PRODUCT_COPYRIGHT "Copyright (c) 2012-2026 Neko."

#endif
