if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/core/machine/machine.c")
set(machine_model "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_timing_model.c")
set(smoke "${PROJECT_SOURCE_DIR}/test/core/machine/core_machine_80286_instruction_timing_ledger_smoke.c")
set(evidence "${PROJECT_SOURCE_DIR}/docs/etc/evidence/t388-s7-80286-lsl-architecture-reconciliation.md")
foreach(path IN ITEMS "${machine}" "${smoke}" "${evidence}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "T388 80286 LSL reconciliation input is missing: ${path}")
    endif()
endforeach()
file(READ "${machine}" machine_text)
file(READ "${machine_model}" machine_model_text)
set(machine_text "${machine_text}${machine_model_text}")
file(READ "${smoke}" smoke_text)
file(READ "${evidence}" evidence_text)
function(t388_require text token)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 80286 LSL reconciliation drift: ${token}")
    endif()
endfunction()
foreach(token IN ITEMS "core_machine_80286_source_instruction_cost" "data->opcodes[prefixes + 1u] == 0x03u" "data->flagMem ? 16u : 14u")
    t388_require("${machine_text}" "${token}")
endforeach()
foreach(token IN ITEMS "timing_80286_lsl" "timing_80286_run(machine, &state, 1u, 14u)" "timing_80286_run(machine, &state, 1u, 16u)")
    t388_require("${smoke_text}" "${token}")
endforeach()
foreach(token IN ITEMS "M5:T388:S7:80286-LSL-ARCHITECTURE-RECONCILIATION:OK" "page-granularity is a 80386-only descriptor attribute" "register `14`, memory `16`")
    t388_require("${evidence_text}" "${token}")
endforeach()
message(STATUS "T388 80286 LSL architecture reconciliation passed.")