if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/core/machine/machine.c")
set(machine_model "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_timing_model.c")
set(preview "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_instructions.c")
set(preview_smoke "${PROJECT_SOURCE_DIR}/test/core/machine/core_machine_cpu_timing_preview_smoke.c")
set(timing_smoke "${PROJECT_SOURCE_DIR}/test/core/machine/core_machine_instruction_timing_smoke.c")
set(evidence "${PROJECT_SOURCE_DIR}/docs/etc/evidence/t388-s5-jcc-target-lexeme.md")
foreach(path IN ITEMS "${machine}" "${machine_model}" "${preview}" "${preview_smoke}" "${timing_smoke}" "${evidence}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "T388 Jcc target-lexeme input is missing: ${path}")
    endif()
endforeach()
foreach(item IN ITEMS machine preview preview_smoke timing_smoke evidence)
    file(READ "${${item}}" ${item}_text)
endforeach()
file(READ "${machine_model}" machine_model_text)
set(machine_text "${machine_text}${machine_model_text}")
function(t388_require text token)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 Jcc target-lexeme drift: ${token}")
    endif()
endfunction()
foreach(token IN ITEMS "core_machine_cpu_execution_preview_lexeme" "CORE_MACHINE_80386_JCC_TAKEN_TICKS" "core_machine_source_timing_mark_unallocated")
    t388_require("${machine_text}" "${token}")
    t388_require("${evidence_text}" "${token}")
endforeach()
t388_require("${preview_text}" "preview_mode = TYPE_TRUE")
t388_require("${preview_smoke_text}" "preview_test_taken_near_jcc_target")
t388_require("${preview_smoke_text}" "0x66u, 0x0fu, 0x84u")
t388_require("${timing_smoke_text}" "static const type_unsigned_8 jcc[]")
t388_require("${timing_smoke_text}" "result.ticks != 9u")
t388_require("${evidence_text}" "M5:T388:S5:JCC-TARGET-LEXEME:OK")
message(STATUS "T388 Jcc target-lexeme boundary passed.")
