if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/core/machine/machine.c")
set(machine_model "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_timing_model.c")
set(smoke "${PROJECT_SOURCE_DIR}/test/core/machine/core_machine_80286_instruction_timing_ledger_smoke.c")
set(evidence "${PROJECT_SOURCE_DIR}/docs/etc/evidence/t388-s6-80286-appendix-b-context.md")
foreach(path IN ITEMS "${machine}" "${smoke}" "${evidence}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "T388 80286 Appendix-B input is missing: ${path}")
    endif()
endforeach()
file(READ "${machine}" machine_text)
file(READ "${machine_model}" machine_model_text)
set(machine_text "${machine_text}${machine_model_text}")
file(READ "${smoke}" smoke_text)
file(READ "${evidence}" evidence_text)
function(t388_require text token)
    string(FIND "${text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 80286 Appendix-B drift: ${token}")
    endif()
endfunction()
foreach(token IN ITEMS "core_machine_80286_source_instruction_cost" "case 0x0fu:" "case 0x62u:" "case 0x63u:" "case 0x8cu:" "case 0x8eu:" "case 0xc4u: case 0xc5u:" "prefixes != 0u" "CORE_MACHINE_SOURCE_UNALLOCATED_TICKS")
    t388_require("${machine_text}" "${token}")
    t388_require("${evidence_text}" "${token}")
endforeach()
foreach(token IN ITEMS "timing_80286_lsl" "timing_80286_lar" "timing_80286_table_control" "timing_80286_ldt_task_registers")
    t388_require("${smoke_text}" "${token}")
endforeach()
t388_require("${evidence_text}" "M5:T388:S6:80286-APPENDIX-B-CONTEXT:OK")
message(STATUS "T388 80286 Appendix-B context passed.")