if(NOT DEFINED PROJECT_CTEST_TEST_FILE OR
    NOT EXISTS "${PROJECT_CTEST_TEST_FILE}")
    message(FATAL_ERROR "CTest registration file is required.")
endif()

file(STRINGS "${PROJECT_CTEST_TEST_FILE}" ctest_lines)
set(test_name)
set(unit_count 0)
set(integration_count 0)
foreach(line IN LISTS ctest_lines)
    set(property_test_name "")
    set(labels "")
    if(line MATCHES "^add_test\\(\\[=\\[([^]]+)\\]=\\]")
        set(test_name "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^add_test\\(\\\"([^\\\"]+)\\\"")
        set(test_name "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^set_tests_properties\\(\\[=\\[([^]]+)\\]=\\] PROPERTIES.*LABELS \\\"([^\"]*)\\\"")
        set(property_test_name "${CMAKE_MATCH_1}")
        set(labels "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^set_tests_properties\\(\\\"([^\\\"]+)\\\" PROPERTIES.*LABELS \\\"([^\\\"]*)\\\"")
        set(property_test_name "${CMAKE_MATCH_1}")
        set(labels "${CMAKE_MATCH_2}")
    endif()
    if(NOT property_test_name STREQUAL "")
        if(NOT property_test_name STREQUAL test_name)
            message(FATAL_ERROR "CTest property does not follow its test: ${property_test_name}")
        endif()
        list(FIND labels "unit" unit_index)
        list(FIND labels "integration" integration_index)
        if(unit_index EQUAL -1 AND integration_index EQUAL -1)
            message(FATAL_ERROR "CTest ${test_name} has no execution route.")
        endif()
        if(NOT unit_index EQUAL -1 AND NOT integration_index EQUAL -1)
            message(FATAL_ERROR "CTest ${test_name} belongs to two routes.")
        endif()
        if(NOT unit_index EQUAL -1)
            math(EXPR unit_count "${unit_count} + 1")
        else()
            math(EXPR integration_count "${integration_count} + 1")
        endif()
    endif()
endforeach()
if(unit_count EQUAL 0 OR integration_count EQUAL 0)
    message(FATAL_ERROR "Both unit and integration routes must be nonempty.")
endif()
message(STATUS "M5:T500:S4:TEST-ROUTE-PARTITION:OK:unit=${unit_count};integration=${integration_count}")
