if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
file(READ "${PROJECT_SOURCE_DIR}/src/core/machine/machine.c" source)
file(READ "${PROJECT_SOURCE_DIR}/docs/etc/evidence/t366-s10-80286-unallocated-publisher-inventory.md" evidence)
foreach(anchor IN ITEMS "if (prefixes != 0u)" "opcode >= 0xb0u && opcode <= 0xbfu" "core_machine_80286_source_timing_lookup" "CORE_MACHINE_SOURCE_UNALLOCATED_TICKS")
    string(FIND "${source}" "${anchor}" source_position)
    string(FIND "${evidence}" "${anchor}" evidence_position)
    if(source_position EQUAL -1 OR evidence_position EQUAL -1)
        message(FATAL_ERROR "T366 S10 publisher inventory drift: ${anchor}")
    endif()
endforeach()
string(FIND "${source}" "core_machine_80286_source_timing_ledger[] = {" ledger_start)
string(FIND "${source}" "core_machine_80386_source_timing_ledger[] = {" ledger_end)
string(FIND "${source}" "static C_INT core_machine_control_stack_source_instruction_cost" control_start)
string(FIND "${source}" "static C_INT core_machine_80286_source_instruction_cost" control_end)
if(ledger_start EQUAL -1 OR ledger_end EQUAL -1 OR control_start EQUAL -1 OR control_end EQUAL -1)
    message(FATAL_ERROR "T366 S10 publisher inventory bounds drift")
endif()
math(EXPR ledger_length "${ledger_end} - ${ledger_start}")
math(EXPR control_length "${control_end} - ${control_start}")
string(SUBSTRING "${source}" ${ledger_start} ${ledger_length} ledger)
string(SUBSTRING "${source}" ${control_start} ${control_length} control_source)
string(REGEX MATCHALL "CORE_MACHINE_SOURCE_TIMING_[A-Z0-9_]+" control_forms "${control_source}")
list(REMOVE_DUPLICATES control_forms)
foreach(form IN LISTS control_forms)
    string(FIND "${ledger}" "{ ${form}," ledger_form_position)
    if(ledger_form_position EQUAL -1)
        message(FATAL_ERROR "T366 S10 80286 control/stack form lacks ledger row: ${form}")
    endif()
endforeach()
message(STATUS "T366 S10 80286 unallocated publisher inventory passed.")
