if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/vm/composition/session/lifecycle.c" lifecycle)
file(READ "${PROJECT_SOURCE_DIR}/src/vm/composition/session/rom/external_pc_at.c" provider)
file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" cmake_source)

foreach(required "vm_session_external_pc_at_rom_provider"
        "core_machine_bind_firmware_provider")
    string(FIND "${lifecycle}" "${required}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "External-ROM lifecycle boundary missing: ${required}")
    endif()
endforeach()
string(FIND "${provider}" "core_machine_firmware_register_immutable_rom" position)
if(position EQUAL -1)
    message(FATAL_ERROR "External-ROM provider does not map immutable firmware")
endif()
foreach(forbidden "default_pc_at.c" "rom/bios.c" "rom/qdcga.c")
    string(FIND "${cmake_source}" "${forbidden}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "Generated product firmware remains in CMake: ${forbidden}")
    endif()
endforeach()

message(STATUS "M5:T515:S3:EXTERNAL-ROM-CLOSURE:OK")
