if(NOT DEFINED PROJECT_SOURCE_DIR OR NOT EXISTS "${PROJECT_SOURCE_DIR}/test/integration")
    message(FATAL_ERROR "T515 integration source root is required.")
endif()

file(GLOB_RECURSE integration_sources
    "${PROJECT_SOURCE_DIR}/test/integration/*.c"
    "${PROJECT_SOURCE_DIR}/test/integration/*.h")
foreach(source IN LISTS integration_sources)
    file(READ "${source}" text)
    if(text MATCHES "CopyFileA|session-floppy-[^\"]*\\.img|session-fixed-disk-[^\"]*\\.img|open_with_media_transform")
        message(FATAL_ERROR
            "T516 integration must use the YAML-declared VM media overlay, not copied media: ${source}")
    endif()
    if(text MATCHES "vm_session_create[ \t\r\n]*\\(")
        message(FATAL_ERROR "T515 integration must open only through session YAML: ${source}")
    endif()
    if(text MATCHES "vm_session_config[ \t\r\n]")
        message(FATAL_ERROR "T515 integration must not construct a session config: ${source}")
    endif()
    if(source MATCHES "/support/.*\\.c$" OR source MATCHES "\\\\support\\\\.*\\.c$")
        continue()
    endif()
    if(source MATCHES "\\.c$" AND NOT text MATCHES
        "integration_yaml_session_|vm_product_session_catalog_create")
        message(FATAL_ERROR "T515 integration lacks a YAML catalog/session consumer: ${source}")
    endif()
endforeach()
file(GLOB_RECURSE unit_sources "${PROJECT_SOURCE_DIR}/test/vm/*.c"
    "${PROJECT_SOURCE_DIR}/test/vm/*.h")
foreach(source IN LISTS unit_sources)
    file(READ "${source}" text)
    if(text MATCHES "vm_session_create[ \t\r\n]*\\(")
        message(FATAL_ERROR
            "T515 repository-only unit test must use in-memory assets: ${source}")
    endif()
    if(text MATCHES "vm_profile_byob_blob_load|GetFileAttributesA|CopyFileA|CreateFile")
        message(FATAL_ERROR
            "T515 repository-only unit test must not load an external asset: ${source}")
    endif()
endforeach()
file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" cmake_text)
if(cmake_text MATCHES "project_add_test\\([^\\n]*integration[^\\n]*(PROJECT_FDD_SMOKE_IMAGE|PROJECT_M1_FDD_SMOKE_IMAGE|PROJECT_HDD_SMOKE_IMAGE)")
    message(FATAL_ERROR
        "T515 integration must be registered through the YAML helper, not a media path.")
endif()
file(GLOB session_documents "${PROJECT_SOURCE_DIR}/assets/sessions/*.yaml")
if(session_documents STREQUAL "")
    message(FATAL_ERROR "T515 integration YAML session documents are required.")
endif()
foreach(session_document IN LISTS session_documents)
    file(READ "${session_document}" text)
    string(REGEX MATCHALL "[^\r\n]*\\.rom[^\r\n]*" rom_lines "${text}")
    if(rom_lines STREQUAL "")
        message(FATAL_ERROR "T515 session lacks an external ROM declaration: ${session_document}")
    endif()
    foreach(rom_line IN LISTS rom_lines)
        if(NOT rom_line MATCHES "nxvm-assets/profiles/.+\\.rom")
            message(FATAL_ERROR
                "T515 integration ROM must be declared from nxvm-assets: "
                "${session_document}: ${rom_line}")
        endif()
    endforeach()
endforeach()
message(STATUS "M5:T515:S3:INTEGRATION-YAML-BOUNDARY:OK")
