if(NOT DEFINED PROJECT_T344_STRICT_DECLARATION_MATRIX OR
    NOT EXISTS "${PROJECT_T344_STRICT_DECLARATION_MATRIX}")
    message(FATAL_ERROR "T344 strict-declaration verifier needs its generated matrix.")
endif()

file(STRINGS "${PROJECT_T344_STRICT_DECLARATION_MATRIX}" project_t344_records)
function(project_t344_has_duplicate records out_duplicate)
    set(project_t344_seen_records)
    foreach(project_t344_record IN LISTS records)
        list(FIND project_t344_seen_records "${project_t344_record}"
            project_t344_duplicate_index)
        if(NOT project_t344_duplicate_index EQUAL -1)
            set(${out_duplicate} TRUE PARENT_SCOPE)
            return()
        endif()
        list(APPEND project_t344_seen_records "${project_t344_record}")
    endforeach()
    set(${out_duplicate} FALSE PARENT_SCOPE)
endfunction()

foreach(project_t344_record IN LISTS project_t344_records)
    if(NOT project_t344_record MATCHES "^[^|]+[|]-(Wall|Wextra|Wpedantic|Werror)$")
        message(FATAL_ERROR "T344 strict-declaration matrix has an invalid record: ${project_t344_record}")
    endif()
endforeach()
project_t344_has_duplicate("${project_t344_records}" project_t344_duplicate)
if(project_t344_duplicate)
    message(FATAL_ERROR "T344 duplicate target-local strict declaration.")
endif()
set(project_t344_negative_records "negative|-Wall" "negative|-Wall")
project_t344_has_duplicate("${project_t344_negative_records}"
    project_t344_negative_duplicate)
if(NOT project_t344_negative_duplicate)
    message(FATAL_ERROR "T344 strict-declaration duplicate self-check failed.")
endif()
list(LENGTH project_t344_records project_t344_count)
if(project_t344_count EQUAL 0)
    message(FATAL_ERROR "T344 strict-declaration matrix is empty.")
endif()
message(STATUS "T344 strict-declaration uniqueness passed: ${project_t344_count} target-option declarations.")
