if(NOT DEFINED PROJECT_T345_T344_MATRIX_FILE OR
        NOT EXISTS "${PROJECT_T345_T344_MATRIX_FILE}")
    message(FATAL_ERROR "T345 requires the T344 direct-compilation matrix.")
endif()
if(NOT DEFINED PROJECT_T345_OWNERSHIP_MATRIX_FILE OR
        NOT EXISTS "${PROJECT_T345_OWNERSHIP_MATRIX_FILE}")
    message(FATAL_ERROR "T345 deferred ownership matrix is required.")
endif()
if(NOT DEFINED PROJECT_T345_S2_TARGETS_FILE OR
        NOT EXISTS "${PROJECT_T345_S2_TARGETS_FILE}")
    message(FATAL_ERROR "T345 S2 target inventory is required.")
endif()
if(NOT DEFINED PROJECT_T345_S3_ENTRIES_FILE OR
        NOT EXISTS "${PROJECT_T345_S3_ENTRIES_FILE}")
    message(FATAL_ERROR "T345 S3 production inventory is required.")
endif()
if(NOT DEFINED PROJECT_T345_S4_RESIDUAL_FILE OR
        NOT EXISTS "${PROJECT_T345_S4_RESIDUAL_FILE}")
    message(FATAL_ERROR "T345 S4 residual inventory is required.")
endif()

file(STRINGS "${PROJECT_T345_T344_MATRIX_FILE}" project_t345_t344_rows)
file(STRINGS "${PROJECT_T345_OWNERSHIP_MATRIX_FILE}" project_t345_ownership_rows)
file(STRINGS "${PROJECT_T345_S2_TARGETS_FILE}" project_t345_s2_targets)
file(STRINGS "${PROJECT_T345_S3_ENTRIES_FILE}" project_t345_s3_entries)
file(STRINGS "${PROJECT_T345_S4_RESIDUAL_FILE}" project_t345_s4_residual_entries)
set(project_t345_s3_targets)
foreach(project_t345_s3_entry IN LISTS project_t345_s3_entries)
    string(REPLACE "|" ";" project_t345_s3_fields "${project_t345_s3_entry}")
    list(LENGTH project_t345_s3_fields project_t345_s3_field_count)
    if(NOT project_t345_s3_field_count EQUAL 2)
        message(FATAL_ERROR "Malformed T345 S3 entry: ${project_t345_s3_entry}")
    endif()
    list(GET project_t345_s3_fields 0 project_t345_s3_target)
    list(APPEND project_t345_s3_targets "${project_t345_s3_target}")
endforeach()
set(project_t345_s4_residual_keys)
foreach(project_t345_s4_entry IN LISTS project_t345_s4_residual_entries)
    string(REPLACE "|" ";" project_t345_s4_fields "${project_t345_s4_entry}")
    list(LENGTH project_t345_s4_fields project_t345_s4_field_count)
    if(NOT project_t345_s4_field_count EQUAL 3)
        message(FATAL_ERROR "Malformed T345 S4 residual entry: ${project_t345_s4_entry}")
    endif()
    list(GET project_t345_s4_fields 0 project_t345_s4_target)
    list(GET project_t345_s4_fields 1 project_t345_s4_source)
    list(GET project_t345_s4_fields 2 project_t345_s4_domain)
    if(project_t345_s4_domain STREQUAL "")
        message(FATAL_ERROR "T345 S4 residual entry has no domain: ${project_t345_s4_entry}")
    endif()
    set(project_t345_s4_key "${project_t345_s4_target}|${project_t345_s4_source}")
    list(FIND project_t345_s4_residual_keys "${project_t345_s4_key}"
        project_t345_s4_duplicate_index)
    if(NOT project_t345_s4_duplicate_index EQUAL -1)
        message(FATAL_ERROR "Duplicate T345 S4 residual entry: ${project_t345_s4_key}")
    endif()
    list(APPEND project_t345_s4_residual_keys "${project_t345_s4_key}")
endforeach()
set(project_t345_expected_keys)
foreach(project_t345_row IN LISTS project_t345_t344_rows)
    string(REPLACE "|" ";" project_t345_fields "${project_t345_row}")
    list(LENGTH project_t345_fields project_t345_count)
    if(NOT project_t345_count EQUAL 4)
        message(FATAL_ERROR "Malformed T344 row in T345 verifier: ${project_t345_row}")
    endif()
    list(GET project_t345_fields 0 project_t345_target)
    list(GET project_t345_fields 1 project_t345_source)
    list(GET project_t345_fields 2 project_t345_status)
    list(FIND project_t345_s2_targets "${project_t345_target}" project_t345_s2_target_index)
    list(FIND project_t345_s3_targets "${project_t345_target}" project_t345_s3_target_index)
    if(project_t345_status STREQUAL "deferred" OR
            (project_t345_status STREQUAL "retained-strict" AND
            NOT project_t345_s2_target_index EQUAL -1 AND
            project_t345_source MATCHES "^tests/") OR
            (project_t345_status STREQUAL "retained-strict" AND
            NOT project_t345_s3_target_index EQUAL -1))
        list(APPEND project_t345_expected_keys "${project_t345_target}|${project_t345_source}")
    endif()
endforeach()

set(project_t345_seen_keys)
set(project_t345_owner_test_count 0)
set(project_t345_embedded_count 0)
set(project_t345_type_count 0)
set(project_t345_safe_production_count 0)
set(project_t345_mixed_count 0)
set(project_t345_expected_residual_keys)
foreach(project_t345_row IN LISTS project_t345_ownership_rows)
    string(REPLACE "|" ";" project_t345_fields "${project_t345_row}")
    list(LENGTH project_t345_fields project_t345_count)
    if(NOT project_t345_count EQUAL 4)
        message(FATAL_ERROR "Malformed T345 ownership row: ${project_t345_row}")
    endif()
    list(GET project_t345_fields 0 project_t345_target)
    list(GET project_t345_fields 1 project_t345_source)
    list(GET project_t345_fields 2 project_t345_class)
    list(GET project_t345_fields 3 project_t345_mechanism)
    set(project_t345_key "${project_t345_target}|${project_t345_source}")
    list(FIND project_t345_expected_keys "${project_t345_key}" project_t345_expected_index)
    if(project_t345_expected_index EQUAL -1)
        message(FATAL_ERROR "T345 ownership row is not a deferred T344 row: ${project_t345_key}")
    endif()
    list(FIND project_t345_seen_keys "${project_t345_key}" project_t345_seen_index)
    if(NOT project_t345_seen_index EQUAL -1)
        message(FATAL_ERROR "Duplicate T345 ownership row: ${project_t345_key}")
    endif()
    list(APPEND project_t345_seen_keys "${project_t345_key}")
    if(project_t345_class STREQUAL "project-owned-owner-test" AND
            project_t345_mechanism STREQUAL "s2-owner-test-strict-cohort")
        math(EXPR project_t345_owner_test_count "${project_t345_owner_test_count} + 1")
    elseif(project_t345_class STREQUAL "embedded-production-test" AND
            project_t345_mechanism STREQUAL "s3-production-owner-warning-remediation")
        math(EXPR project_t345_embedded_count "${project_t345_embedded_count} + 1")
        list(APPEND project_t345_expected_residual_keys "${project_t345_key}")
    elseif(project_t345_class STREQUAL "type-foundation-production" AND
            project_t345_mechanism STREQUAL "s3-safe-production-strict-cohort")
        math(EXPR project_t345_type_count "${project_t345_type_count} + 1")
    elseif(project_t345_class STREQUAL "safely-separable-production" AND
            project_t345_mechanism STREQUAL "s3-safe-production-strict-cohort")
        math(EXPR project_t345_safe_production_count "${project_t345_safe_production_count} + 1")
    elseif(project_t345_class STREQUAL "mixed-or-inherited-production" AND
            project_t345_mechanism STREQUAL "s3-ownership-separation-and-warning-remediation")
        math(EXPR project_t345_mixed_count "${project_t345_mixed_count} + 1")
        list(APPEND project_t345_expected_residual_keys "${project_t345_key}")
    else()
        message(FATAL_ERROR "Unknown T345 ownership class or mechanism: ${project_t345_row}")
    endif()
endforeach()

list(LENGTH project_t345_expected_keys project_t345_expected_count)
list(LENGTH project_t345_seen_keys project_t345_seen_count)
list(LENGTH project_t345_s2_targets project_t345_s2_target_count)
if(NOT project_t345_seen_count EQUAL project_t345_expected_count)
    message(FATAL_ERROR "T345 ownership matrix has ${project_t345_seen_count} rows; expected ${project_t345_expected_count}.")
endif()
if(NOT project_t345_owner_test_count EQUAL 186 OR
        NOT project_t345_embedded_count EQUAL 7 OR
        NOT project_t345_type_count EQUAL 1)
    message(FATAL_ERROR
        "Unexpected T345 ownership counts: tests=${project_t345_owner_test_count}, embedded=${project_t345_embedded_count}, type=${project_t345_type_count}.")
endif()
if(NOT project_t345_s2_target_count EQUAL 183)
    message(FATAL_ERROR "T345 S2 target inventory has ${project_t345_s2_target_count} entries; expected 183.")
endif()
list(LENGTH project_t345_s3_entries project_t345_s3_entry_count)
if(NOT project_t345_safe_production_count EQUAL 2 OR
        NOT project_t345_s3_entry_count EQUAL 3 OR
        NOT project_t345_mixed_count EQUAL 51)
    message(FATAL_ERROR
        "Unexpected T345 S3 counts: safe=${project_t345_safe_production_count}, entries=${project_t345_s3_entry_count}, mixed=${project_t345_mixed_count}.")
endif()
list(LENGTH project_t345_expected_residual_keys project_t345_expected_residual_count)
list(LENGTH project_t345_s4_residual_keys project_t345_s4_residual_count)
if(NOT project_t345_expected_residual_count EQUAL 58 OR
        NOT project_t345_s4_residual_count EQUAL 58)
    message(FATAL_ERROR
        "Unexpected T345 S4 residual counts: expected=${project_t345_expected_residual_count}, actual=${project_t345_s4_residual_count}.")
endif()
foreach(project_t345_expected_residual_key IN LISTS project_t345_expected_residual_keys)
    list(FIND project_t345_s4_residual_keys "${project_t345_expected_residual_key}"
        project_t345_s4_residual_index)
    if(project_t345_s4_residual_index EQUAL -1)
        message(FATAL_ERROR "Missing T345 S4 residual entry: ${project_t345_expected_residual_key}")
    endif()
endforeach()
foreach(project_t345_s4_residual_key IN LISTS project_t345_s4_residual_keys)
    list(FIND project_t345_expected_residual_keys "${project_t345_s4_residual_key}"
        project_t345_expected_residual_index)
    if(project_t345_expected_residual_index EQUAL -1)
        message(FATAL_ERROR "Unexpected T345 S4 residual entry: ${project_t345_s4_residual_key}")
    endif()
endforeach()
message(STATUS "T345 deferred ownership passed: ${project_t345_seen_count} rows (${project_t345_owner_test_count} owner tests, ${project_t345_embedded_count} embedded production tests, ${project_t345_type_count} type foundation, ${project_t345_safe_production_count} safely separable production, ${project_t345_mixed_count} mixed/inherited production, ${project_t345_expected_residual_count} exact residual production entries).")
