if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/src/vm/composition/session/session.c" session)
file(READ "${PROJECT_SOURCE_DIR}/src/vm/composition/session/lifecycle.c" lifecycle)
foreach(source IN ITEMS "${session}" "${lifecycle}")
    foreach(forbidden "profile_firmware" "VBIOS_" "qdkeyb")
        string(FIND "${source}" "${forbidden}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "Generated BIOS keyboard path remains: ${forbidden}")
        endif()
    endforeach()
endforeach()
message(STATUS "M5:T515:S3:EXTERNAL-ROM-KEYBOARD-CLOSURE:OK")
