if(NOT DEFINED PROJECT_SOURCE_DIR OR
    NOT DEFINED PROJECT_SPECIALIZED_TARGETS_FILE OR
    NOT DEFINED PROJECT_GATE_DEPENDENCIES_FILE OR
    NOT DEFINED PROJECT_CTEST_TEST_FILE)
    message(FATAL_ERROR "Current-gate separation verifier requires source, target-list, dependency-list, and CTest-testfile paths.")
endif()
if(NOT EXISTS "${PROJECT_SPECIALIZED_TARGETS_FILE}")
    message(FATAL_ERROR "Current specialized-verifier target list is missing.")
endif()
if(NOT EXISTS "${PROJECT_CTEST_TEST_FILE}")
    message(FATAL_ERROR "Current CTest testfile is missing.")
endif()
if(NOT EXISTS "${PROJECT_GATE_DEPENDENCIES_FILE}")
    message(FATAL_ERROR "Current gate dependency list is missing.")
endif()

file(STRINGS "${PROJECT_GATE_DEPENDENCIES_FILE}" dependency_lines)
set(dependency_section)
foreach(line IN LISTS dependency_lines)
    if(line STREQUAL "[smoke]")
        set(dependency_section smoke)
        set(found_smoke_section TRUE)
    elseif(line STREQUAL "[fast]")
        set(dependency_section fast)
        set(found_fast_section TRUE)
    elseif(line STREQUAL "[specialized]")
        set(dependency_section specialized)
        set(found_specialized_section TRUE)
    elseif(line)
        if(dependency_section STREQUAL smoke)
            list(APPEND smoke_dependencies "${line}")
        elseif(dependency_section STREQUAL fast)
            list(APPEND fast_dependencies "${line}")
        elseif(dependency_section STREQUAL specialized)
            list(APPEND specialized_dependencies "${line}")
        else()
            message(FATAL_ERROR "Current gate dependency list has an entry outside a section.")
        endif()
    endif()
endforeach()
if(NOT found_smoke_section OR NOT found_fast_section OR
    NOT found_specialized_section)
    message(FATAL_ERROR "Current gate dependency list is incomplete.")
endif()
foreach(target IN LISTS smoke_dependencies fast_dependencies)
    if(target MATCHES "^verify-[A-Za-z0-9-]+$")
        message(FATAL_ERROR "Smoke targets must not depend on specialized verifier target ${target}.")
    endif()
endforeach()

file(STRINGS "${PROJECT_SPECIALIZED_TARGETS_FILE}" specialized_targets)
foreach(target IN LISTS specialized_targets)
    list(FIND specialized_dependencies "${target}" target_index)
    if(target AND target_index EQUAL -1)
        message(FATAL_ERROR "Specialized gate omits ${target}.")
    endif()
endforeach()

file(READ "${PROJECT_SOURCE_DIR}/CMakePresets.json" presets)
string(JSON preset_count LENGTH "${presets}" buildPresets)
set(current_gate_index -1)
math(EXPR preset_last "${preset_count} - 1")
foreach(index RANGE ${preset_last})
    string(JSON preset_name GET "${presets}" buildPresets ${index} name)
    if(preset_name STREQUAL "current-gates-gcc")
        set(current_gate_index ${index})
        break()
    endif()
endforeach()
if(current_gate_index EQUAL -1)
    message(FATAL_ERROR "current-gates-gcc preset is missing.")
endif()
string(JSON current_gate_count LENGTH "${presets}" buildPresets
    ${current_gate_index} targets)
if(NOT current_gate_count EQUAL 2)
    message(FATAL_ERROR "current-gates-gcc must contain exactly smoke and specialized targets.")
endif()
set(current_gate_targets)
math(EXPR current_gate_last "${current_gate_count} - 1")
foreach(index RANGE ${current_gate_last})
    string(JSON current_gate_target GET "${presets}" buildPresets
        ${current_gate_index} targets ${index})
    list(APPEND current_gate_targets ${current_gate_target})
endforeach()
foreach(required_target IN ITEMS run-current-smokes verify-current-specialized-gates)
    list(FIND current_gate_targets ${required_target} target_index)
    if(target_index EQUAL -1)
        message(FATAL_ERROR "current-gates-gcc omits ${required_target}.")
    endif()
endforeach()

file(STRINGS "${PROJECT_CTEST_TEST_FILE}" ctest_lines)
set(current_test_name)
set(current_test_program)
set(current_programs)
set(current_media_programs)
set(current_nonmedia_programs)
foreach(line IN LISTS ctest_lines)
    set(current_property_match FALSE)
    if(line MATCHES "^add_test\\(\"([^\"]+)\" \"([^\"]+)\"")
        set(current_test_name "${CMAKE_MATCH_1}")
        set(current_test_program "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^add_test\\(\\[=\\[([^]]+)\\]=\\] \"([^\"]+)\"")
        set(current_test_name "${CMAKE_MATCH_1}")
        set(current_test_program "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^set_tests_properties\\(\"([^\"]+)\" PROPERTIES +LABELS \"([^\"]*)\"")
        set(current_property_name "${CMAKE_MATCH_1}")
        set(current_test_labels "${CMAKE_MATCH_2}")
        set(current_property_match TRUE)
    elseif(line MATCHES "^set_tests_properties\\(\\[=\\[([^]]+)\\]=\\] PROPERTIES +LABELS \"([^\"]*)\"")
        set(current_property_name "${CMAKE_MATCH_1}")
        set(current_test_labels "${CMAKE_MATCH_2}")
        set(current_property_match TRUE)
    endif()
    if(current_property_match)
        if(NOT current_property_name STREQUAL current_test_name)
            message(FATAL_ERROR "CTest property does not match its preceding test declaration.")
        endif()
        list(FIND current_test_labels "current-gate" current_gate_index)
        list(FIND current_test_labels "media" media_index)
        if(NOT media_index EQUAL -1 AND current_gate_index EQUAL -1)
            message(FATAL_ERROR "Media CTest ${current_test_name} is outside the current-gate selection.")
        endif()
        if(NOT current_gate_index EQUAL -1)
            get_filename_component(current_test_executable
                "${current_test_program}" NAME_WE)
            list(APPEND current_programs "${current_test_executable}")
            if(media_index EQUAL -1)
                list(APPEND current_nonmedia_programs "${current_test_executable}")
            else()
                list(APPEND current_media_programs "${current_test_executable}")
            endif()
        endif()
    endif()
endforeach()

list(LENGTH current_programs current_count)
list(LENGTH current_media_programs current_media_count)
list(LENGTH current_nonmedia_programs current_nonmedia_count)
if(current_count EQUAL 0)
    message(FATAL_ERROR "Current CTest selection is empty; refusing to verify an empty gate.")
endif()
math(EXPR current_partition_count
    "${current_media_count} + ${current_nonmedia_count}")
if(NOT current_count EQUAL current_partition_count)
    message(FATAL_ERROR "Current CTest media and non-media selections do not partition the full current selection.")
endif()
foreach(program IN LISTS current_programs)
    list(FIND smoke_dependencies "${program}" smoke_program_index)
    if(smoke_program_index EQUAL -1)
        message(FATAL_ERROR "run-current-smokes omits current CTest executable ${program}.")
    endif()
endforeach()
foreach(program IN LISTS current_nonmedia_programs)
    list(FIND fast_dependencies "${program}" fast_program_index)
    if(fast_program_index EQUAL -1)
        message(FATAL_ERROR "run-current-fast-smokes omits non-media current executable ${program}.")
    endif()
endforeach()
foreach(program IN LISTS current_media_programs)
    list(FIND fast_dependencies "${program}" fast_program_index)
    if(NOT fast_program_index EQUAL -1)
        message(FATAL_ERROR "run-current-fast-smokes must not build media current executable ${program}.")
    endif()
endforeach()

message(STATUS "M5:T327:S1:CURRENT-GATE-SEPARATION:OK: full=${current_count};media=${current_media_count};non-media=${current_nonmedia_count}")
