if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(machine "${PROJECT_SOURCE_DIR}/src/core/machine/machine.c")
set(cpu "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_instructions.c")
set(header "${PROJECT_SOURCE_DIR}/src/core/machine/cpu_instructions.h")
set(smoke "${PROJECT_SOURCE_DIR}/tests/machine/core_machine_lar_lsl_s57_smoke.c")
set(evidence "${PROJECT_SOURCE_DIR}/docs/etc/evidence/t388-s8-80386-lsl-granularity-capture.md")
foreach(path IN ITEMS "${machine}" "${cpu}" "${header}" "${smoke}" "${evidence}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "T388 80386 LSL input is missing: ${path}")
    endif()
endforeach()
file(READ "${machine}" machine_text)
file(READ "${cpu}" cpu_text)
file(READ "${header}" header_text)
file(READ "${smoke}" smoke_text)
file(READ "${evidence}" evidence_text)
foreach(token IN ITEMS "source_lsl_granularity_valid" "source_lsl_page_granular")
    foreach(text IN ITEMS "${cpu_text}" "${header_text}")
        string(FIND "${text}" "${token}" position)
        if(position EQUAL -1)
            message(FATAL_ERROR "T388 80386 LSL capture drift: ${token}")
        endif()
    endforeach()
endforeach()
foreach(token IN ITEMS "memory ? 26u : 25u" "memory ? 21u : 20u")
    string(FIND "${machine_text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 80386 LSL timing-row drift: ${token}")
    endif()
endforeach()
foreach(token IN ITEMS "lar_lsl_s57_test_80386_timing_granularity" "20u, 25u, 21u, 26u")
    string(FIND "${smoke_text}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "T388 80386 LSL smoke drift: ${token}")
    endif()
endforeach()
string(FIND "${evidence_text}" "M5:T388:S8:80386-LSL-GRANULARITY-CAPTURE:OK" position)
if(position EQUAL -1)
    message(FATAL_ERROR "T388 80386 LSL evidence marker is missing")
endif()
message(STATUS "T388 80386 LSL granularity capture passed.")