foreach(required IN ITEMS PROJECT_T344_CURRENT_TARGETS_FILE
        PROJECT_T344_CURRENT_AUXILIARY_TESTS_FILE PROJECT_T344_CTEST_TEST_FILE)
    if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
        message(FATAL_ERROR "T344 registration input is required: ${required}")
    endif()
endforeach()

file(STRINGS "${PROJECT_T344_CURRENT_TARGETS_FILE}" targets)
file(STRINGS "${PROJECT_T344_CURRENT_AUXILIARY_TESTS_FILE}" auxiliary)
file(STRINGS "${PROJECT_T344_CTEST_TEST_FILE}" ctest_lines)
set(registered)
foreach(line IN LISTS ctest_lines)
    if(line MATCHES "^add_test\\(\\[=\\[(unit|integration)\\.([^]]+)\\]=\\]")
        list(APPEND registered "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^add_test\\(\\\"(unit|integration)\\.([^\\\"]+)\\\"")
        list(APPEND registered "${CMAKE_MATCH_2}")
    endif()
endforeach()
foreach(target IN LISTS targets auxiliary)
    list(FIND registered "${target}" registered_index)
    if(registered_index EQUAL -1)
        message(FATAL_ERROR "T344 target lacks a CTest route: ${target}")
    endif()
endforeach()
if(DEFINED PROJECT_T515_YAML_BOOT_CASES_FILE)
    if(NOT EXISTS "${PROJECT_T515_YAML_BOOT_CASES_FILE}")
        message(FATAL_ERROR "T515 YAML boot registration input is missing.")
    endif()
    file(STRINGS "${PROJECT_T515_YAML_BOOT_CASES_FILE}" matrix_cases)
    list(LENGTH matrix_cases matrix_case_count)
    if(NOT matrix_case_count EQUAL 20)
        message(FATAL_ERROR "T515 YAML matrix registration must retain exactly twenty historical rows.")
    endif()
    foreach(matrix_case IN LISTS matrix_cases)
        list(FIND registered "${matrix_case}" matrix_case_index)
        if(matrix_case_index EQUAL -1)
            message(FATAL_ERROR "T515 YAML boot case lacks a CTest route: ${matrix_case}")
        endif()
        list(REMOVE_ITEM registered "${matrix_case}")
    endforeach()
endif()
list(SORT registered)
list(REMOVE_DUPLICATES registered)
list(LENGTH targets target_count)
list(LENGTH auxiliary auxiliary_count)
math(EXPR expected_count "${target_count} + ${auxiliary_count}")
list(LENGTH registered registered_count)
if(NOT registered_count EQUAL expected_count)
    message(FATAL_ERROR "T344 registration has an unexpected test count.")
endif()
message(STATUS "M5:T500:S4:TEST-NO-DUAL-REGISTRATION:OK:${registered_count}")
