if(NOT DEFINED CORPUS_ROOT OR NOT DEFINED CORPUS_NAME)
    message(FATAL_ERROR "CORPUS_ROOT and CORPUS_NAME are required")
endif()

file(REAL_PATH "${CORPUS_ROOT}" corpus_root)
set(corpus_manifest "${corpus_root}/MANIFEST.sha256")
if(NOT EXISTS "${corpus_manifest}")
    message(FATAL_ERROR "missing ${CORPUS_NAME} manifest: ${corpus_manifest}")
endif()

file(STRINGS "${corpus_manifest}" manifest_lines)
set(manifest_paths)
set(manifest_revision FALSE)
foreach(line IN LISTS manifest_lines)
    if(line MATCHES "^# corpus-revision: .+$")
        set(manifest_revision TRUE)
    elseif(line MATCHES "^#" OR line STREQUAL "")
        continue()
    elseif(NOT line MATCHES "^([0-9A-F]+)  (.+)$")
        message(FATAL_ERROR "invalid ${CORPUS_NAME} manifest line: ${line}")
    else()
        set(expected_hash "${CMAKE_MATCH_1}")
        set(relative_path "${CMAKE_MATCH_2}")
        string(LENGTH "${expected_hash}" hash_length)
        if(NOT hash_length EQUAL 64)
            message(FATAL_ERROR "invalid ${CORPUS_NAME} manifest hash: ${relative_path}")
        endif()
        if(relative_path IN_LIST manifest_paths)
            message(FATAL_ERROR "duplicate ${CORPUS_NAME} manifest path: ${relative_path}")
        endif()
        set(source_path "${corpus_root}/${relative_path}")
        if(NOT EXISTS "${source_path}" OR IS_DIRECTORY "${source_path}")
            message(FATAL_ERROR "missing ${CORPUS_NAME} source: ${relative_path}")
        endif()
        file(READ "${source_path}" contents)
        string(FIND "${contents}" "\r" carriage_return)
        if(NOT carriage_return EQUAL -1)
            message(FATAL_ERROR "${CORPUS_NAME} source must use LF: ${relative_path}")
        endif()
        file(SHA256 "${source_path}" actual_hash)
        string(TOUPPER "${actual_hash}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "${CORPUS_NAME} manifest mismatch: ${relative_path}")
        endif()
        list(APPEND manifest_paths "${relative_path}")
    endif()
endforeach()
if(NOT manifest_revision)
    message(FATAL_ERROR "${CORPUS_NAME} manifest has no corpus revision")
endif()

file(GLOB_RECURSE actual_paths RELATIVE "${corpus_root}" "${corpus_root}/*")
foreach(relative_path IN LISTS actual_paths)
    if(IS_DIRECTORY "${corpus_root}/${relative_path}" OR
       relative_path STREQUAL "MANIFEST.sha256")
        continue()
    endif()
    if(NOT relative_path IN_LIST manifest_paths)
        message(FATAL_ERROR "${CORPUS_NAME} manifest missing path: ${relative_path}")
    endif()
endforeach()
foreach(relative_path IN LISTS manifest_paths)
    if(NOT relative_path IN_LIST actual_paths)
        message(FATAL_ERROR "${CORPUS_NAME} manifest stale path: ${relative_path}")
    endif()
endforeach()

message(STATUS "${CORPUS_NAME} manifest verified: ${corpus_root}")
