cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED PRODUCT_ROOT)
    set(PRODUCT_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components debug xasm32 surface)
set(edges_debug common/machine product/xasm32 lib/storage lib/types)
set(edges_xasm32 lib/types)
set(edges_surface common/machine common/session common/ui product/debug lib/kvm-base lib/types)

function(check_edge owner dependency)
    if(NOT dependency STREQUAL "product/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden Product edge: ${owner} -> ${dependency}")
    endif()
endfunction()

function(component_for_target target out_component)
    if(target STREQUAL "types" OR target STREQUAL "base" OR target STREQUAL "console" OR
       target STREQUAL "console-broker" OR target STREQUAL "storage" OR
       target STREQUAL "kvm-base" OR target STREQUAL "kvm-window" OR target STREQUAL "kvm-console")
        set(${out_component} "lib/${target}" PARENT_SCOPE)
    elseif(target MATCHES "^common-(machine|session|ui)$")
        string(REGEX REPLACE "^common-" "common/" component "${target}")
        set(${out_component} "${component}" PARENT_SCOPE)
    elseif(target STREQUAL "product-xasm32")
        set(${out_component} "product/xasm32" PARENT_SCOPE)
    elseif(target STREQUAL "product-debug")
        set(${out_component} "product/debug" PARENT_SCOPE)
    elseif(target MATCHES "^product-surface(-.*)?$")
        set(${out_component} "product/surface" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unknown Product link target: ${target}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${PRODUCT_ROOT}" "${PRODUCT_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "Product must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "^(debug|xasm32|surface)/[^/]+\\.[ch]$")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    file(READ "${PRODUCT_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(memset|memcpy|memmove|memcmp|memchr|strlen|strcmp|strchr|strtok|calloc|malloc|realloc|free|snprintf)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw CRT vocabulary in Product; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "(^|[^A-Za-z0-9_])(U?INT[A-Z0-9_]*|SIZE|PTRDIFF|WCHAR|WINT)_(MAX|MIN)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "Raw integer limit in Product; use Lib Types: ${path}")
    endif()
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|WaitForSingleObject|CreateEvent[A-W]?|pthread_")
        message(FATAL_ERROR "Platform implementation in Product: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(product|common|emulator|lib)/[^/]+/[^/]+\\.h$")
            message(FATAL_ERROR "Noncanonical Product include: ${header}")
        endif()
        string(REGEX MATCH "^([^/]+)/([^/]+)/([^/]+\\.h)$" _ "${header}")
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_3}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "product/${owner}")
            if(NOT EXISTS "${PRODUCT_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local Product header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in Product: ${header}")
        endif()
    endforeach()
endforeach()

file(READ "${PRODUCT_ROOT}/CMakeLists.txt" build_source)
string(REGEX REPLACE "#[^\n]*" "" build_source "${build_source}")
string(REGEX MATCHALL "target_link_libraries[ \t\r\n]*\\([^)]*\\)" links "${build_source}")
foreach(link IN LISTS links)
    string(REGEX REPLACE "^target_link_libraries[ \t\r\n]*\\(|\\)$" "" args "${link}")
    string(REGEX REPLACE "[ \t\r\n]+" ";" args "${args}")
    list(POP_FRONT args target)
    component_for_target("${target}" owner_component)
    string(REGEX REPLACE "^product/" "" owner "${owner_component}")
    foreach(dependency_target IN LISTS args)
        if(dependency_target MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$" OR dependency_target STREQUAL "")
            continue()
        endif()
        component_for_target("${dependency_target}" dependency)
        check_edge("${owner}" "${dependency}")
    endforeach()
endforeach()
message(STATUS "Product platform and component boundaries verified")
