#ifndef IBMPC_PRODUCT_VERSION_INTERFACE_H
#define IBMPC_PRODUCT_VERSION_INTERFACE_H

#define PRODUCT_NAME "Neko's x86 Virtual Machine"
#ifndef PRODUCT_BUILD_VERSION
#define PRODUCT_BUILD_VERSION "0.5.0000"
#endif
#define PRODUCT_COPYRIGHT "Copyright (c) 2012-2026 Neko."

#endif
